### ISSUE TITLE
Unix Agent Poller Errors

### ISSUE THREAD

**Issue by lehuizi** [librenms/librenms#11101]
Hey! Since the automated upgrade to 1.60 I am getting errors when polling devices with unix-agent enabled.

```
LibreNMS UNIX Agent: 
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\Database\Eloquent\Model::throwBadMethodCallException('pollingTarget')
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1618): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'pollingTarget', Array)
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1630): Illuminate\Database\Eloquent\Model->__call('pollingTarget', Array)
#3 /opt/librenms/includes/polling/unix-agent.inc.php(15): Illuminate\Database\Eloquent\Model::__callStatic('pollingTarget', Array)
#4 /opt/librenms/includes/polling/functions.inc.php(315): include('/opt/librenms/i...')
#5 /opt/librenms/poller.php(174): poll_device(Array, false)
#6 {main}
Error in unix-agent module. Call to undefined method App\Models\Device::pollingTarget()
```

**Comment by lehuizi** [comment]
The problem is, that the method "pollingTarget" doesn't exist.

**Comment by kkrumm1** [comment]
No need to open a issue. You already have submitted the fix as a PR.

**Comment by lehuizi** [comment]
@kkrumm1 I opened the issue before i decided to create an PR. :)
