### ISSUE TITLE
Webui broke after 1.64.1-41-g62ca4ea

### ISSUE THREAD

**Issue by famahmou** [librenms/librenms#11817]
Whoops, looks like something went wrong. Check your librenms.log.
Check your log for more details. (librenms.log)

from librenms.log:

[2020-06-12 15:38:34] production.ERROR: Target class [2fa] does not exist. {"userId":1,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [2fa] does not exist. at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php:805)
[stacktrace]
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()

**Comment by famahmou** [comment]
more errors in librenms.log:
[2020-06-12 15:30:29] production.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"' at line 1 (SQL: SELECT * FROM devices,ports WHERE (devices.device_id = 76 AND devices.device_id = ports.device_id) AND (((ports.ifInOctets_rate*8) / ports.ifSpeed)*100) >= 90 AND ports.ifType REGEXP "ethernet" = ") (SQL: SELECT * FROM devices,ports WHERE (devices.device_id = 76 AND devices.device_id = ports.device_id) AND (((ports.ifInOctets_rate*8) / ports.ifSpeed)*100) >= 90 AND ports.ifType REGEXP "ethernet" = ")#0 /opt/librenms/LibreNMS/Alert/AlertRules.php(74): dbFetchRows('SELECT * FROM d...', Array)
#1 /opt/librenms/poller.php(156): LibreNMS\Alert\AlertRules->runRules(76)
#2 {main}
