### ISSUE TITLE
./lnms migrate fails SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes

### ISSUE THREAD

**Issue by joelsdc** [librenms/librenms#13131]
### The problem

I can't run the db upgrade command:

```
$ ./lnms migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migrating: 2020_12_14_091314_create_port_groups_table

In Connection.php line 692:

  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes (SQL: alter table `port_groups` add unique `port_groups_name_unique`(`name`))


In Exception.php line 18:

  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes


In PDOStatement.php line 112:

  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes


$
```

I've tried the workarounds I've read about modifying MySQL config params:

```
innodb-file-format=barracuda
innodb-file-per-table=ON
innodb-large-prefix=ON
innodb_default_row_format = 'DYNAMIC'
```

### Output of ./validate.php

```txt
$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.7.0-64-g43cd9b0c7
DB Schema | 2020_12_14_091314_create_port_group_port_table (205)
PHP       | 7.4.22
Python    | 3.6.9
MySQL     | 10.5.12-MariaDB-1:10.5.12+maria~bionic
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 2.1.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[FAIL]  Your database is out of date!
	[FIX]:
	./lnms migrate
$
```

### Anything in the logs that might be useful for us?

When trying to login:
```
[2021-08-12 08:12:15] production.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'librenms.isis_adjacencies' doesn't exist (SQL: select count(*) as aggregate from `isis_adjacencies`) (View: /opt/librenms/resources/views/layouts/librenmsv1.blade.php) (View: /opt/librenms/resources/views/layouts/librenmsv1.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'librenms.isis_adjacencies' doesn't exist (SQL: select count(*) as aggregate from `isis_adjacencies`) (View: /opt/librenms/resources/views/layouts/librenmsv1.blade.php) (View: /opt/librenms/resources/views/layouts/librenmsv1.blade.php) at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:692)
[stacktrace]
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(793): Illuminate\\Http\\Response->__construct()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(763): Illuminate\\Routing\\Router::toResponse()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /opt/librenms/app/Http/Middleware/LoadUserPreferences.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\LoadUserPreferences->handle()
#13 /opt/librenms/app/Http/Middleware/VerifyTwoFactor.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\VerifyTwoFactor->handle()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#19 /opt/librenms/app/Http/Middleware/LegacyExternalAuth.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\LegacyExternalAuth->handle()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#25 /opt/librenms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#27 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#28 /opt/librenms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#30 /opt/librenms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#32 /opt/librenms/app/Http/Middleware/CheckInstalled.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckInstalled->handle()
#34 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#36 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#37 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#38 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#39 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#40 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#41 /opt/librenms/vendor/genealabs/laravel-caffeine/src/Http/Middleware/LaravelCaffeineDripMiddleware.php(11): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): GeneaLabs\\LaravelCaffeine\\Http\\Middleware\\LaravelCaffeineDripMiddleware->handle()
#43 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#46 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#48 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#49 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#51 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#53 /opt/librenms/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#55 /opt/librenms/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#57 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#59 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#60 /opt/librenms/html/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#61 {main}
```

**Comment by joelsdc** [comment]
As the db is not up-to-date, when I try to login I get the: `Whoops, looks like something went wrong. Check your librenms.log.
`

I believe when I finish the DB upgrade everything should be solved as if I run it with `--pretend` I can see the creation of the missing tables the log is complaining about, just that it's the last step (`CreateIsisAdjacenciesTable`)

**Comment by joelsdc** [comment]
This is the output of `./lnms migrate --pretend`:

```
$ ./lnms migrate --pretend
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

CreatePortGroupsTable: select * from information_schema.tables where table_schema = ? and table_name = ? and table_type = 'BASE TABLE'
CreatePortGroupsTable: create table `port_groups` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `desc` varchar(255) null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePortGroupsTable: alter table `port_groups` add unique `port_groups_name_unique`(`name`)
MigrateToUtf8mb4: ALTER SCHEMA `librenms` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
MigrateToUtf8mb4: select `TABLE_NAME` from `information_schema`.`tables` where `table_schema` = ?
MigrateToUtf8mb4: select * from `information_schema`.`columns` where `table_schema` = ? and `CHARACTER_SET_NAME` is not null and `COLLATION_NAME` is not null and (`CHARACTER_SET_NAME` != ? or `COLLATION_NAME` != ?)
AddForeignKeysToPortGroupPortTable: alter table `port_group_port` add constraint `port_group_port_port_group_id_foreign` foreign key (`port_group_id`) references `port_groups` (`id`) on delete CASCADE
AddForeignKeysToPortGroupPortTable: alter table `port_group_port` add constraint `port_group_port_port_id_foreign` foreign key (`port_id`) references `ports` (`port_id`) on delete CASCADE
CreateSessionsTable: create table `sessions` (`id` varchar(255) not null, `user_id` bigint unsigned null, `ip_address` varchar(45) null, `user_agent` text null, `payload` text not null, `last_activity` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateSessionsTable: alter table `sessions` add primary key `sessions_id_primary`(`id`)
CreateSessionsTable: alter table `sessions` add index `sessions_user_id_index`(`user_id`)
CreateSessionsTable: alter table `sessions` add index `sessions_last_activity_index`(`last_activity`)
SlasAddRttField: ALTER TABLE slas CHANGE sla_nr sla_nr INT UNSIGNED NOT NULL
SlasAddRttField: alter table `slas` add `rtt` double(8, 2) unsigned null after `rtt_type`
AlterBillHistoryMaxMin: alter table `bill_history` add `bill_peak_out` bigint null after `traf_total`, add `bill_peak_in` bigint null after `bill_peak_out`
AddSyslogIndexes: alter table `syslog` add index `syslog_device_id_program_index`(`device_id`, `program`)
AddSyslogIndexes: alter table `syslog` add index `syslog_device_id_priority_index`(`device_id`, `priority`)
CreateIsisAdjacenciesTable: create table `isis_adjacencies` (`id` int unsigned not null auto_increment primary key, `device_id` int not null, `port_id` int not null, `ifIndex` int not null, `isisISAdjState` varchar(13) not null, `isisISAdjNeighSysType` varchar(128) not null, `isisISAdjNeighSysID` varchar(128) not null, `isisISAdjNeighPriority` varchar(128) not null, `isisISAdjLastUpTime` bigint unsigned not null, `isisISAdjAreaAddress` varchar(128) not null, `isisISAdjIPAddrType` varchar(128) not null, `isisISAdjIPAddrAddress` varchar(128) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateIsisAdjacenciesTable: alter table `isis_adjacencies` add index `isis_adjacencies_device_id_index`(`device_id`)
CreateIsisAdjacenciesTable: alter table `isis_adjacencies` add index `isis_adjacencies_port_id_index`(`port_id`)
CreateIsisAdjacenciesTable: alter table `isis_adjacencies` add index `isis_adjacencies_ifindex_index`(`ifIndex`)
$
```

I *think* that if I alter the `port_groups.name` to VARCHAR(191) it should continue, but I don't the side-effects this can cause.

```sql
MariaDB [librenms]> show create table port_groups \G;
*************************** 1. row ***************************
       Table: port_groups
Create Table: CREATE TABLE `port_groups` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `desc` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
1 row in set (0.000 sec)

ERROR: No query specified

MariaDB [librenms]>
```

**Comment by joelsdc** [comment]
So the problem was that although I set the params as needed:

```
innodb-file-format=barracuda
innodb-file-per-table=ON
innodb-large-prefix=ON
innodb_default_row_format = 'DYNAMIC'
```

The table(s) already exist so these commands didn't actually change anything for them.

After doing a full db dump & drop db & restore db (having the above previously parameters set) the tables are created on disk with the correct config and the DB migration was able to continue without any more issues.

I'm leaving this info here in case someone else runs into the same problem.

Cheers!
