### ISSUE TITLE
poller-wrapper.py not working after tonight's automated update (28.09.2021 00:15)

### ISSUE THREAD

**Issue by brointhemix** [librenms/librenms#13282]
### The problem

Hello LibreNMS Team,

I can see that since today's regular automated update schedule (28.09.2021 00:15), the poller-wrapper.py process has stopped working:

= = =
[librenms@librenms1 ~]$ /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16
Cronic detected failure or error output for the command:
/opt/librenms/poller-wrapper.py 16

RESULT CODE: 1

ERROR OUTPUT:
Traceback (most recent call last):
  File "/opt/librenms/LibreNMS/__init__.py", line 154, in get_config_data
    import dotenv
ModuleNotFoundError: No module named 'dotenv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/librenms/poller-wrapper.py", line 38, in <module>
    config = LibreNMS.get_config_data(os.path.dirname(os.path.realpath(__file__)))
  File "/opt/librenms/LibreNMS/__init__.py", line 166, in get_config_data
    % (env_path, exc)
UnboundLocalError: local variable 'env_path' referenced before assignment

STANDARD OUTPUT:
[librenms@librenms1 ~]$
= = =

I managed to fix it quickly by installing python-dotenv module by hand using pip:

`# pip3 install python-dotenv`

I am on CentOS 8 Stream, 'dnf update' was done like a week or so ago. This is the official LXC image from the LXC project.

### Output of ./validate.php

```txt
[librenms@librenms1 ~]$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.9.0-27-gbfa200f3f
DB Schema | 2021_25_01_0129_isis_adjacencies_nullable (217)
PHP       | 7.3.20
Python    | 3.6.8
MySQL     | 10.5.12-MariaDB
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### Anything in the logs that might be useful for us?

```txt
Could not find anything in the logs.
```

**Comment by royvandongen** [comment]
i too had this issue, and "fixed" it exactly the same way as you did. I am running Ubuntu 20.04.

**Comment by TD-er** [comment]
Here the same problem, but different error.
Nothing is polled since the same timestamp as mentioned in this issue.

When I try to run the poller.php from the command line it does seem to work just fine, but it is not called from the poller-wrapper.py with the following error:

```
Cronic detected failure or error output for the command:
/opt/librenms/poller-wrapper.py 16

RESULT CODE: 1

ERROR OUTPUT:
ERROR: Could not execute command [['/usr/bin/env', 'php', '/opt/librenms/config_to_json.php']]: Expecting value: line 1 column 1 (char 0)
Could not run poller wrapper. Missing config

STANDARD OUTPUT:
```

I also ran the daily.sh script, but doesn't seem to fix this.

**Comment by Jellyfrog** [comment]
Its not the same problem at all? create a new issue

**Comment by brointhemix** [comment]
Thanks a bunch!!!

**Comment by murrant** [comment]
@Jellyfrog that doesn't fix this issue.

This issue is caused by stderr output when running config_to_json.php.

Often this is caused by bad settings in snmp.conf with the snmp php module enabled.
To work-around this issue fix your snmp.conf @brointhemix 

This might work around your bad snmp.conf #13295
