### ISSUE TITLE
The requested URL was not found on this server.

### ISSUE THREAD

**Issue by sbakara** [librenms/librenms#13349]
### The problem

I'm trying to install LibreNMS on Ubuntu 18.04. This went on without a hitch until I tried to access http://librenms.example.com/install.php on my browser. In the apache2 logs, error I get is 
`[php7:error] [pid 4630] [client x.x.x.x:60872] script '/var/www/html/install.php' not found or unable to stat`
Your help would be highly appreciated. 

### Output of ./validate.php

```txt
PHP Warning:  include(Illuminate/Support/Str.php): Failed to open stream: No such file or directory in /opt/librenms/validate.php on line 71
PHP Warning:  include(): Failed opening 'Illuminate/Support/Str.php' for inclusion (include_path='.:/usr/share/php') in /opt/librenms/validate.php on line 71
PHP Fatal error:  Uncaught Error: Class "Illuminate\Support\Str" not found in /opt/librenms/LibreNMS/Config.php:129
Stack trace:
#0 /opt/librenms/LibreNMS/Util/Git.php(34): LibreNMS\Config::get()
#1 /opt/librenms/LibreNMS/Util/Version.php(40): LibreNMS\Util\Git::repoPresent()
#2 /opt/librenms/LibreNMS/Util/Version.php(45): LibreNMS\Util\Version->__construct()
#3 /opt/librenms/includes/common.php(987): LibreNMS\Util\Version::get()
#4 /opt/librenms/validate.php(73): version_info()
#5 [internal function]: {closure}()
#6 {main}
  thrown in /opt/librenms/LibreNMS/Config.php on line 129
[FAIL]  config.php does not exist, please copy config.php.default to config.php

Warning: include(Illuminate/Support/Str.php): Failed to open stream: No such file or directory in /opt/librenms/validate.php on line 71

Warning: include(): Failed opening 'Illuminate/Support/Str.php' for inclusion (include_path='.:/usr/share/php') in /opt/librenms/validate.php on line 71

Fatal error: Uncaught Error: Class "Illuminate\Support\Str" not found in /opt/librenms/LibreNMS/Config.php:129
Stack trace:
#0 /opt/librenms/LibreNMS/Util/Git.php(34): LibreNMS\Config::get()
#1 /opt/librenms/LibreNMS/Util/Version.php(40): LibreNMS\Util\Git::repoPresent()
#2 /opt/librenms/LibreNMS/Util/Version.php(45): LibreNMS\Util\Version->__construct()
#3 /opt/librenms/includes/common.php(987): LibreNMS\Util\Version::get()
#4 /opt/librenms/validate.php(73): version_info()
#5 [internal function]: {closure}()
#6 {main}
  thrown in /opt/librenms/LibreNMS/Config.php on line 129
```

### Anything in the logs that might be useful for us?

```txt
Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1045] Access denied for user 'librenms'@'localhost' (using password: NO) (SQL: select * from `config` where (`config_name` = rrdtool_version) limit 1) in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:703
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(663): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(367): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2350): Illuminate\Database\Connection->select('select * from `...', Array, true)
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2338): Illuminate\Database\Query\Builder->runSelect()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2872): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2339): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(615): Illuminate\Database\Query\Builder->get(Array)
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(599): Illuminate\Database\Eloquent\Builder->getModels(Array)
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(259): Illuminate\Database\Eloquent\Builder->get(Array)
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(464): Illuminate\Database\Eloquent\Builder->first()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(498): Illuminate\Database\Eloquent\Builder->firstOrNew(Array)
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->updateOrCreate(Array, Array)
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2109): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'updateOrCreate', Array)
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2121): Illuminate\Database\Eloquent\Model->__call('updateOrCreate', Array)
#14 /opt/librenms/LibreNMS/Config.php(255): Illuminate\Database\Eloquent\Model::__callStatic('updateOrCreate', Array)
#15 /opt/librenms/LibreNMS/Config.php(462): LibreNMS\Config::persist('rrdtool_version', '1.7.0')
#16 /opt/librenms/LibreNMS/Config.php(60): LibreNMS\Config::processConfig()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(955): LibreNMS\Config::load(Object(App\Application))
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(900): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(App\Application))
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith(Array)
#22 /opt/librenms/LibreNMS/Util/Laravel.php(44): Illuminate\Foundation\Console\Kernel->bootstrap()
#23 /opt/librenms/includes/init.php(92): LibreNMS\Util\Laravel::bootCli()
#24 /opt/librenms/config_to_json.php(13): require('/opt/librenms/i...')
```

**Comment by murrant** [comment]
/install.php is not the correct url, it is just /install, please check the install docs
