### ISSUE TITLE
Commit #13505 causing error

### ISSUE THREAD

**Issue by ReVoLt112** [librenms/librenms#13512]
### The problem

```
[2021-11-13 05:26:02] production.ERROR: Return value of GeneaLabs\LaravelCaffeine\Dripper::getAgeThresholdAttribute() must be of the type int, float returned {"exception":"[object] (TypeError(code: 0): Return value of GeneaLabs\\LaravelCaffeine\\Dripper::getAgeThresholdAttribute() must be of the type int, float returned at /opt/librenms/vendor/genealabs/laravel-caffeine/src/Dripper.php:28)
[stacktrace]
#0 /opt/librenms/vendor/jenssegers/model/src/Model.php(619): GeneaLabs\\LaravelCaffeine\\Dripper->getAgeThresholdAttribute(NULL)
#1 /opt/librenms/vendor/jenssegers/model/src/Model.php(573): Jenssegers\\Model\\Model->mutateAttribute('ageThreshold', NULL)
#2 /opt/librenms/vendor/jenssegers/model/src/Model.php(556): Jenssegers\\Model\\Model->getAttributeValue('ageThreshold')
#3 /opt/librenms/vendor/jenssegers/model/src/Model.php(845): Jenssegers\\Model\\Model->getAttribute('ageThreshold')
#4 /opt/librenms/vendor/genealabs/laravel-caffeine/src/Dripper.php(12): Jenssegers\\Model\\Model->__get('ageThreshold')
#5 /opt/librenms/vendor/jenssegers/model/src/Model.php(619): GeneaLabs\\LaravelCaffeine\\Dripper->getHtmlAttribute(NULL)
#6 /opt/librenms/vendor/jenssegers/model/src/Model.php(573): Jenssegers\\Model\\Model->mutateAttribute('html', NULL)
#7 /opt/librenms/vendor/jenssegers/model/src/Model.php(556): Jenssegers\\Model\\Model->getAttributeValue('html')
#8 /opt/librenms/vendor/jenssegers/model/src/Model.php(845): Jenssegers\\Model\\Model->getAttribute('html')
#9 /opt/librenms/vendor/genealabs/laravel-caffeine/src/Http/Middleware/LaravelCaffeineDripMiddleware.php(45): Jenssegers\\Model\\Model->__get('html')
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): GeneaLabs\\LaravelCaffeine\\Http\\Middleware\\LaravelCaffeineDripMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /opt/librenms/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#27 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#28 /opt/librenms/html/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#29 {main}
"}
```

### Output of ./validate.php

```txt
librenms@server01:~$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-3-g4b572b9b3
DB Schema | 2021_11_12_123037_change_cpwVcID_to_unsignedInteger (225)
PHP       | 7.3.31-1~deb10u1
Python    | 3.7.3
MySQL     | 10.3.31-MariaDB-0+deb10u1
RRDTool   | 1.7.1
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 2.1.12
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### Anything in the logs that might be useful for us?

```txt
https://github.com/librenms/librenms/commit/8ccf72ffdddd36e7e965fd8e1dae7c012a65995e#diff-cf1101373df4d8d213c79cbf71cac990a57e6a061842d0f73ec9ed47a8918774

This change was the reason for the error, changed session lifetime back to 120 solved this issue for me
```

**Comment by hb9eue** [comment]
Same error on my installation, noticed today after probably updates fetched during the night.

**Comment by murrant** [comment]
This is an error with 32 bit PHP installs (Mostly RPi).  Apparently, if you overflow an integer, it returns a float.  https://www.php.net/manual/en/language.types.integer.php#language.types.integer.overflow

You can fix it immediately by setting SESSION_LIFETIME=35793  or, you just update with ./daily.sh (or wait a day) as the value has been reduced so it doesn't overflow on 32bit installs.
