### ISSUE TITLE
Most of the graphs are lost

### ISSUE THREAD

**Issue by sma-inberlin** [librenms/librenms#13546]
### The problem

We are on master and daily updates are enabled. For one day a bad version reset a lot of graphs and for some one day is missing. It looks like part of devices were rediscoverd with new IDs

![grafik](https://user-images.githubusercontent.com/8058078/142701370-1ea30ad8-53cf-4595-9b78-8580814ea803.png)
![grafik](https://user-images.githubusercontent.com/8058078/142701300-9122f1b6-beb8-41e0-ac28-86ffd3fcd7e0.png)

We have a lot of old port rrd:
```
-rw-rw-r-- 1 librenms librenms 2543768 Nov 18 01:06 port-id529.rrd
-rw-rw-r-- 1 librenms librenms 2543768 Nov 18 01:06 port-id528.rrd
-rw-rw-r-- 1 librenms librenms 2543768 Nov 18 01:06 port-id525.rrd
-rw-rw-r-- 1 librenms librenms 2543768 Nov 18 01:06 port-id524.rrd
-rw-rw-r-- 1 librenms librenms 2543768 Nov 18 01:06 port-id523.rrd
```
and new ones were created:
```
-rw-rw-r-- 1 librenms librenms 2543768 Nov 19 23:47 port-id4248.rrd
-rw-rw-r-- 1 librenms librenms 2543768 Nov 19 23:47 port-id4249.rrd
-rw-rw-r-- 1 librenms librenms 2543768 Nov 19 23:47 port-id4250.rrd
-rw-rw-r-- 1 librenms librenms 2543768 Nov 19 23:47 port-id4251.rrd
-rw-rw-r-- 1 librenms librenms 2543768 Nov 19 23:47 port-id4252.rrd
-rw-rw-r-- 1 librenms librenms 2543768 Nov 19 23:47 port-id4255.rrd
```

Any idea what we can do?

### Output of ./validate.php

```txt
librenms@librenms-1:~$ /opt/librenms/validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-23-g716725758
DB Schema | 2021_11_17_105321_device_add_display_field (226)
PHP       | 7.3.32-1+0~20211118.90+debian10~1.gbp564dd3
Python    | 3.7.3
MySQL     | 10.3.31-MariaDB-0+deb10u1
RRDTool   | 1.7.1
SNMP      | 5.7.3
====================================

[OK]    Composer Version: 2.1.12
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### What was the last working version of LibreNMS?

21.11.0-23-g716725758 - Fri Nov 19 2021 19:21:56 GMT+0100

### Anything in the logs that might be useful for us?

```txt
[2021-11-17 00:15:09] production.ERROR: Call to undefined method App\Models\DeviceGroup::updateGroupsFor() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method App\\Models\\DeviceGroup::updateGroupsFor() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71)
[stacktrace]
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('updateGroupsFor')
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2109): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'updateGroupsFor', Array)
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2121): Illuminate\\Database\\Eloquent\\Model->__call('updateGroupsFor', Array)
#3 /opt/librenms/poller.php(142): Illuminate\\Database\\Eloquent\\Model::__callStatic('updateGroupsFor', Array)
#4 {main}
"}
[2021-11-17 00:15:09] production.ERROR: Call to undefined method App\Models\DeviceGroup::updateGroupsFor() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method App\\Models\\DeviceGroup::updateGroupsFor() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71)
[stacktrace]
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('updateGroupsFor')
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2109): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'updateGroupsFor', Array)
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2121): Illuminate\\Database\\Eloquent\\Model->__call('updateGroupsFor', Array)
#3 /opt/librenms/poller.php(142): Illuminate\\Database\\Eloquent\\Model::__callStatic('updateGroupsFor', Array)
#4 {main}
"}
[2021-11-17 00:15:21] production.ERROR: Call to undefined method App\Models\DeviceGroup::updateGroupsFor() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method App\\Models\\DeviceGroup::updateGroupsFor() at /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71)
[stacktrace]
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('updateGroupsFor')
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2109): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'updateGroupsFor', Array)
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2121): Illuminate\\Database\\Eloquent\\Model->__call('updateGroupsFor', Array)
#3 /opt/librenms/poller.php(142): Illuminate\\Database\\Eloquent\\Model::__callStatic('updateGroupsFor', Array)
#4 {main}
"}




/opt/librenms/discovery.php new 2021-11-18 00:15:01 - 0 devices discovered in 0.004 secs
[2021-11-18 00:15:03] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:04] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:04] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:04] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:04] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:04] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:04] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:04] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:04] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:04] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:05] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:05] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
/opt/librenms/poller.php 31 2021-11-18 00:15:06 - 1 devices polled in 2.058 secs
[2021-11-18 00:15:07] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
/opt/librenms/poller.php 4 2021-11-18 00:15:07 - 1 devices polled in 3.237 secs
/opt/librenms/poller.php 6 2021-11-18 00:15:08 - 1 devices polled in 3.197 secs
[2021-11-18 00:15:09] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:09] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-18 00:15:13] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
/opt/librenms/poller.php 47 2021-11-18 00:15:16 - 1 devices polled in 12.27 secs
```

**Comment by murrant** [comment]
Something is broken in your install.  What is the out `git status`?

**Comment by murrant** [comment]
For example when i search for `DeviceGroup::updateGroupsFor` in the current code (which your validate says you are on) there are 0 references to it. Likewise App/Action exists.

**Comment by sma-inberlin** [comment]
```
librenms@librenms-1:~$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
I guess something was broken in master between two days last week ;-)

**Comment by murrant** [comment]
@sma-inberlin but it isn't broken for anyone else...

**Comment by murrant** [comment]
@sma-inberlin try running `./scripts/composer_wrapper.php --no-dev`  Maybe you have a bad cache.

**Comment by sma-inberlin** [comment]
```
librenms@librenms-1:~$ ./scripts/composer_wrapper.php --no-dev

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--no-dev" option does not exist.                   
                                                          

list [--xml] [--raw] [--format FORMAT] [--] [<namespace>]
```

**Comment by murrant** [comment]
Sorry, forgot `./scripts/composer_wrapper.php install --no-dev`

**Comment by sma-inberlin** [comment]
Hi @murrant 

thanks for helping me. The command work but nothing really changed.

```
librenms@librenms-1:~$ ./scripts/composer_wrapper.php  install --no-dev
> LibreNMS\ComposerHelper::preInstall
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: fruitcake/laravel-cors
Discovered Package: genealabs/laravel-caffeine
Discovered Package: laravel-notification-channels/webpush
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: librenms/laravel-vue-i18n-generator
Discovered Package: mews/purifier
Discovered Package: nesbot/carbon
Discovered Package: php-flasher/flasher-laravel
Discovered Package: tightenco/ziggy
Discovered Package: wpb/string-blade-compiler
Package manifest generated successfully.
67 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> LibreNMS\ComposerHelper::postInstall
> Illuminate\Foundation\ComposerScripts::postInstall
> @php artisan vue-i18n:generate --multi-locales --format=umd
> @php artisan view:cache
Compiled views cleared!
Blade templates cached successfully!
> @php artisan optimize
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Files cached successfully!
> @php artisan config:clear
Configuration cache cleared!
> scripts/dynamic_check_requirements.py || pip3 install --user -r requirements.txt || :
```
Just thinking what can trigger a discovery of ports with new IDs?

If I check all those files in `~/rrd` which where not written since Nov 18 I only have `port-id*` files. For those ports I have new files with only Data from Nov 18. This did not happen for e.g. `availability-*, netstats-*, poller-perf-*, sensor-dbm-*` files.

Not all switches are effected. Just some in some locations.

**Comment by murrant** [comment]
Try `git reset --hard origin/master`  (not to other visitors this will remove any local changes)

**Comment by sma-inberlin** [comment]
```
librenms@librenms-1:~$ git reset --hard origin/master
HEAD is now at 439945074 Skip invalid OSPF data (#13547)

```
Did you expect another output?

**Comment by sma-inberlin** [comment]
Here we an an example of the night when a lot of switches were rediscovered:
![grafik](https://user-images.githubusercontent.com/8058078/142808915-4fc72f7e-ed1b-4ec6-a703-2a77cb2abc09.png)
and some entries before:
![grafik](https://user-images.githubusercontent.com/8058078/142809093-4d2c4aca-d3fc-4b8f-aa61-05611a73d3d4.png)

**Comment by murrant** [comment]
That is the expected output... Are you still getting the errors in the log?

**Comment by sma-inberlin** [comment]
No I don't get those errors in the logs anymore. Those errors only appeared eraly on Nov 17 and once on Nov 18 . The timestamps where we lost some of the graphs and rediscovery of some devices happend.

**Comment by murrant** [comment]
@sma-inberlin thanks for helping trying to figure it out.  Do you have a single poller or distributed polling.

I'm still baffled how you have both code calling old methods removed in the merge and code calling new code that was added.  This means you had a mix of new and old code running.

**Comment by sma-inberlin** [comment]
It's a single poller. Let's close the issue. No time to deal with. Maybe the mix of code happened with the Daily updates.
