### ISSUE TITLE
Dell S5248FB-ON (OS10) Error polling ospf module - ospfAreaTable index

### ISSUE THREAD

**Issue by fmkaiser** [librenms/librenms#13592]
### The problem

Since the change in #13542, we see `Error polling ospf module` in the event log when polling our Dell S4248FB-ON switches running OS10 10.5.1.3. Very likely the problem has existed longer and is just now logged.

Running the poller in debug mode gets us:
```
# ./poller.php -h <dell-s4248-switch> -m ospf -v -d
...
#### Load poller module ospf ####
...
1 Areas: SNMP['/usr/bin/snmpwalk' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/dell' '-v2c' '-c' 'xxx' '-OQXUt' '-Os' 'udp:<dell-s4248-switch>:161' 'OSPF-MIB::ospfAreaTable']
ospfAreaId[4.0.0.0].0 = 0.0.0.0
ospfImportAsExtern[4.0.0.0].0 = importExternal
ospfSpfRuns[4.0.0.0].0 = 2850100
ospfAreaBdrRtrCount[4.0.0.0].0 = 3
ospfAsBdrRtrCount[4.0.0.0].0 = 13
ospfAreaLsaCount[4.0.0.0].0 = 84
ospfAreaLsaCksumSum[4.0.0.0].0 = 2926928
ospfAreaSummary[4.0.0.0].0 = sendAreaSummary
ospfAreaStatus[4.0.0.0].0 = active
ospfAreaNssaTranslatorRole[4.0.0.0].0 = candidate
ospfAreaNssaTranslatorState[4.0.0.0].0 = disabled
ospfAreaNssaTranslatorStabilityInterval[4.0.0.0].0 = 40
ospfAreaNssaTranslatorEvents[4.0.0.0].0 = 0


SQL[select * from `ospf_areas` where (`device_id` = ? and `ospfAreaId` = ? and `context_name` = ?) limit 1 [3,"4.0.0.0].0",""] 0.45ms]
Error polling ospf module for rzgdr1.rzg.mpg.de. SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-0.0.0.0-' for key 'ospf_areas_device_id_ospfareaid_context_name_unique' (SQL: insert into `ospf_areas` (`device_id`, `ospfAreaId`, `context_name`, `ospfImportAsExtern`, `ospfSpfRuns`, `ospfAreaBdrRtrCount`, `ospfAsBdrRtrCount`, `ospfAreaLsaCount`, `ospfAreaLsaCksumSum`, `ospfAreaSummary`, `ospfAreaStatus`) values (3, 0.0.0.0, , importExternal, 2850100, 3, 13, 84, 2926928, sendAreaSummary, active))
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(663): Illuminate\Database\Connection->runQueryCallback('insert into `os...', Array, Object(Closure))
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(493): Illuminate\Database\Connection->run('insert into `os...', Array, Object(Closure))
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(445): Illuminate\Database\Connection->statement('insert into `os...', Array)
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `os...', Array)
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2965): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `os...', Array, 'id')
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1641): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1180): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1145): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(986): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(499): Illuminate\Database\Eloquent\Model->save()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(App\Models\OspfArea))
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(500): tap(Object(App\Models\OspfArea), Object(Closure))
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->updateOrCreate(Array, Array)
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2109): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'updateOrCreate', Array)
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2121): Illuminate\Database\Eloquent\Model->__call('updateOrCreate', Array)
#15 /opt/librenms/LibreNMS/Modules/Ospf.php(99): Illuminate\Database\Eloquent\Model::__callStatic('updateOrCreate', Array)
#16 [internal function]: LibreNMS\Modules\Ospf->LibreNMS\Modules\{closure}(Array, '4.0.0.0].0')
#17 /opt/librenms/LibreNMS/Data/Source/SnmpResponse.php(203): call_user_func(Object(Closure), Array, '4.0.0.0].0')
#18 [internal function]: LibreNMS\Data\Source\SnmpResponse->LibreNMS\Data\Source\{closure}(Array, '4.0.0.0].0')
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(663): array_map(Object(Closure), Array, Array)
#20 /opt/librenms/LibreNMS/Data/Source/SnmpResponse.php(204): Illuminate\Support\Collection->map(Object(Closure))
#21 /opt/librenms/LibreNMS/Modules/Ospf.php(103): LibreNMS\Data\Source\SnmpResponse->mapTable(Object(Closure))
#22 /opt/librenms/includes/polling/ospf.inc.php(8): LibreNMS\Modules\Ospf->poll(Object(LibreNMS\OS\Generic))
#23 /opt/librenms/includes/polling/functions.inc.php(329): include('/opt/librenms/i...')
#24 /opt/librenms/poller.php(138): poll_device(Array, true)
#25 {main}
SQL[insert into `eventlog` (`device_id`, `reference`, `type`, `datetime`, `severity`, `message`, `username`) values (?, ?, ?, ?, ?, ?, ?) [3,null,"poller","2021-12-01 12:43:05",5,"Error polling ospf module. Check log file for more details.",""] 0.6ms]
```

The table index supplied by the Dell OS10 switch seems strange with the additional "4" before the Area ID "0.0.0.0" likely causing the issue:

```
# /usr/bin/snmpwalk '-M' '/opt/librenms/mibs:/opt/librenms/mibs/dell' '-v2c' '-c' 'xxx'  'udp:<dell-s4248-switch>:161' 'OSPF-MIB::ospfAreaTable'
OSPF-MIB::ospfAreaId.4.0.0.0.0 = IpAddress: 0.0.0.0
...
```

What is unclear to us is whether this is just a bug in the Dell SNMP agent, or if the "4" might be some kind of valid sub-index.

For comparison, on our Dell/FTOS 9 and Cisco switches, output looks and works as one would expect

```
# /usr/bin/snmpwalk '-M' '/opt/librenms/mibs:/opt/librenms/mibs/dell' '-v2c' '-c' 'xxx'  'udp:<FTOS-9-Switch>:161' 'OSPF-MIB::ospfAreaTable'
OSPF-MIB::ospfAreaId.0.0.0.0 = IpAddress: 0.0.0.0
...
```

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-57-g5ce7a5a
DB Schema | 2021_11_17_105321_device_add_display_field (226)
PHP       | 7.3.33
Python    | 3.6.8
MySQL     | 10.5.13-MariaDB
RRDTool   | 1.7.1
SNMP      | 5.7.2
====================================

[OK]    Composer Version: 2.1.12
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### Device info

Dell S4248FB-ON (OS10 10.5.1.3)

Edit: Also reproducible on Dell S5248F-ON running OS10 10.5.2.8 with minimal OSPF config e.g. no VRF etc.:

```
router ospf 1
 router-id x.x.x.x

interface vlan42
 ip ospf 1 area 0.0.0.0
```

### Discovery output

```txt
available on request
```

### Poller output

```txt
available on request
```

**Comment by murrant** [comment]
Does dell have vendor specific MIBs for OSPF?  Because I'm guessing 4 means ipv4, which implies it supports IPv6.  The standard OSPF-MIB does not.

**Comment by fmkaiser** [comment]
@murrant 4 for ipv4 is a good point.  
According to the [Dell docs](https://www.dell.com/support/manuals/de-de/dell-emc-smartfabric-os10/smartfabric-os-user-guide-10-5-2/mibs?guid=guid-1521dfef-87fd-44d5-85f9-0b8813373278&lang=en-us), there are no vendor specific OSPF MIBs however.  

Also to my knowledge OSPF(v2) is IPv4 only, while OSPFv3 for IPv6 has it's own OSPFv3 MIB.  
So I don't really see why Dell would want to include the IP version in the OSPF(v2) MIB tables.  

Unless you have any other ideas, I'll try to get some clarification from Dell.

**Comment by murrant** [comment]
Yeah, you are correct on the OSPF mibs.

There is no certification process for SNMP and I think the optional validation suite is very weak.  Easy for vendors to make mistakes.

**Comment by fmkaiser** [comment]
After some back and forth, Dell has identified the problem on their end and provided us with a fix. 

Unfortunately I am not allowed to share details about the case, but this link might be of interest if one were to encounter a similar problem: https://net-snmp.sourceforge.io/wiki/index.php/FAQ:Applications_17
