### ISSUE TITLE
Duplicate entry for key ports_device_id_ifindex_unique

### ISSUE THREAD

**Issue by streamthing** [librenms/librenms#13738]
### The problem

Hello,
LibreNMS doesn't change port speed, and logs shows:
```
2022-02-01 04:05:15 Po1 ifSpeed: 20 Gbps -> 30 Gbps
2022-02-01 04:00:15 Po1 ifSpeed: 20 Gbps -> 30 Gbps
2022-02-01 03:55:15 Po1 ifSpeed: 20 Gbps -> 30 Gbps
2022-02-01 03:50:15 Po1 ifSpeed: 20 Gbps -> 30 Gbps
2022-02-01 03:45:14 Po1 ifSpeed: 20 Gbps -> 30 Gbps
2022-02-01 03:40:13 Po1 ifSpeed: 20 Gbps -> 30 Gbps
2022-02-01 03:35:15 Po1 ifSpeed: 20 Gbps -> 30 Gbps
2022-02-01 03:30:15 Po1 ifSpeed: 20 Gbps -> 30 Gbps
2022-02-01 03:25:15 Po1 ifSpeed: 20 Gbps -> 30 Gbps
2022-02-01 03:20:14 Po1 ifSpeed: 20 Gbps -> 30 Gbps
2022-02-01 03:15:14 Po1 ifSpeed: 20 Gbps -> 30 Gbps
```

this is propably same error like this, but not resolved https://community.librenms.org/t/production-error-sqlstate-23000-integrity-constraint-violation-1062-duplicate-entry/6863/12

Poller:
```
Port Po1: Port-channel1 (17 / #5535165) 
ifHCInOctets  

ifHCOutOctets  

ifHCInUcastPkts  

ifHCOutUcastPkts  

ifHCInBroadcastPkts  

ifOutBroadcastPkts  

ifInMulticastPkts  

ifOutMulticastPkts  

ifHighSpeed (30000)  

VLAN =  
SQL[insert into `eventlog` (`device_id`, `reference`, `type`, `datetime`, `severity`, `message`, `username`) values (?, ?, ?, ?, ?, ?, ?) [67,5535165,"interface","2022-02-01 04:08:05",3,"ifSpeed: 20 Gbps -> 30 Gbps",""] 1.54ms] 
  

ifSpeed: 20 Gbps -> 30 Gbps  

CiscoPO

 ifInOctets (1054742686345 B) 101652147.87442 Bps 10376 secs  


 ifOutOctets (1178653324145 B) 113594190.83896 Bps 10376 secs  


 ifInErrors (114 B) 0.010986892829607 Bps 10376 secs  


 ifOutErrors (0 B) 0 Bps 10376 secs  


 ifInUcastPkts (1068667459 B) 102994.16528527 Bps 10376 secs  


 ifOutUcastPkts (1050431163 B) 101236.61941018 Bps 10376 secs  


 ifInNUcastPkts (0 B) 0 Bps 10376 secs  


 ifOutNUcastPkts (0 B) 0 Bps 10376 secs  


 ifInDiscards (0 B) 0 Bps 10376 secs  
negative ifOutDiscards

 ifOutDiscards (-43448 B) 0 Bps 10376 secs  


 ifInUnknownProtos (0 B) 0 Bps 10376 secs  


 ifInBroadcastPkts (472451 B) 45.533057054742 Bps 10376 secs  


 ifOutBroadcastPkts (0 B) 0 Bps 10376 secs  


 ifInMulticastPkts (0 B) 0 Bps 10376 secs  


 ifOutMulticastPkts (0 B) 0 Bps 10376 secs  

bps(813.22 Mbps/908.75 Mbps)bytes(982.31 GiB/1.07 TiB)
pkts(102.99 kpps/101.24 kpps)
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '67-17' for key 'ports_device_id_ifindex_unique' (SQL: UPDATE `ports` set `ifIndex`=17,`ifLastChange`=4619,`ifSpeed`=30000000000,`ifSpeed_prev`=20000000000,`ifInOctets`=1055126789430,`ifInOctets_prev`=384103085,`ifInOctets_rate`=101652147.87442,`ifInOctets_delta`=1054742686345,`ifOutOctets`=1179749033000,`ifOutOctets_prev`=1095708855,`ifOutOctets_rate`=113594190.83896,`ifOutOctets_delta`=1178653324145,`ifInErrors`=114,`ifInErrors_prev`=0,`ifInErrors_rate`=0.010986892829607,`ifInErrors_delta`=114,`ifOutErrors`=0,`ifOutErrors_prev`=0,`ifOutErrors_rate`=0,`ifOutErrors_delta`=0,`ifInUcastPkts`=1069956682,`ifInUcastPkts_prev`=1289223,`ifInUcastPkts_rate`=102994.16528527,`ifInUcastPkts_delta`=1068667459,`ifOutUcastPkts`=1051216128,`ifOutUcastPkts_prev`=784965,`ifOutUcastPkts_rate`=101236.61941018,`ifOutUcastPkts_delta`=1050431163,`poll_time`=1643684885,`poll_prev`=1643674509,`poll_period`=10376 WHERE `port_id` = 5535165) (SQL: UPDATE `ports` set `ifIndex`=17,`ifLastChange`=4619,`ifSpeed`=30000000000,`ifSpeed_prev`=20000000000,`ifInOctets`=1055126789430,`ifInOctets_prev`=384103085,`ifInOctets_rate`=101652147.87442,`ifInOctets_delta`=1054742686345,`ifOutOctets`=1179749033000,`ifOutOctets_prev`=1095708855,`ifOutOctets_rate`=113594190.83896,`ifOutOctets_delta`=1178653324145,`ifInErrors`=114,`ifInErrors_prev`=0,`ifInErrors_rate`=0.010986892829607,`ifInErrors_delta`=114,`ifOutErrors`=0,`ifOutErrors_prev`=0,`ifOutErrors_rate`=0,`ifOutErrors_delta`=0,`ifInUcastPkts`=1069956682,`ifInUcastPkts_prev`=1289223,`ifInUcastPkts_rate`=102994.16528527,`ifInUcastPkts_delta`=1068667459,`ifOutUcastPkts`=1051216128,`ifOutUcastPkts_prev`=784965,`ifOutUcastPkts_rate`=101236.61941018,`ifOutUcastPkts_delta`=1050431163,`poll_time`=1643684885,`poll_prev`=1643674509,`poll_period`=10376 WHERE `port_id` = 5535165)#0 /opt/librenms/includes/polling/ports.inc.php(943): dbUpdate(Array, 'ports', '`port_id` = ?', Array)
#1 /opt/librenms/includes/polling/functions.inc.php(329): include('/opt/librenms/i...')
#2 /opt/librenms/poller.php(138): poll_device(Array, false)
#3 {main}  

SQL[UPDATE `ports_statistics` set `ifInNUcastPkts`=?,`ifInNUcastPkts_prev`=?,`ifInNUcastPkts_rate`=?,`ifInNUcastPkts_delta`=?,`ifOutNUcastPkts`=?,`ifOutNUcastPkts_prev`=?,`ifOutNUcastPkts_rate`=?,`ifOutNUcastPkts_delta`=?,`ifInDiscards`=?,`ifInDiscards_prev`=?,`ifInDiscards_rate`=?,`ifInDiscards_delta`=?,`ifOutDiscards`=?,`ifOutDiscards_prev`=?,`ifOutDiscards_rate`=?,`ifOutDiscards_delta`=?,`ifInUnknownProtos`=?,`ifInUnknownProtos_prev`=?,`ifInUnknownProtos_rate`=?,`ifInUnknownProtos_delta`=?,`ifInBroadcastPkts`=?,`ifInBroadcastPkts_prev`=?,`ifInBroadcastPkts_rate`=?,`ifInBroadcastPkts_delta`=?,`ifOutBroadcastPkts`=?,`ifOutBroadcastPkts_prev`=?,`ifOutBroadcastPkts_rate`=?,`ifOutBroadcastPkts_delta`=?,`ifInMulticastPkts`=?,`ifInMulticastPkts_prev`=?,`ifInMulticastPkts_rate`=?,`ifInMulticastPkts_delta`=?,`ifOutMulticastPkts`=?,`ifOutMulticastPkts_prev`=?,`ifOutMulticastPkts_rate`=?,`ifOutMulticastPkts_delta`=? WHERE `port_id` = ? [0,0,0,0,0,0,0,0,"0",0,0,0,"109",43557,"0",-43448,0,0,0,0,"472451",0,45.53305705474171,472451,"0",0,0,0,"0",0,0,0,"0",0,0,0,5535165] 0.85ms] 
  

1 updated  
```

### Output of ./validate.php

```txt
librenms@librenms:~$ /opt/librenms/validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 22.1.0-34-ga3bd1b9a6
DB Schema | 2021_12_02_113537_ports_stp_designated_cost_change_to_int (234)
PHP       | 7.3.19-1~deb10u1
Python    | 3.7.3
MySQL     | 10.3.27-MariaDB-0+deb10u1
RRDTool   | 1.7.1
SNMP      | 5.7.3
====================================

[OK]    Composer Version: 2.2.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by ottorei** [comment]
Have you changed the port association mode after the device had been discovered once?

**Comment by streamthing** [comment]
> Have you changed the port association mode after the device had been discovered once?

No, i'm not changed. I got ifName as default.

**Comment by streamthing** [comment]
Other router, other port, ifName, nothing changed on LibreNMS:
```
2022-02-10 03:00:14 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 03:00:14 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:55:12 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:55:12 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:50:12 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:50:12 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:45:12 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:45:12 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:40:12 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:40:12 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:35:12 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:35:12 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:30:12 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:30:12 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:25:11 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:25:11 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:20:11 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:20:11 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:15:14 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:15:14 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:10:15 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:10:14 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:05:14 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:05:14 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 02:00:17 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 02:00:17 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 01:55:16 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 01:55:16 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 01:50:16 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 01:50:16 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 01:45:17 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 01:45:17 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 01:40:15 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 01:40:15 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 01:35:16 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 01:35:16 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 01:30:18 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 01:30:18 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 01:25:16 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 01:25:16 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 01:20:16 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
2022-02-10 01:20:15 Po1.1462    ifOperStatus: lowerLayerDown -> up
2022-02-10 01:15:17 Po1.1462    ifSpeed: 1 Gbps -> 30 Gbps
```

**Comment by streamthing** [comment]
Lol, today after daily i can see it's working from 00:20.
Something was changed?

**Comment by murrant** [comment]
@streamthing no
