### ISSUE TITLE
LibreNMS not working anymore after PHP upgrade from 7.4 to 8.1

### ISSUE THREAD

**Issue by Jarod2801** [librenms/librenms#14251]
### The problem

After performing the PHP Upgrade from 7.4 to 8.1, lnms stopped working.

The services mariadb, httpd and php-fpm looking fine.

./daily.sh and ./validate.php run without errors.

### Output of ./validate.php

```txt
bash-4.2$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 22.8.0-18-g87a14ba
DB Schema | 2022_07_03_1947_add_app_data (244)
PHP       | 8.1.9
Python    | 3.6.8
Database  | MariaDB 10.5.17-MariaDB
RRDTool   | 1.4.8
SNMP      | 5.7.2
====================================

[OK]    Composer Version: 2.4.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
bash-4.2$
```

### Anything in the logs that might be useful for us?

```txt
/opt/librenms/logs/librenms.log

[2022-08-26T14:52:43.014201+02:00] production.ERROR: Error discovering entity-physical module for 4467-yyy-3916-1. TypeError: array_replace_recursive(): Argument #1 ($array) must be of type array, null given in /opt/librenms/includes/discovery/entity-physical/ciena-sds.inc.php:44
Stack trace:
#0 /opt/librenms/includes/discovery/entity-physical/ciena-sds.inc.php(44): array_replace_recursive(NULL, NULL, NULL)
#1 /opt/librenms/includes/discovery/entity-physical.inc.php(10): include('/opt/librenms/i...')
#2 /opt/librenms/includes/discovery/functions.inc.php(153): include('/opt/librenms/i...')
#3 /opt/librenms/discovery.php(118): discover_device(Array, false)
#4 {main}
[2022-08-26T14:52:43.019917+02:00] production.ERROR: array_replace_recursive(): Argument #1 ($array) must be of type array, null given {"exception":"[object] (TypeError(code: 0): array_replace_recursive(): Argument #1 ($array) must be of type array, null given at /opt/librenms/includes/discovery/entity-physical/ciena-sds.inc.php:44)"}
/opt/librenms/poller.php 171 2022-08-26 14:52:43 - 1 devices polled in 3.797 secs
/opt/librenms/poller.php 318 2022-08-26 14:52:43 - 1 devices polled in 3.862 secs
[2022-08-26T14:52:43.152116+02:00] production.ERROR: Error discovering entity-physical module for 4054-yyy-5142-1. TypeError: array_replace_recursive(): Argument #1 ($array) must be of type array, null given in /opt/librenms/includes/discovery/entity-physical/ciena-sds.inc.php:44
Stack trace:
#0 /opt/librenms/includes/discovery/entity-physical/ciena-sds.inc.php(44): array_replace_recursive(NULL, NULL, NULL)
#1 /opt/librenms/includes/discovery/entity-physical.inc.php(10): include('/opt/librenms/i...')
#2 /opt/librenms/includes/discovery/functions.inc.php(153): include('/opt/librenms/i...')
#3 /opt/librenms/discovery.php(118): discover_device(Array, false)
#4 {main}
[2022-08-26T14:52:43.156623+02:00] production.ERROR: array_replace_recursive(): Argument #1 ($array) must be of type array, null given {"exception":"[object] (TypeError(code: 0): array_replace_recursive(): Argument #1 ($array) must be of type array, null given at /opt/librenms/includes/discovery/entity-physical/ciena-sds.inc.php:44)"}
/opt/librenms/discovery.php 370 2022-08-26 14:52:43 - 1 devices discovered in 31.31 secs
/opt/librenms/poller.php 279 2022-08-26 14:52:43 - 1 devices polled in 3.867 secs
/opt/librenms/discovery.php 341 2022-08-26 14:52:44 - 1 devices discovered in 31.67 secs
/opt/librenms/poller.php 29 2022-08-26 14:52:44 - 1 devices polled in 3.893 secs
/opt/librenms/poller.php 748 2022-08-26 14:52:44 - 1 devices polled in 4.003 secs
/opt/librenms/poller.php 18 2022-08-26 14:52:44 - 1 devices polled in 3.855 secs
/opt/librenms/poller.php 6 2022-08-26 14:52:44 - 1 devices polled in 3.819 secs
/opt/librenms/poller.php 126 2022-08-26 14:52:44 - 1 devices polled in 3.808 secs
[2022-08-26T14:52:44.946557+02:00] production.ERROR: Error discovering entity-physical module for 4495-yyy-3916-1. TypeError: array_replace_recursive(): Argument #1 ($array) must be of type array, null given in /opt/librenms/includes/discovery/entity-physical/ciena-sds.inc.php:44
Stack trace:
#0 /opt/librenms/includes/discovery/entity-physical/ciena-sds.inc.php(44): array_replace_recursive(NULL, NULL, NULL)
#1 /opt/librenms/includes/discovery/entity-physical.inc.php(10): include('/opt/librenms/i...')
#2 /opt/librenms/includes/discovery/functions.inc.php(153): include('/opt/librenms/i...')
#3 /opt/librenms/discovery.php(118): discover_device(Array, false)
#4 {main}
[2022-08-26T14:52:44.950445+02:00] production.ERROR: array_replace_recursive(): Argument #1 ($array) must be of type array, null given {"exception":"[object] (TypeError(code: 0): array_replace_recursive(): Argument #1 ($array) must be of type array, null given at /opt/librenms/includes/discovery/entity-physical/ciena-sds.inc.php:44)"}
/opt/librenms/poller.php 30 2022-08-26 14:52:45 - 1 devices polled in 3.803 secs
/opt/librenms/poller.php 277 2022-08-26 14:52:45 - 1 devices polled in 3.863 secs
```

**Comment by murrant** [comment]
Fixed by #14252 

Also, when you say lnms, it means the command "lnms"
