### ISSUE TITLE
Error discovering bgp-peers module

### ISSUE THREAD

**Issue by ciroiriarte** [librenms/librenms#14316]
### The problem

After updating to PHP 8.1, I see errors that I haven't seen before.

### Output of ./validate.php

```txt
===================================
Component | Version
--------- | -------
LibreNMS  | 22.8.0
DB Schema | 2022_07_03_1947_add_app_data (244)
PHP       | 8.1.10
Python    | 3.6.15
Database  | MariaDB 10.6.8-MariaDB
RRDTool   | 1.7.0
SNMP      | 5.7.3
====================================

[OK]    Composer Version: 2.4.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[WARN]  Using database for locking, you should set CACHE_DRIVER=redis
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Anything in the logs that might be useful for us?

```txt
[2022-09-07T00:34:59.075519-05:00] production.ERROR: Error discovering bgp-peers module for myrouter.lab. TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /opt/librenms/includes/discovery/bgp-peers.inc.php:120
Stack trace:
#0 /opt/librenms/includes/discovery/bgp-peers.inc.php(120): array_keys()
#1 /opt/librenms/includes/discovery/functions.inc.php(153): include('...')
#2 /opt/librenms/discovery.php(118): discover_device()
#3 {main}  
/opt/librenms/discovery.php 20 2022-09-07 00:34:59 - 1 devices discovered in 5.544 secs
```

**Comment by murrant** [comment]
I'm not sure this error exists anymore.  Is it possible for you to switch to daily (at least temporarily) and see if it is resolved.

**Comment by PipoCanaja** [comment]
Hi @ciroiriarte 
Could you please let us know if this issue is still around by re-opening this issue ?
Thanx
