### ISSUE TITLE
Sensors initialisation fails with PHP 8.1 

### ISSUE THREAD

**Issue by poshleon** [librenms/librenms#14390]
### The problem

I created test librenms server to fix low-temp alerts.

Latest as of today 2022-09-26 librenms. With remi php 8.1 on Oracle Linux 8 (RHEL like) I get an error discovering sensors:

```
production.ERROR: Error discovering sensors module for 10.0.0.1. TypeError: current(): Argument #1 ($array) must be of type array, null 
given in /opt/librenms/includes/discovery/sensors/state/linux.inc.php:69
Stack trace:
#0 /opt/librenms/includes/discovery/sensors/state/linux.inc.php(69): current()
#1 /opt/librenms/includes/discovery/functions.inc.php(993): include('/opt/librenms/i...')
#2 /opt/librenms/includes/discovery/sensors.inc.php(84): sensors()
#3 /opt/librenms/includes/discovery/functions.inc.php(153): include('/opt/librenms/i...')
#4 /opt/librenms/discovery.php(118): discover_device()
#5 {main}  
```
After downgrading to php 7.4 stream from AppStream repo the temps get discovered. I don’t think insisting on php 8.1 is a good idea while there are still problems.

Not using Weathermap or any other plugins.

### Output of ./validate.php

```txt
Validate php is OK except it's complaining about not having php 8.1
```

### What was the last working version of LibreNMS?

22.9.0-4-ge990dfcb3 - Mon Sep 26 2022 05:47:58 GMT+0200

### Anything in the logs that might be useful for us?

```txt
production.ERROR: Error discovering sensors module for 10.0.0.1. TypeError: current(): Argument #1 ($array) must be of type array, null 
given in /opt/librenms/includes/discovery/sensors/state/linux.inc.php:69
Stack trace:
#0 /opt/librenms/includes/discovery/sensors/state/linux.inc.php(69): current()
#1 /opt/librenms/includes/discovery/functions.inc.php(993): include('/opt/librenms/i...')
#2 /opt/librenms/includes/discovery/sensors.inc.php(84): sensors()
#3 /opt/librenms/includes/discovery/functions.inc.php(153): include('/opt/librenms/i...')
#4 /opt/librenms/discovery.php(118): discover_device()
#5 {main}
```

**Comment by murrant** [comment]
This was already fixed by #13722
