### ISSUE TITLE
Error polling ports module Cisco IOS-XE after upgrading to PHP 8.1 / LibreNMS 22.10.0

### ISSUE THREAD

**Issue by torbbb** [librenms/librenms#14576]
### The problem

No data for ports on Cisco IOS-XE after the last update. Eventlog: Error polling ports module. Check log file for more details.

### Output of ./validate.php

```txt
librenms@librenms:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 22.10.0-72-g0f34c144c (2022-11-04T01:39:17+01:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.12
Python    | 3.10.8
Database  | MariaDB 10.6.10-MariaDB-1+b1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================
```

### What was the last working version of LibreNMS?

22.9.0

### Anything in the logs that might be useful for us?

```txt
librenms@librenms:~$ ./discovery.php -h 10.7.1.101 -m ports 
LibreNMS Discovery
10.7.1.101 16 iosxe 
#### Load disco module core ####
OS: Cisco IOS-XE (iosxe)


>> Runtime for discovery module 'core': 0.1110 seconds with 2895352 bytes
>> SNMP: [1/0.08s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module core ####


#### Load disco module ports ####
Error discovering ports module for 10.7.1.101. TypeError: stripos(): Argument #2 ($needle) must be of type string, array given in /opt/librenms/includes/common.php:737
Stack trace:
#0 /opt/librenms/includes/common.php(737): stripos()
#1 /opt/librenms/includes/functions.php(615): str_i_contains()
#2 /opt/librenms/includes/discovery/ports.inc.php(94): is_port_valid()
#3 /opt/librenms/includes/discovery/functions.inc.php(153): include('...')
#4 /opt/librenms/discovery.php(106): discover_device()
#5 {main}  
stripos(): Argument #2 ($needle) must be of type string, array given {"exception":"[object] (TypeError(code: 0): stripos(): Argument #2 ($needle) must be of type string, array given at /opt/librenms/includes/common.php:737)"} 

>> Runtime for discovery module 'ports': 0.7990 seconds with 1358520 bytes
>> SNMP: [5/0.54s] MySQL: [7/0.11s] RRD: [0/0.00s]  
#### Unload disco module ports ####

Discovered in 2.068 seconds


SNMP [7/0.68s]: Snmpget[2/0.14s] Snmpwalk[5/0.54s]  
SQL [12/0.26s]: Select[10/0.22s] Insert[1/0.04s] Update[1/0.00s]  
RRD [0/0.00s]:   


--------------------------------------------------------------------

/logs/librenms.log 

[2022-11-04T10:11:48.364943+01:00] production.ERROR: Error polling ports module for 10.7.22.100. TypeError: stripos(): Argument #2 ($needle) must be of type string, array given in /opt/librenms/includes/common.php:737
Stack trace:
#0 /opt/librenms/includes/common.php(737): stripos()
#1 /opt/librenms/includes/functions.php(615): str_i_contains()
#2 /opt/librenms/includes/polling/ports.inc.php(469): is_port_valid()
#3 /opt/librenms/includes/polling/functions.inc.php(340): include('...')
#4 /opt/librenms/poller.php(126): poll_device()
#5 {main}  
[2022-11-04T10:11:48.373407+01:00] production.ERROR: stripos(): Argument #2 ($needle) must be of type string, array given {"exception":"[object] (TypeError(code: 0): stripos(): Argument #2 ($needle) must be of type string, array given at /opt/librenms/includes/common.php:737)"}
```

**Comment by murrant** [comment]
@torbbb one of your port filtering settings is set wrong, it should be an array of strings or just a string.  (you have an array in an array)

Check the following settings (both global and per-os).
bad_if
good_if

**Comment by murrant** [comment]
Closing due to incorrect local configuration being the problem.
