### ISSUE TITLE
raisecom-ros is broken for Raisecom RAX721 switches

### ISSUE THREAD

**Issue by friek** [librenms/librenms#14808]
### The problem

The Raisecom RAX721 switches are relatively new models running major version 6 of Raisecom ROS. It turns out that some SNMP tables like all IF-MIB tables but also Q-BRIDGE-MIB tables don't have increasing OIDs in an snmpwalk. For example:
```bash
$ snmpwalk -v2c -M $HOME/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:$HOME/mibs/raisecom:. -c public hostname IF-MIB::ifIndex 2>&1 | tail -6
IF-MIB::ifIndex.272646331 = INTEGER: 272646331
IF-MIB::ifIndex.272646335 = INTEGER: 272646335
IF-MIB::ifIndex.268435456 = INTEGER: 268435456
Error: OID not increasing: IF-MIB::ifIndex.272646335
 >= IF-MIB::ifIndex.268435456
```

In my local installation, I've fixed this by adding the unordered OIDs to `includes/definitions/raisecom-ros.yaml` which leads to snmpwalk being called with `-Cc`:
```yaml
oids:
  unordered:
    - ifXEntry
    - ifDescr
    - ifAdminStatus
    - ifOperStatus
    - ifLastChange
    - ifType
    - ifPhysAddress
    - ifMtu
    - ifInErrors
    - ifOutErrors
    - ifInDiscards
    - ifOutDiscards
```

Besides the IF-MIB tables above I've also tried adding the `Q-BRIDGE-MIB::{dot1qVlanCurrentUntaggedPorts, dot1qVlanCurrentEgressPorts, dot1qVlanStaticUntaggedPorts, dot1qVlanStaticEgressPorts}` to fix vlan detection but that didn't work out alright. Those tables also don't have increasing OIDs in an snmpwalk but vlan detection is somehow broken anyway (which I consider a separate issue). Also note that in the unordered list above, the `IF-MIB::` prefix is excluded from the entries as they aren't used as such by LibreNMS when generating the snmpwalk commands.

Although this could be considered a bug in the SNMP implementation of ROS, they have no intention of fixing it. 

I can create a PR to merge in the locally made changes in `raisecom-ros.yaml` if that's desirable.

### Output of ./validate.php

```txt
% ./validate.php
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/johan/Development/PhpstormProjects/librenms/scripts/composer_wrapper.php on line 40
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/johan/Development/PhpstormProjects/librenms/scripts/composer_wrapper.php on line 43
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/johan/Development/PhpstormProjects/librenms/scripts/composer_wrapper.php on line 40
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/johan/Development/PhpstormProjects/librenms/scripts/composer_wrapper.php on line 43
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.1.0-5-g8d49e72f2 (2023-01-25T20:19:46+01:00)
DB Schema | 2021_02_09_122930_migrate_to_utf8mb4 (248)
PHP       | 8.1.14
Python    | 3.10.9
Database  | MySQL 8.0.31
RRDTool   | 1.8.0
SNMP      | 5.6.2.1
===========================================

[OK]    Composer Version: 2.5.1
[OK]    Dependencies up-to-date.
[WARN]  Debug enabled.  This is a security risk.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]
[OK]    Database schema correct
[FAIL]  Time between this server and the mysql database is off
 Mysql time 2023-01-26 12:30:17
 PHP time 2023-01-26 13:30:17
[WARN]  Your tmp directory (/var/folders/2t/4635hll17335qlqkbk6j0zsm0000gn/T) is not set to 777 so graphs most likely won't be generated
[FAIL]  No active polling method detected
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[INFO]  Could not read cron files
[WARN]  Using database for locking, you should set CACHE_DRIVER=redis
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Global lnms shortcut not installed. lnms command must be run with full path
	[FIX]:
	sudo ln -s /Users/johan/Development/PhpstormProjects/librenms/lnms /usr/local/bin/lnms
[WARN]  Log rotation not enabled, could cause disk space issues
	[FIX]:
	sudo cp /Users/johan/Development/PhpstormProjects/librenms/misc/librenms.logrotate /etc/logrotate.d/librenms
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]:
	You can fix this with ./scripts/github-remove
	Modified Files:
	 includes/definitions/raisecom-ros.yaml
[FAIL]  You need to run this script as 'librenms' or root
```

### Device info

Raisecom RAX721

### Discovery output

```txt
LibreNMS Discovery
x.x.x.x 3 raisecom-ros 
#### Load disco module core ####
OS: Raisecom ROS (raisecom-ros)


>> Runtime for discovery module 'core': 0.5010 seconds with 2756152 bytes
>> SNMP: [9/0.47s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module core ####


#### Load disco module os ####
Location: *censored*
Hardware: MSOTN P200R001C01
OS Version: ROS_6.3.1_20221013
OS Features: 
Serial: *censored*

>> Runtime for discovery module 'os': 0.1940 seconds with 719840 bytes
>> SNMP: [4/0.13s] MySQL: [1/0.05s] RRD: [0/0.00s]  
#### Unload disco module os ####


#### Load disco module ports ####
.............................

>> Runtime for discovery module 'ports': 0.4960 seconds with 121584 bytes
>> SNMP: [5/0.42s] MySQL: [30/0.56s] RRD: [0/0.00s]  
#### Unload disco module ports ####


#### Load disco module ports-stack ####


>> Runtime for discovery module 'ports-stack': 0.0650 seconds with 5776 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.05s] RRD: [0/0.00s]  
#### Unload disco module ports-stack ####

Module [ xdsl ] disabled globally.


#### Load disco module entity-physical ####

Caching OIDs: entPhysicalEntry

>> Runtime for discovery module 'entity-physical': 0.0620 seconds with 17272 bytes
>> SNMP: [1/0.06s] MySQL: [1/0.04s] RRD: [0/0.00s]  
#### Unload disco module entity-physical ####

Module [ entity-state ] disabled globally.

Module [ isis ] disabled globally.


#### Load disco module processors ####
Pre-cache raisecom-ros: rosMgmtOpticalTransceiverDDMTable 
Caching data: mempools os processors sensors 
UUUUUUUUUUUUUUUUUUUU

>> Runtime for discovery module 'processors': 3.8000 seconds with 355336 bytes
>> SNMP: [13/3.24s] MySQL: [42/0.73s] RRD: [0/0.00s]  
#### Unload disco module processors ####


#### Load disco module mempools ####
U
raisecom-ros [system]: Memory: 26%  506.25 KiB / 1.89 MiB

>> Runtime for discovery module 'mempools': 0.2170 seconds with 374168 bytes
>> SNMP: [4/0.19s] MySQL: [8/0.15s] RRD: [0/0.00s]  
#### Unload disco module mempools ####


#### Load disco module cisco-vrf-lite ####

>> Runtime for discovery module 'cisco-vrf-lite': 0.0010 seconds with 1448 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.01s] RRD: [0/0.00s]  
#### Unload disco module cisco-vrf-lite ####

Module [ cisco-mac-accounting ] disabled globally.

Module [ cisco-pw ] disabled globally.

Module [ vrf ] disabled globally.

Module [ cisco-cef ] disabled globally.

Module [ slas ] disabled globally.

Module [ cisco-cbqos ] disabled globally.

Module [ cisco-otv ] disabled globally.

Module [ cisco-qfp ] disabled globally.


#### Load disco module ipv4-addresses ####


>> Runtime for discovery module 'ipv4-addresses': 0.0640 seconds with 37464 bytes
>> SNMP: [1/0.06s] MySQL: [2/0.05s] RRD: [0/0.00s]  
#### Unload disco module ipv4-addresses ####


#### Load disco module ipv6-addresses ####


>> Runtime for discovery module 'ipv6-addresses': 0.1420 seconds with 9904 bytes
>> SNMP: [2/0.14s] MySQL: [1/0.06s] RRD: [0/0.00s]  
#### Unload disco module ipv6-addresses ####

Module [ route ] disabled globally.


#### Load disco module sensors ####
 ENTITY-SENSOR: Caching OIDs: entPhysicalDescr
Airflow: 
Current: 
Charge: 
Dbm: Raisecom..
Fanspeed: 
Frequency: 
Humidity: 
Load: 
Loss: 
Power: 
Power_consumed: 
Power_factor: 
Runtime: 
Signal: 
State: Cur 1, Low: null, Low Warn: null, Warn: null, High: null
.Cur 6, Low: null, Low Warn: null, Warn: null, High: null
.
Count: 
Temperature: Raisecom..
Tv_signal: 
Bitrate: 
Voltage: 
Snr: 
Pressure: 
Cooling: 
Delay: 
Quality_factor: 
Chromatic_dispersion: 
Ber: 
Eer: 
Waterflow: 
Percent: 

>> Runtime for discovery module 'sensors': 0.2050 seconds with 32856 bytes
>> SNMP: [1/0.06s] MySQL: [58/1.10s] RRD: [0/0.00s]  
#### Unload disco module sensors ####


#### Load disco module storage ####
aix_filesystem : hrStorage : 

>> Runtime for discovery module 'storage': 0.2430 seconds with 58608 bytes
>> SNMP: [5/0.17s] MySQL: [4/0.16s] RRD: [0/0.00s]  
#### Unload disco module storage ####


#### Load disco module hr-device ####


>> Runtime for discovery module 'hr-device': 0.1420 seconds with 12296 bytes
>> SNMP: [2/0.13s] MySQL: [1/0.07s] RRD: [0/0.00s]  
#### Unload disco module hr-device ####


#### Load disco module discovery-protocols ####
 CISCO-CDP-MIB: 
 LLDP-MIB: 
 OSPF Discovery: 

>> Runtime for discovery module 'discovery-protocols': 0.4590 seconds with 85936 bytes
>> SNMP: [1/0.06s] MySQL: [47/0.88s] RRD: [0/0.00s]  
#### Unload disco module discovery-protocols ####


#### Load disco module arp-table ####
: 



>> Runtime for discovery module 'arp-table': 0.1670 seconds with -10048 bytes
>> SNMP: [2/0.15s] MySQL: [3/0.12s] RRD: [0/0.00s]  
#### Unload disco module arp-table ####

Module [ discovery-arp ] disabled globally.

Module [ junose-atm-vp ] disabled globally.


#### Load disco module bgp-peers ####
AS272637955 

>> Runtime for discovery module 'bgp-peers': 0.1020 seconds with 12808 bytes
>> SNMP: [2/0.09s] MySQL: [3/0.14s] RRD: [0/0.00s]  
#### Unload disco module bgp-peers ####


#### Load disco module vlans ####
IEEE8021-Q-BRIDGE-MIB VLANs: ver version1 Error discovering vlans module for 172.16.16.107. TypeError: array_merge(): Argument #1 must be of type array, string given in /Users/johan/Development/PhpstormProjects/librenms/includes/discovery/vlans/q-bridge-mib.inc.php:47
Stack trace:
#0 /Users/johan/Development/PhpstormProjects/librenms/includes/discovery/vlans/q-bridge-mib.inc.php(47): array_merge('', '10 40 40 1B')
#1 [internal function]: {closure}(Array, Array)
#2 /Users/johan/Development/PhpstormProjects/librenms/includes/discovery/vlans/q-bridge-mib.inc.php(51): array_reduce(Array, Object(Closure), Array)
#3 /Users/johan/Development/PhpstormProjects/librenms/includes/discovery/vlans.inc.php(39): require('/Users/johan/De...')
#4 /Users/johan/Development/PhpstormProjects/librenms/includes/discovery/functions.inc.php(153): include('/Users/johan/De...')
#5 /Users/johan/Development/PhpstormProjects/librenms/discovery.php(106): discover_device(Array, false)
#6 {main}  
array_merge(): Argument #1 must be of type array, string given {"exception":"[object] (TypeError(code: 0): array_merge(): Argument #1 must be of type array, string given at /Users/johan/Development/PhpstormProjects/librenms/includes/discovery/vlans/q-bridge-mib.inc.php:47)"} 

>> Runtime for discovery module 'vlans': 3.3490 seconds with 1029496 bytes
>> SNMP: [4/0.33s] MySQL: [22/0.54s] RRD: [0/0.00s]  
#### Unload disco module vlans ####

Module [ vmware-vminfo ] disabled globally.

Module [ libvirt-vminfo ] disabled globally.

Module [ printer-supplies ] disabled globally.


#### Load disco module ucd-diskio ####


>> Runtime for discovery module 'ucd-diskio': 0.0570 seconds with 6552 bytes
>> SNMP: [1/0.05s] MySQL: [1/0.06s] RRD: [0/0.00s]  
#### Unload disco module ucd-diskio ####

Module [ applications ] disabled globally.


#### Load disco module services ####

>> Runtime for discovery module 'services': 0.0000 seconds with 720 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module services ####


#### Load disco module stp ####
Instances: 
Ports: 

>> Runtime for discovery module 'stp': 0.0680 seconds with 78184 bytes
>> SNMP: [1/0.05s] MySQL: [2/0.11s] RRD: [0/0.00s]  
#### Unload disco module stp ####


#### Load disco module ntp ####

>> Runtime for discovery module 'ntp': 0.0000 seconds with 264 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module ntp ####

Module [ loadbalancers ] disabled globally.

Module [ mef ] disabled globally.


#### Load disco module wireless ####

>> Runtime for discovery module 'wireless': 0.0440 seconds with 155840 bytes
>> SNMP: [0/0.00s] MySQL: [24/0.36s] RRD: [0/0.00s]  
#### Unload disco module wireless ####


#### Load disco module fdb-table ####
Q-BRIDGE-MIB:Error discovering fdb-table module for 172.16.16.107. TypeError: Cannot access offset of type string on string in /Users/johan/Development/PhpstormProjects/librenms/includes/discovery/fdb-table/bridge.inc.php:62
Stack trace:
#0 /Users/johan/Development/PhpstormProjects/librenms/includes/discovery/fdb-table.inc.php(29): include()
#1 /Users/johan/Development/PhpstormProjects/librenms/includes/discovery/functions.inc.php(153): include('/Users/johan/De...')
#2 /Users/johan/Development/PhpstormProjects/librenms/discovery.php(106): discover_device(Array, false)
#3 {main}  
Cannot access offset of type string on string {"exception":"[object] (TypeError(code: 0): Cannot access offset of type string on string at /Users/johan/Development/PhpstormProjects/librenms/includes/discovery/fdb-table/bridge.inc.php:62)"} 

>> Runtime for discovery module 'fdb-table': 1.4580 seconds with 187848 bytes
>> SNMP: [0/0.00s] MySQL: [4/0.15s] RRD: [0/0.00s]  
#### Unload disco module fdb-table ####


#### Load disco module mpls ####

>> Runtime for discovery module 'mpls': 0.0000 seconds with 37144 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [0/0.00s]  
#### Unload disco module mpls ####

Discovered in 13.051 seconds


SNMP [59/5.90s]: Snmpget[26/1.42s] Snmpwalk[30/4.37s] Snmptranslate[2/0.07s] Snmpgetnext[1/0.04s]  
SQL [261/5.65s]: Select[185/3.91s] Update[51/0.99s] Delete[13/0.29s] Insert[12/0.45s]  
RRD [0/0.00s]:   

Process finished with exit code 0
```

### Poller output

```txt
Too large to submit in an issue. See https://www.localhost.nl/pb/view/de6f6009#Mx9lKNxq5NBqWEB3ms1CjSgaZNAlmbpJ
```

**Comment by murrant** [comment]
oids not increasing is an upstream bug.  The work-around that LibreNMS could implement involves the possibility of an infinite loop.

**Comment by friek** [comment]
It's already been fixed in https://github.com/librenms/librenms/pull/15365 so I guess it can be closed.
