### ISSUE TITLE
php 8.1 discovery-protocols and snmpv3 - array issue

### ISSUE THREAD

**Issue by letienne** [librenms/librenms#14823]
### The problem

I recently upgraded my installation to 23.1.0, which required a php upgrade from 7.4 to 8.1.

Since then, the discovery-protocols part was failing:

`
[2023-01-31T13:03:53.996958+01:00] production.ERROR: Error discovering discovery-protocols module for <<device>>. 
TypeError: Cannot access offset of type string on string in /opt/librenms/includes/functions.php:319
Stack trace:
#0 /opt/librenms/includes/functions.php(269): deviceArray()
#1 /opt/librenms/includes/discovery/functions.inc.php(79): addHost()
#2 /opt/librenms/includes/discovery/discovery-protocols.inc.php(60): discover_new_device()
#3 /opt/librenms/includes/discovery/functions.inc.php(153): include('...')
#4 /opt/librenms/discovery.php(106): discover_device()
#5 {main}
`

It appears that php 8.1 is more strict regarding the line:

when $v3 is not an array.

I'm no developer, but I changed functions.php line 318 from :
`  } elseif ($snmpver === 'v3' ) {
`
to

`  } elseif ($snmpver === 'v3' && is_array($v3)) {`

and removed 

` $v3['authname'] . '/' . $v3['authlevel']`

from line 273 and it appears to be working again (or at least it does not crash the process anymore :)

That's probably something you can fix better somewhere else 

### Output of ./validate.php

```txt
cannot disclose. relevant parts:

Version	23.1.0 - Mon Jan 30 2023 13:46:55 GMT+0100
Database Schema	2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
Web Server	Apache/2.4.52 (Ubuntu)
PHP	8.1.2-1ubuntu2.10
Python	3.10.6
Database	MariaDB 10.6.11-MariaDB-0ubuntu0.22.04.1

Webpage output :

ConfigurationOk
DatabaseOk
DependenciesOk
DiskOk
DistributedpollerOk
MailOk
PhpOk
PollerOk
ProgramsOk
PythonWarning
WARN: Could not check Python dependencies because this script is not running as librenms
```

### What was the last working version of LibreNMS?

22.x?

**Comment by murrant** [comment]
Did you set SNMPv3 credentials in config.php?  If so, you probably formatted them wrong.  I suggest you delete that and set the credentials via the webui to ensure the correct format.

**Comment by letienne** [comment]
Yes, I did. And yes it appears that you're right. I removed them from my config.php file and added them via the webui, it seems to be working now.
