### ISSUE TITLE
After updating Laravel to version 9.52.5, the whole system falls into an error with an example: Exception: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by drykov-ttc** [librenms/librenms#14988]
### The problem

After updating Laravel to version 9.52.5, the entire system falls into an error, for example: Exception: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated, errors of this type occur throughout the system. Composer has been updated all dependencies are satisfied

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.4.1-22-g8733589f6 (2023-04-19T20:50:42+06:00)
DB Schema | 2021_02_09_122930_migrate_to_utf8mb4 (250)
PHP       | 8.1.18
Python    | 3.6.8
Database  | MariaDB 10.11.2-MariaDB-log
RRDTool   | 1.7.0
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.5.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[FAIL]  Time between this server and the mysql database is off
 Mysql time 2023-04-20 12:25:47
 PHP time 2023-04-20 22:25:46
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[FAIL]  No active polling method detected
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[FAIL]  No active python wrapper pollers found
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
"Exception: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated" // app/Providers/ErrorReportingProvider.php:63
"/opt/librenms/LibreNMS/Validations/User.php:95" // app/Providers/ErrorReportingProvider.php:63
```

### What was the last working version of LibreNMS?

23.2.0

### Anything in the logs that might be useful for us?

```txt
Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xFD\x01\xC8\x01\xF4\x01...' for column `librenms_prod`.`ports_adsl`.`adslAturInvSerialNumber` at row 1 in /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
Stack trace:
#0 /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(119): Doctrine\DBAL\Driver\PDO\Exception::new()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(546): Illuminate\Database\Connection->run()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(498): Illuminate\Database\Connection->statement()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3322): Illuminate\Database\Query\Processors\Processor->processInsertGetId()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1869): Illuminate\Database\Query\Builder->insertGetId()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1330): Illuminate\Database\Eloquent\Builder->__call()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1295): Illuminate\Database\Eloquent\Model->insertAndSetId()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1138): Illuminate\Database\Eloquent\Model->performInsert()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Illuminate\Database\Eloquent\Model->save()
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(235): Illuminate\Support\HigherOrderCollectionProxy->Illuminate\Support\{closure}()
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\Support\Collection->each()
#15 /opt/librenms/LibreNMS/DB/SyncsModels.php(70): Illuminate\Support\HigherOrderCollectionProxy->__call()
#16 /opt/librenms/LibreNMS/Modules/Xdsl.php(154): LibreNMS\Modules\Xdsl->syncModels()
#17 /opt/librenms/LibreNMS/Modules/Xdsl.php(82): LibreNMS\Modules\Xdsl->pollAdsl()
#18 /opt/librenms/includes/polling/xdsl.inc.php(8): LibreNMS\Modules\Xdsl->poll()
#19 /opt/librenms/includes/polling/functions.inc.php(339): include('...')
#20 /opt/librenms/poller.php(126): poll_device()
#21 {main}

Next Illuminate\Database\QueryException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xFD\x01\xC8\x01\xF4\x01...' for column `librenms_prod`.`ports_adsl`.`adslAturInvSerialNumber` at row 1 (SQL: insert into `ports_adsl` (`adslLineCoding`, `adslLineType`, `adslAtucInvVendorID`, `adslAtucInvVersionNumber`, `adslAtucCurrSnrMgn`, `adslAtucCurrAtn`, `adslAtucCurrOutputPwr`, `adslAtucCurrAttainableRate`, `adslAturInvSerialNumber`, `adslAturInvVendorID`, `adslAturInvVersionNumber`, `adslAturCurrSnrMgn`, `adslAturCurrAtn`, `adslAturCurrOutputPwr`, `adslAturCurrAttainableRate`, `adslAtucChanCurrTxRate`, `adslAturChanCurrTxRate`, `port_id`) values (2, 3, ..BDCM, 06.05.17, 24.5, 12.5, 10.7, 23640000, m      S������o6.��r�, ..BDCM, A��jyu�o8, 11.2, 6.6, 12.2, 1307000, 5630000, 1148000, 152120)) in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(546): Illuminate\Database\Connection->run()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(498): Illuminate\Database\Connection->statement()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3322): Illuminate\Database\Query\Processors\Processor->processInsertGetId()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1869): Illuminate\Database\Query\Builder->insertGetId()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1330): Illuminate\Database\Eloquent\Builder->__call()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1295): Illuminate\Database\Eloquent\Model->insertAndSetId()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1138): Illuminate\Database\Eloquent\Model->performInsert()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Illuminate\Database\Eloquent\Model->save()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(235): Illuminate\Support\HigherOrderCollectionProxy->Illuminate\Support\{closure}()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\Support\Collection->each()
#12 /opt/librenms/LibreNMS/DB/SyncsModels.php(70): Illuminate\Support\HigherOrderCollectionProxy->__call()
#13 /opt/librenms/LibreNMS/Modules/Xdsl.php(154): LibreNMS\Modules\Xdsl->syncModels()
#14 /opt/librenms/LibreNMS/Modules/Xdsl.php(82): LibreNMS\Modules\Xdsl->pollAdsl()
#15 /opt/librenms/includes/polling/xdsl.inc.php(8): LibreNMS\Modules\Xdsl->poll()
#16 /opt/librenms/includes/polling/functions.inc.php(339): include('...')
#17 /opt/librenms/poller.php(126): poll_device()
#18 {main}  
[2023-04-20T22:33:07.127147+06:00] production.ERROR: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xFD\x01\xC8\x01\xF4\x01...' for column `librenms_prod`.`ports_adsl`.`adslAturInvSerialNumber` at row 1 (SQL: insert into `ports_adsl` (`adslLineCoding`, `adslLineType`, `adslAtucInvVendorID`, `adslAtucInvVersionNumber`, `adslAtucCurrSnrMgn`, `adslAtucCurrAtn`, `adslAtucCurrOutputPwr`, `adslAtucCurrAttainableRate`, `adslAturInvSerialNumber`, `adslAturInvVendorID`, `adslAturInvVersionNumber`, `adslAturCurrSnrMgn`, `adslAturCurrAtn`, `adslAturCurrOutputPwr`, `adslAturCurrAttainableRate`, `adslAtucChanCurrTxRate`, `adslAturChanCurrTxRate`, `port_id`) values (2, 3, ..BDCM, 06.05.17, 24.5, 12.5, 10.7, 23640000, m  S������o6.��r�, ..BDCM, A��jyu�o8, 11.2, 6.6, 12.2, 1307000, 5630000, 1148000, 152120)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xFD\\x01\\xC8\\x01\\xF4\\x01...' for column `librenms_prod`.`ports_adsl`.`adslAturInvSerialNumber` at row 1 (SQL: insert into `ports_adsl` (`adslLineCoding`, `adslLineType`, `adslAtucInvVendorID`, `adslAtucInvVersionNumber`, `adslAtucCurrSnrMgn`, `adslAtucCurrAtn`, `adslAtucCurrOutputPwr`, `adslAtucCurrAttainableRate`, `adslAturInvSerialNumber`, `adslAturInvVendorID`, `adslAturInvVersionNumber`, `adslAturCurrSnrMgn`, `adslAturCurrAtn`, `adslAturCurrOutputPwr`, `adslAturCurrAttainableRate`, `adslAtucChanCurrTxRate`, `adslAturChanCurrTxRate`, `port_id`) values (2, 3, ..BDCM, 06.05.17, 24.5, 12.5, 10.7, 23640000, \u0002m\u0002\t\u0002S\u0001�\u0001�\u0001�\u0001�\u0001�\u0001�\u0001o\u00016\u0001.\u0001�\u0001�\u0001r\u0001�, ..BDCM, A�\u0003�\u0002j\u0002y\u0002u\u0002�\u0002o\u00028, 11.2, 6.6, 12.2, 1307000, 5630000, 1148000, 152120)) at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xFD\\x01\\xC8\\x01\\xF4\\x01...' for column `librenms_prod`.`ports_adsl`.`adslAturInvSerialNumber` at row 1 at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)
[previous exception] [object] (PDOException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xFD\\x01\\xC8\\x01\\xF4\\x01...' for column `librenms_prod`.`ports_adsl`.`adslAturInvSerialNumber` at row 1 at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} 
/opt/librenms/poller.php 2197 2023-04-20 22:33:07 - 1 devices polled in 535.9 secs
[librenms@obsrv-app-01 logs]$ ^C
[librenms@obsrv-app-01 logs]$ tail librenms.log 
#16 /opt/librenms/includes/polling/functions.inc.php(339): include('...')
#17 /opt/librenms/poller.php(126): poll_device()
#18 {main}  
[2023-04-20T22:33:10.946651+06:00] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'ports_adsl_port_id_unique' (SQL: insert into `ports_adsl` (`adslAtucInvVendorID`, `adslAturInvVendorID`, `adslAturInvVersionNumber`, `adslAtucInvVersionNumber`, `port_id`) values (, , , , 0)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'ports_adsl_port_id_unique' (SQL: insert into `ports_adsl` (`adslAtucInvVendorID`, `adslAturInvVendorID`, `adslAturInvVersionNumber`, `adslAtucInvVersionNumber`, `port_id`) values (, , , , 0)) at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'ports_adsl_port_id_unique' at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)
[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'ports_adsl_port_id_unique' at /opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} 
/opt/librenms/poller.php 6059 2023-04-20 22:33:11 - 1 devices polled in 125.6 secs
/opt/librenms/poller.php 3704 2023-04-20 22:33:11 - 1 devices polled in 117.0 secs
/opt/librenms/poller.php 6314 2023-04-20 22:33:12 - 1 devices polled in 94.71 secs
/opt/librenms/discovery.php 1004 2023-04-20 22:33:12 - 1 devices discovered in 10.57 secs
[librenms@obsrv-app-01 logs]$
```

**Comment by murrant** [comment]
Uh, you sure this has anything to do with Laravel?

This command seems to be failing on your system causing an error in validate: `find /opt/librenms \! -user librenms -o \! -group librenms 2> /dev/null`

The ADSL module seems to be trying to inject garbage into the database `\xFD\x01\xC8\x01\xF4\x0`, is that from a device of yours?

**Comment by Jellyfrog** [comment]
> DB Schema | 2021_02_09_122930_migrate_to_utf8mb4 (250)
You haven't run migrations in years. I'm surprised anything is working

**Comment by drykov-ttc** [comment]
> You haven't run migrations in years. I'm surprised anything is working

Yes i do. A new installation fix this problem.
