### ISSUE TITLE
Error in daily.sh "PHP Fatal error:  Uncaught ArgumentCountError" and error in validate.php

### ISSUE THREAD

**Issue by FK1985** [librenms/librenms#15034]
### The problem

Step "Updating composer packages" fails within daily.sh:

```
Updating to latest codebase                        OK
Updating Composer packages                         FAIL
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/console/Helper/HelperSet.php on line 112

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/console/Helper/HelperSet.php on line 112
Deprecation Notice: Optional parameter $schema declared before required parameter $path is implicitly treated as a required parameter in phar:///opt/librenms/composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Optional parameter $schema declared before required parameter $path is implicitly treated as a required parameter in phar:///opt/librenms/composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///opt/librenms/composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/Repository/ArrayRepository.php:196
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/Repository/ArrayRepository.php:196
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/Repository/ArrayRepository.php:196
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///opt/librenms/composer.phar/src/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///opt/librenms/composer.phar/src/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Finder.php:675
Deprecation Notice: Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Finder.php:732
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with FilterIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Iterator/FilterIterator.php:30
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Iterator/FileTypeFilterIterator.php:42
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:85
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() should either be compatible with FilesystemIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:113
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::current() should either be compatible with FilesystemIterator::current(): SplFileInfo|FilesystemIterator|string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:65
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:55
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:71
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:76
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Iterator/FilterIterator.php:30
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Iterator/FilenameFilterIterator.php:28
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/vendor/symfony/finder/Iterator/PathFilterIterator.php:27
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///opt/librenms/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:321
> LibreNMS\ComposerHelper::preInstall
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/Repository/ArrayRepository.php:196
Deprecation Notice: Return type of Composer\Repository\CompositeRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/Repository/CompositeRepository.php:139
Loading composer repositories with package information
Deprecation Notice: Return type of Composer\DependencyResolver\Pool::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Pool.php:166
Installing dependencies from lock file
Deprecation Notice: Return type of Composer\DependencyResolver\RuleSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/RuleSet.php:114
Deprecation Notice: Return type of Composer\DependencyResolver\RuleSet::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/RuleSet.php:99
Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Decisions.php:155
Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Decisions.php:165
Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Decisions.php:160
Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Decisions.php:170
Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Decisions.php:150
Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Decisions.php:145
Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/RuleSetIterator.php:36
Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/RuleSetIterator.php:46
Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/RuleSetIterator.php:41
Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/RuleSetIterator.php:89
Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/RuleSetIterator.php:70
PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge(amenadiel/jpgraph: Array)
#1 phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array('array_merge', Array)
#2 phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages(Object(Composer\DependencyResolver\Pool), Array, Array, 'amenadiel/jpgra...')
#3 phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Solver.php(742): Composer\DependencyResolver\Solver->selectAndInstall(1, Array, Array, Object(Composer\DependencyResolver\GenericRule))
#4 phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat(Array)
#5 phar:///opt/librenms/composer.phar/src/Composer/Installer.php(475): Composer\DependencyResolver\Solver->solve(Object(Composer\DependencyResolver\Request), false)
#6 phar:///opt/librenms/composer.phar/src/Composer/Installer.php(229): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array)
#7 phar:///opt/librenms/composer.phar/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
#8 phar:///opt/librenms/composer.phar/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///opt/librenms/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///opt/librenms/composer.phar/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///opt/librenms/composer.phar/src/Composer/Console/Application.php(258): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///opt/librenms/composer.phar/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///opt/librenms/composer.phar/src/Composer/Console/Application.php(104): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///opt/librenms/composer.phar/bin/composer(61): Composer\Console\Application->run()
#15 /opt/librenms/composer.phar(24): require('phar:///opt/lib...')
#16 {main}
  thrown in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php on line 84

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge(amenadiel/jpgraph: Array)
#1 phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array('array_merge', Array)
#2 phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages(Object(Composer\DependencyResolver\Pool), Array, Array, 'amenadiel/jpgra...')
#3 phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Solver.php(742): Composer\DependencyResolver\Solver->selectAndInstall(1, Array, Array, Object(Composer\DependencyResolver\GenericRule))
#4 phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat(Array)
#5 phar:///opt/librenms/composer.phar/src/Composer/Installer.php(475): Composer\DependencyResolver\Solver->solve(Object(Composer\DependencyResolver\Request), false)
#6 phar:///opt/librenms/composer.phar/src/Composer/Installer.php(229): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array)
#7 phar:///opt/librenms/composer.phar/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
#8 phar:///opt/librenms/composer.phar/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///opt/librenms/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///opt/librenms/composer.phar/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///opt/librenms/composer.phar/src/Composer/Console/Application.php(258): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///opt/librenms/composer.phar/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///opt/librenms/composer.phar/src/Composer/Console/Application.php(104): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///opt/librenms/composer.phar/bin/composer(61): Composer\Console\Application->run()
#15 /opt/librenms/composer.phar(24): require('phar:///opt/lib...')
#16 {main}
  thrown in phar:///opt/librenms/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php on line 84
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK
Caching Mac OUI data                               OK
```

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.4.1-652-g15216f5 (2023-05-10T00:15:08+02:00)
DB Schema | 2023_04_12_174529_modify_ports_table (250)
PHP       | 8.1.18
Python    | 3.6.8
Database  | MariaDB 10.5.19-MariaDB
RRDTool   | 1.4.8
SNMP      | 5.7.2
===========================================

[OK]    Composer Version: 1.8.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[FAIL]  Python3 module issue found: 'Required packages: ['PyMySQL!=1.0.0', 'python-dotenv', 'redis>=4.0', 'setuptools', 'psutil>=5.6.0', 'command_runner>=1.3.0']
Required version not satisfied: (redis 3.5.3 (/opt/librenms/.local/lib/python3.6/site-packages), Requirement.parse('redis>=4.0'))
'
        [FIX]:
        pip3 install -r /opt/librenms/requirements.txt
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Anything in the logs that might be useful for us?

```txt
pip3 install -r /opt/librenms/requirements.txt
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already satisfied: PyMySQL!=1.0.0 in /root/.local/lib/python3.6/site-packages (from -r /opt/librenms/requirements.txt (line 1))
Requirement already satisfied: python-dotenv in /root/.local/lib/python3.6/site-packages (from -r /opt/librenms/requirements.txt (line 2))
Requirement already satisfied: redis>=4.0 in /root/.local/lib/python3.6/site-packages (from -r /opt/librenms/requirements.txt (line 3))
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from -r /opt/librenms/requirements.txt (line 4))
Requirement already satisfied: psutil>=5.6.0 in /root/.local/lib/python3.6/site-packages (from -r /opt/librenms/requirements.txt (line 5))
Requirement already satisfied: command_runner>=1.3.0 in /root/.local/lib/python3.6/site-packages (from -r /opt/librenms/requirements.txt (line 6))
Requirement already satisfied: async-timeout>=4.0.2 in /root/.local/lib/python3.6/site-packages (from redis>=4.0->-r /opt/librenms/requirements.txt (line 3))
Requirement already satisfied: importlib-metadata>=1.0; python_version < "3.8" in /root/.local/lib/python3.6/site-packages (from redis>=4.0->-r /opt/librenms/requirements.txt (line 3))
Requirement already satisfied: typing-extensions; python_version < "3.8" in /root/.local/lib/python3.6/site-packages (from redis>=4.0->-r /opt/librenms/requirements.txt (line 3))
Requirement already satisfied: deprecated>=1.2.3 in /root/.local/lib/python3.6/site-packages (from redis>=4.0->-r /opt/librenms/requirements.txt (line 3))
Requirement already satisfied: packaging>=20.4 in /root/.local/lib/python3.6/site-packages (from redis>=4.0->-r /opt/librenms/requirements.txt (line 3))
Requirement already satisfied: zipp>=0.5 in /root/.local/lib/python3.6/site-packages (from importlib-metadata>=1.0; python_version < "3.8"->redis>=4.0->-r /opt/librenms/requirements.txt (line 3))
Requirement already satisfied: wrapt<2,>=1.10 in /root/.local/lib/python3.6/site-packages (from deprecated>=1.2.3->redis>=4.0->-r /opt/librenms/requirements.txt (line 3))
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /root/.local/lib/python3.6/site-packages (from packaging>=20.4->redis>=4.0->-r /opt/librenms/requirements.txt (line 3))
```

**Comment by peejaychilds** [comment]
`pip3 install -r /opt/librenms/requirements.txt ` should be run as the librenms user?
