### ISSUE TITLE
Error with Cisco FTD polling cipsec-modules

### ISSUE THREAD

**Issue by olivianrususv** [librenms/librenms#15073]
### The problem

Hello,

We are encountering several error events on multiple Cisco FTDs: Error polling cipsec-tunnels module. Check log file for more details. .
On a closer look into the log file : 

Error polling cipsec-tunnels module for XXXXXX. LibreNMS\Exceptions\InvalidIpException: Could not parse into IP:  in /opt/librenms/LibreNMS/Util/IP.php:72
Stack trace:
#0 /opt/librenms/includes/polling/cipsec-tunnels.inc.php(29): LibreNMS\Util\IP::fromHexString('')
#1 /opt/librenms/includes/polling/functions.inc.php(339): include('/opt/librenms/i...')
#2 /opt/librenms/poller.php(126): poll_device(Array, false)
#3 {main}  
Could not parse into IP:  {"exception":"[object] (LibreNMS\\Exceptions\\InvalidIpException(code: 0): Could not parse into IP:  at /opt/librenms/LibreNMS/Util/IP.php:72)"} 

It seems that it wants to parse an empty string , maybe there's a small validation missing ? 
Can you help with this ? I don't know if I should post this on the community site or not.
Thanks!

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.5.0 (2023-05-25T00:15:11+03:00)
DB Schema | 2023_04_27_164904_update_slas_opstatus_tinyint (252)
PHP       | 8.1.10
Python    | 3.6.8
Database  | MariaDB 10.5.17-MariaDB
RRDTool   | 1.4.8
SNMP      | 5.7.2
===========================================

[OK]    Composer Version: 2.5.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[INFO]  fping FAILURES can be ignored if running LibreNMS in a jail without ::1. You may want to test it manually: fping ::1
[FAIL]  /usr/sbin/fping6 could not be executed. /usr/sbin/fping6 must have CAP_NET_RAW capability (getcap) or suid. Selinux exclusions may be required.
 ((null): can't create raw socket (must run as root?) : Protocol not supported)
[FAIL]  /usr/sbin/fping6 should have CAP_NET_RAW!
	[FIX]: 
	setcap cap_net_raw+ep /usr/sbin/fping6
[WARN]  Could not check Python dependencies because this script is not running as librenms
	[FIX]: 
	The install docs show how this is done on a new install: https://docs.librenms.org/Installation/Install-LibreNMS/#configure-php-fpm
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[FAIL]  Scheduler is not running
	[FIX]: 
	cp /opt/librenms/dist/librenms-scheduler.service /opt/librenms/dist/librenms-scheduler.timer /etc/systemd/system/
systemctl enable librenms-scheduler.timer
systemctl start librenms-scheduler.timer
[WARN]  Global lnms shortcut not installed. lnms command must be run with full path
	[FIX]: 
	sudo ln -s /opt/librenms/lnms /usr/local/bin/lnms
[WARN]  Bash completion not installed. lnms command tab completion unavailable.
	[FIX]: 
	sudo cp /opt/librenms/misc/lnms-completion.bash /etc/bash_completion.d/
[WARN]  Log rotation not enabled, could cause disk space issues
	[FIX]: 
	sudo cp /opt/librenms/misc/librenms.logrotate /etc/logrotate.d/librenms
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>

Diff output format options
    -p, --patch           generate patch
    -s, --no-patch        suppress diff output
    -u                    generate patch
    -U, --unified[=<n>]   generate diffs with <n> lines context
    -W, --function-context
                          generate diffs with <n> lines context
    --raw                 generate the diff in raw format
    --patch-with-raw      synonym for '-p --raw'
    --patch-with-stat     synonym for '-p --stat'
    --numstat             machine friendly --stat
    --shortstat           output only the last line of --stat
    -X, --dirstat[=<param1,param2>...]
                          output the distribution of relative amount of changes for each sub-directory
    --cumulative          synonym for --dirstat=cumulative
    --dirstat-by-file[=<param1,param2>...]
                          synonym for --dirstat=files,param1,param2...
    --check               warn if changes introduce conflict markers or whitespace errors
    --summary             condensed summary such as creations, renames and mode changes
    --name-only           show only names of changed files
    --name-status         show only names and status of changed files
    --stat[=<width>[,<name-width>[,<count>]]]
                          generate diffstat
    --stat-width <width>  generate diffstat with a given width
    --stat-name-width <width>
                          generate diffstat with a given name width
    --stat-graph-width <width>
                          generate diffstat with a given graph width
    --stat-count <count>  generate diffstat with limited lines
    --compact-summary     generate compact summary in diffstat
    --binary              output a binary diff that can be applied
    --full-index          show full pre- and post-image object names on the "index" lines
    --color[=<when>]      show colored diff
    --ws-error-highlight <kind>
                          highlight whitespace errors in the 'context', 'old' or 'new' lines in the diff
    -z                    do not munge pathnames and use NULs as output field terminators in --raw or --numstat
    --abbrev[=<n>]        use <n> digits to display object names
    --src-prefix <prefix>
                          show the given source prefix instead of "a/"
    --dst-prefix <prefix>
                          show the given destination prefix instead of "b/"
    --line-prefix <prefix>
                          prepend an additional prefix to every line of output
    --no-prefix           do not show any source or destination prefix
    --inter-hunk-context <n>
                          show context between diff hunks up to the specified number of lines
    --output-indicator-new <char>
                          specify the character to indicate a new line instead of '+'
    --output-indicator-old <char>
                          specify the character to indicate an old line instead of '-'
    --output-indicator-context <char>
                          specify the character to indicate a context instead of ' '

Diff rename options
    -B, --break-rewrites[=<n>[/<m>]]
                          break complete rewrite changes into pairs of delete and create
    -M, --find-renames[=<n>]
                          detect renames
    -D, --irreversible-delete
                          omit the preimage for deletes
    -C, --find-copies[=<n>]
                          detect copies
    --find-copies-harder  use unmodified files as source to find copies
    --no-renames          disable rename detection
    --rename-empty        use empty blobs as rename source
    --follow              continue listing the history of a file beyond renames
    -l <n>                prevent rename/copy detection if the number of rename/copy targets exceeds given limit

Diff algorithm options
    --minimal             produce the smallest possible diff
    -w, --ignore-all-space
                          ignore whitespace when comparing lines
    -b, --ignore-space-change
                          ignore changes in amount of whitespace
    --ignore-space-at-eol
                          ignore changes in whitespace at EOL
    --ignore-cr-at-eol    ignore carrier-return at the end of line
    --ignore-blank-lines  ignore changes whose lines are all blank
    -I, --ignore-matching-lines <regex>
                          ignore changes whose all lines match <regex>
    --indent-heuristic    heuristic to shift diff hunk boundaries for easy reading
    --patience            generate diff using the "patience diff" algorithm
    --histogram           generate diff using the "histogram diff" algorithm
    --diff-algorithm <algorithm>
                          choose a diff algorithm
    --anchored <text>     generate diff using the "anchored diff" algorithm
    --word-diff[=<mode>]  show word diff, using <mode> to delimit changed words
    --word-diff-regex <regex>
                          use <regex> to decide what a word is
    --color-words[=<regex>]
                          equivalent to --word-diff=color --word-diff-regex=<regex>
    --color-moved[=<mode>]
                          moved lines of code are colored differently
    --color-moved-ws <mode>
                          how white spaces are ignored in --color-moved

Other diff options
    --relative[=<prefix>]
                          when run from subdir, exclude changes outside and show relative paths
    -a, --text            treat all files as text
    -R                    swap two inputs, reverse the diff
    --exit-code           exit with 1 if there were differences, 0 otherwise
    --quiet               disable all output of the program
    --ext-diff            allow an external diff helper to be executed
    --textconv            run external text conversion filters when comparing binary files
    --ignore-submodules[=<when>]
                          ignore changes to submodules in the diff generation
    --submodule[=<format>]
                          specify how differences in submodules are shown
    --ita-invisible-in-index
                          hide 'git add -N' entries from the index
    --ita-visible-in-index
                          treat 'git add -N' entries as real in the index
    -S <string>           look for differences that change the number of occurrences of the specified string
    -G <regex>            look for differences that change the number of occurrences of the specified regex
    --pickaxe-all         show all changes in the changeset with -S or -G
    --pickaxe-regex       treat <string> in -S as extended POSIX regular expression
    -O <file>             control the order in which files appear in the output
    --rotate-to <path>    show the change in the specified path first
    --skip-to <path>      skip the output to the specified path
    --find-object <object-id>
                          look for differences that change the number of occurrences of the specified object
    --diff-filter [(A|C|D|M|R|T|U|X|B)...[*]]
                          select files by diff type
    --output <file>       output to a specific file

[FAIL]  Failed to fetch version from local git: fatal: detected dubious ownership in repository at '/opt/librenms'
To add an exception for this directory, call:

	git config --global --add safe.directory /opt/librenms
[WARN]  Your local git branch is not master, this will prevent automatic updates.
	[FIX]: 
	You can switch back to master with git checkout master
[FAIL]  You need to run this script as 'librenms' or root
[FAIL]  We have found some files that are owned by a different user than 'librenms', this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
	[FIX]: 
	sudo chown -R librenms:librenms /opt/librenms
	sudo setfacl -d -m g::rwx /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
	sudo chmod -R ug=rwX /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
	Files:
	 /opt/librenms/storage/app/purifier
	 /opt/librenms/storage/app/purifier/URI
	 /opt/librenms/storage/app/purifier/URI/4.15.0,3478238e680361cd87bf880f5b3cc50a1e7abc6c,1.ser
	 /opt/librenms/storage/app/purifier/HTML
	 /opt/librenms/storage/app/purifier/HTML/4.15.0,fe97c36109f79a043b63c51aaa36362f0f2f6553,1.ser
```

### Anything in the logs that might be useful for us?

```txt
/opt/librenms/poller.php 295 2023-05-30 14:17:07 - 1 devices polled in 15.48 secs
Error polling cipsec-tunnels module for XXXXXX. LibreNMS\Exceptions\InvalidIpException: Could not parse into IP:  in /opt/librenms/LibreNMS/Util/IP.php:72
Stack trace:
#0 /opt/librenms/includes/polling/cipsec-tunnels.inc.php(29): LibreNMS\Util\IP::fromHexString('')
#1 /opt/librenms/includes/polling/functions.inc.php(339): include('/opt/librenms/i...')
#2 /opt/librenms/poller.php(126): poll_device(Array, false)
#3 {main}  
Could not parse into IP:  {"exception":"[object] (LibreNMS\\Exceptions\\InvalidIpException(code: 0): Could not parse into IP:  at /opt/librenms/LibreNMS/Util/IP.php:72)"} 
/opt/librenms/poller.php 266 2023-05-30 14:17:09 - 1 devices polled in 17.64 secs
/opt/librenms/poller.php 232 2023-05-30 14:17:09 - 1 devices polled in 14.77 secs
/opt/librenms/poller.php 298 2023-05-30 14:17:10 - 1 devices polled in 13.77 secs
/opt/librenms/poller.php 114 2023-05-30 14:17:13 - 1 devices polled in 129.8 secs
/opt/librenms/poller.php 254 2023-05-30 14:17:14 - 1 devices polled in 14.84 secs
/opt/librenms/poller.php 66 2023-05-30 14:17:15 - 1 devices polled in 14.34 secs
/opt/librenms/poller.php 231 2023-05-30 14:17:15 - 1 devices polled in 14.67 secs
/opt/librenms/poller.php 279 2023-05-30 14:17:18 - 1 devices polled in 11.85 secs
/opt/librenms/poller.php 133 2023-05-30 14:17:18 - 1 devices polled in 12.98 secs
/opt/librenms/poller.php 127 2023-05-30 14:17:19 - 1 devices polled in 12.82 secs
/opt/librenms/poller.php 280 2023-05-30 14:17:19 - 1 devices polled in 12.16 secs
/opt/librenms/poller.php 299 2023-05-30 14:17:19 - 1 devices polled in 12.35 secs
Error polling cipsec-tunnels module for XXXXXXXX. LibreNMS\Exceptions\InvalidIpException: Could not parse into IP:  in /opt/librenms/LibreNMS/Util/IP.php:72
Stack trace:
#0 /opt/librenms/includes/polling/cipsec-tunnels.inc.php(29): LibreNMS\Util\IP::fromHexString('')
#1 /opt/librenms/includes/polling/functions.inc.php(339): include('/opt/librenms/i...')
#2 /opt/librenms/poller.php(126): poll_device(Array, false)
#3 {main}  
Could not parse into IP:  {"exception":"[object] (LibreNMS\\Exceptions\\InvalidIpException(code: 0): Could not parse into IP:  at /opt/librenms/LibreNMS/Util/IP.php:72)"}
```

**Comment by laf** [comment]
Closing old issues down, please create a new one with updated debug if this is still relevant.
