### ISSUE TITLE
Aruba Switch does not shown CPU and Memory graph

### ISSUE THREAD

**Issue by cheungray** [librenms/librenms#15081]
### The problem

Aruba Switch only collect the network interface data from snmp, it does not shown CPU and memory
![Screenshot 2023-05-31 110154](https://github.com/librenms/librenms/assets/40875939/5afac9d4-f67a-46c0-a29a-e4da28c95f78)

### Output of ./validate.php

```txt
librenms@pc-mon1p:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.5.0-9-gea57c2518 (2023-05-31T07:49:12+08:00)
DB Schema | 2023_04_27_164904_update_slas_opstatus_tinyint (252)
PHP       | 8.1.2-1ubuntu2.11
Python    | 3.10.6
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.5.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

**Comment by ervin09** [comment]
same issue also on HP ProCurve 2.7.0.0

**Comment by PipoCanaja** [comment]
Hi @ervin09  and @cheungray 
As you have this device in your environnement, please have a look at the discovery and poller code to check if the values are polled or not. Seems that they are not. 
Next step is to check if the values are available from the device or not. 
- If yes, then it can be fixed, and please attach the details here. 
- If not, LibreNMS cannot display values that are not provided by the device as you can imagine. You can then close this issue.
Thanx

**Comment by ervin09** [comment]
@PipoCanaja thanks for looking into this issue :) 
here's a discovery of the device on my side . please let me know if i need to add more flags, or something:
`./discovery.php -h 172.21.3.17
LibreNMS Discovery
172.21.3.17 23 procurve
#### Load disco module core ####
OS: HP ProCurve (procurve)

>> Runtime for discovery module 'core': 0.2040 seconds with 2900848 bytes
>> SNMP: [1/0.03s] MySQL: [0/0.00s] RRD: [0/0.00s]
#### Unload disco module core ####

#### Load disco module os ####
Location: 2.OG A4 (rechts bei conf264)
Hardware: 1930 48G Class4 PoE 4SFP/SFP+ 370W JL686A
OS Version: 2.7.0.0
OS Features:
Serial: CN07KPJ0F3

>> Runtime for discovery module 'os': 0.1190 seconds with 212744 bytes
>> SNMP: [4/0.08s] MySQL: [1/0.00s] RRD: [0/0.00s]
#### Unload disco module os ####

#### Load disco module ports ####
....................................................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..X.

>> Runtime for discovery module 'ports': 1.0930 seconds with 73432 bytes
>> SNMP: [5/1.08s] MySQL: [56/0.06s] RRD: [0/0.00s]
#### Unload disco module ports ####

#### Load disco module ports-stack ####
....................................................................

>> Runtime for discovery module 'ports-stack': 0.0810 seconds with -304 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [0/0.00s]
#### Unload disco module ports-stack ####

Module [ xdsl ] disabled globally.

#### Load disco module entity-physical ####

Caching OIDs: entPhysicalEntry entAliasMappingIdentifier.....................................................................

>> Runtime for discovery module 'entity-physical': 0.4070 seconds with 72128 bytes
>> SNMP: [1/0.34s] MySQL: [139/0.27s] RRD: [0/0.00s]
#### Unload disco module entity-physical ####

Module [ entity-state ] disabled globally.

Module [ isis ] disabled globally.

#### Load disco module processors ####
Pre-cache procurve: hpicfSensorTable hpicfXcvrInfoTable
Caching data: mempools os processors sensors
Host Resources: UCD Resources:

>> Runtime for discovery module 'processors': 0.1480 seconds with 25736 bytes
>> SNMP: [7/0.14s] MySQL: [2/0.01s] RRD: [0/0.00s]
#### Unload disco module processors ####

#### Load disco module mempools ####

>> Runtime for discovery module 'mempools': 0.2360 seconds with 237240 bytes
>> SNMP: [12/0.23s] MySQL: [1/0.00s] RRD: [0/0.00s]
#### Unload disco module mempools ####

#### Load disco module cisco-vrf-lite ####

>> Runtime for discovery module 'cisco-vrf-lite': 0.0000 seconds with -1688 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [0/0.00s]
#### Unload disco module cisco-vrf-lite ####

Module [ cisco-mac-accounting ] disabled globally.

Module [ cisco-pw ] disabled globally.

Module [ vrf ] disabled globally.

Module [ cisco-cef ] disabled globally.

Module [ slas ] disabled globally.

Module [ cisco-cbqos ] disabled globally.

Module [ cisco-otv ] disabled globally.

Module [ cisco-qfp ] disabled globally.

#### Load disco module ipv4-addresses ####
s.s.

>> Runtime for discovery module 'ipv4-addresses': 0.0450 seconds with -10520 bytes
>> SNMP: [3/0.04s] MySQL: [16/0.04s] RRD: [0/0.00s]
#### Unload disco module ipv4-addresses ####

#### Load disco module ipv6-addresses ####
Error discovering ipv6-addresses module for 172.21.3.17. TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /opt/librenms/LibreNMS/Data/Source/NetSnmpQuery.php:397
Stack trace:
#0 /opt/librenms/LibreNMS/Data/Source/NetSnmpQuery.php(397): implode()
#1 [internal function]: LibreNMS\Data\Source\NetSnmpQuery->LibreNMS\Data\Source\{closure}()
#2 /opt/librenms/LibreNMS/Data/Source/NetSnmpQuery.php(397): array_map()
#3 /opt/librenms/LibreNMS/Data/Source/NetSnmpQuery.php(288): LibreNMS\Data\Source\NetSnmpQuery->execMultiple()
#4 /opt/librenms/includes/discovery/ipv6-addresses.inc.php(14): LibreNMS\Data\Source\NetSnmpQuery->walk()
#5 /opt/librenms/includes/discovery/functions.inc.php(164): include('/opt/librenms/i...')
#6 /opt/librenms/discovery.php(108): discover_device()
#7 {main}
implode(): Argument #2 ($array) must be of type ?array, string given {"exception":"[object] (TypeError(code: 0): implode(): Argument #2 ($array) must be of type ?array, string given at /opt/librenms/LibreNMS/Data/Source/NetSnmpQuery.php:397)"}

>> Runtime for discovery module 'ipv6-addresses': 0.1740 seconds with 260552 bytes
>> SNMP: [1/0.02s] MySQL: [3/0.01s] RRD: [0/0.00s]
#### Unload disco module ipv6-addresses ####

Module [ route ] disabled globally.

#### Load disco module sensors ####
 ENTITY-SENSOR: Caching OIDs: entPhysicalDescr entPhysicalName entPhySensorType entPhySensorScale entPhySensorPrecision entPhySensorValue entPhySensorOperStatus
Airflow:
Current:
Charge:
Dbm: Procurve
Fanspeed:
Frequency:
Humidity:
Load:
Loss:
Power:
Power_consumed:
Power_factor:
Runtime:
Signal:
State:
Count:
Temperature: Procurve
Tv_signal:
Bitrate:
Voltage: Procurve
Snr:
Pressure:
Cooling:
Delay:
Quality_factor:
Chromatic_dispersion:
Ber:
Eer:
Waterflow:
Percent:

>> Runtime for discovery module 'sensors': 0.1970 seconds with 127600 bytes
>> SNMP: [8/0.18s] MySQL: [35/0.09s] RRD: [0/0.00s]
#### Unload disco module sensors ####

#### Load disco module storage ####
hrStorage :

>> Runtime for discovery module 'storage': 0.0830 seconds with 4312 bytes
>> SNMP: [2/0.05s] MySQL: [2/0.00s] RRD: [0/0.00s]
#### Unload disco module storage ####

#### Load disco module hr-device ####

>> Runtime for discovery module 'hr-device': 0.0630 seconds with 1416 bytes
>> SNMP: [2/0.06s] MySQL: [1/0.00s] RRD: [0/0.00s]
#### Unload disco module hr-device ####

#### Load disco module discovery-protocols ####
 LLDP-MIB: .++...........+..
 OSPF Discovery:

>> Runtime for discovery module 'discovery-protocols': 0.6040 seconds with 293144 bytes
>> SNMP: [3/0.31s] MySQL: [155/0.37s] RRD: [0/0.00s]
#### Unload disco module discovery-protocols ####


#### Load disco module arp-table ####
1:
...

>> Runtime for discovery module 'arp-table': 0.0410 seconds with 872 bytes
>> SNMP: [2/0.03s] MySQL: [3/0.06s] RRD: [0/0.00s]
#### Unload disco module arp-table ####

Module [ discovery-arp ] disabled globally.

Module [ junose-atm-vp ] disabled globally.

#### Load disco module bgp-peers ####
AS1

>> Runtime for discovery module 'bgp-peers': 0.0320 seconds with 120 bytes
>> SNMP: [2/0.03s] MySQL: [3/0.01s] RRD: [0/0.00s]
#### Unload disco module bgp-peers ####

#### Load disco module vlans ####
IEEE8021-Q-BRIDGE-MIB VLANs: ver version1
VLAN 1
dot1d id  ifIndex   Port Name                Priority  State          Cost
1         1         1                        0         unknown        0         Updated
2         2         2                        0         unknown        0         Updated
3         3         3                        0         unknown        0         Updated
4         4         4                        0         unknown        0         Updated
5         5         5                        0         unknown        0         Updated
6         6         6                        0         unknown        0         Updated
7         7         7                        0         unknown        0         Updated
8         8         8                        0         unknown        0         Updated
9         9         9                        0         unknown        0         Updated
10        10        10                       0         unknown        0         Updated
11        11        11                       0         unknown        0         Updated
12        12        12                       0         unknown        0         Updated
13        13        13                       0         unknown        0         Updated
14        14        14                       0         unknown        0         Updated
15        15        15                       0         unknown        0         Updated
16        16        16                       0         unknown        0         Updated
17        17        17                       0         unknown        0         Updated
18        18        18                       0         unknown        0         Updated
19        19        19                       0         unknown        0         Updated
20        20        20                       0         unknown        0         Updated
21        21        21                       0         unknown        0         Updated
22        22        22                       0         unknown        0         Updated
23        23        23                       0         unknown        0         Updated
24        24        24                       0         unknown        0         Updated
25        25        25                       0         unknown        0         Updated
26        26        26                       0         unknown        0         Updated
27        27        27                       0         unknown        0         Updated
28        28        28                       0         unknown        0         Updated
29        29        29                       0         unknown        0         Updated
30        30        30                       0         unknown        0         Updated
31        31        31                       0         unknown        0         Updated
32        32        32                       0         unknown        0         Updated
33        33        33                       0         unknown        0         Updated
34        34        34                       0         unknown        0         Updated
35        35        35                       0         unknown        0         Updated
36        36        36                       0         unknown        0         Updated
37        37        37                       0         unknown        0         Updated
38        38        38                       0         unknown        0         Updated
39        39        39                       0         unknown        0         Updated
40        40        40                       0         unknown        0         Updated
41        41        41                       0         unknown        0         Updated
42        42        42                       0         unknown        0         Updated
43        43        43                       0         unknown        0         Updated
44        44        44                       0         unknown        0         Updated
45        45        45                       0         unknown        0         Updated
46        46        46                       0         unknown        0         Updated
47        47        47                       0         unknown        0         Updated
48        48        48                       0         unknown        0         Updated
49        49        49                       0         unknown        0         Updated
50        50        50                       0         unknown        0         Updated
51        51        51                       0         unknown        0         Updated
52        52        52                       0         unknown        0         Updated
1000      1000                               0         unknown        0         Inserted
1001      1001                               0         unknown        0         Inserted
1002      1002                               0         unknown        0         Inserted
1003      1003                               0         unknown        0         Inserted
1004      1004                               0         unknown        0         Inserted
1005      1005                               0         unknown        0         Inserted
1006      1006                               0         unknown        0         Inserted
1007      1007                               0         unknown        0         Inserted
1008      1008                               0         unknown        0         Inserted
1009      1009                               0         unknown        0         Inserted
1010      1010                               0         unknown        0         Inserted
1011      1011                               0         unknown        0         Inserted
1012      1012                               0         unknown        0         Inserted
1013      1013                               0         unknown        0         Inserted
1014      1014                               0         unknown        0         Inserted
1015      1015                               0         unknown        0         Inserted

>> Runtime for discovery module 'vlans': 0.2320 seconds with 642640 bytes
>> SNMP: [5/0.18s] MySQL: [207/0.41s] RRD: [0/0.00s]
#### Unload disco module vlans ####

Module [ vminfo ] disabled globally.

Module [ printer-supplies ] disabled globally.

#### Load disco module ucd-diskio ####

>> Runtime for discovery module 'ucd-diskio': 0.0330 seconds with 840 bytes
>> SNMP: [1/0.03s] MySQL: [1/0.00s] RRD: [0/0.00s]
#### Unload disco module ucd-diskio ####


#### Load disco module applications ####

Applications:

>> Runtime for discovery module 'applications': 0.0360 seconds with 71352 bytes
>> SNMP: [1/0.03s] MySQL: [3/0.01s] RRD: [0/0.00s]
#### Unload disco module applications ####


#### Load disco module services ####


>> Runtime for discovery module 'services': 0.0080 seconds with 76416 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [0/0.00s]
#### Unload disco module services ####

#### Load disco module stp ####
VLAN: 1 Bridge: b8:d4:e7:e6:86:f4 DR: b8:d4:e7:e6:86:f4
Instances: .
Ports:

>> Runtime for discovery module 'stp': 0.8780 seconds with 176336 bytes
>> SNMP: [5/0.86s] MySQL: [3/0.01s] RRD: [0/0.00s]
#### Unload disco module stp ####


#### Load disco module ntp ####

>> Runtime for discovery module 'ntp': 0.0000 seconds with 80 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [0/0.00s]
#### Unload disco module ntp ####

Module [ loadbalancers ] disabled globally.

Module [ mef ] disabled globally.


#### Load disco module wireless ####

>> Runtime for discovery module 'wireless': 0.0080 seconds with -2864 bytes
>> SNMP: [0/0.00s] MySQL: [24/0.04s] RRD: [0/0.00s]
#### Unload disco module wireless ####


#### Load disco module fdb-table ####
Q-BRIDGE-MIB:
 1: ......................+.......................................................................+...................+...+...............+........

>> Runtime for discovery module 'fdb-table': 0.2900 seconds with 192008 bytes
>> SNMP: [0/0.00s] MySQL: [24/0.04s] RRD: [0/0.00s]
#### Unload disco module fdb-table ####

#### Load disco module mpls ####

>> Runtime for discovery module 'mpls': 0.0000 seconds with 144 bytes
>> SNMP: [0/0.00s] MySQL: [0/0.00s] RRD: [0/0.00s]
#### Unload disco module mpls ####

Discovered in 8.285 seconds

SNMP [66/3.75s]: Snmpget[13/0.25s] Snmpwalk[46/3.42s] Snmptranslate[6/0.07s] Snmpgetnext[1/0.01s]
SQL [687/1.47s]: Select[464/1.06s] Update[182/0.30s] Delete[7/0.07s] Insert[34/0.05s]
RRD [0/0.00s]:
`

**Comment by ervin09** [comment]
and this is what i found out from HP : 
https://community.hpe.com/t5/aruba-provision-based/monitor-aruba-jl679a-6100-cpu-mem-etc-via-snmp/td-p/7147842

perhaps an update of the MIB files is required , but i don't know how to do that....

**Comment by sthen** [comment]
> and this is what i found out from HP : https://community.hpe.com/t5/aruba-provision-based/monitor-aruba-jl679a-6100-cpu-mem-etc-via-snmp/td-p/7147842
> 
> perhaps an update of the MIB files is required , but i don't know how to do that....

That info is for a 'classic' procurve type switch, yours is "Instant On" which I think runs fairly different software.

From the mibs available at https://community.arubainstanton.com/blogs/jamie-easly1/2022/02/07/1830 there's hpe-mng.mib which has various rlCpuUtil* however it appears cpu measurements are not done by default and need a value writing to rlCpuUtilEnable first (and then librenms would need to use the relevant oid).

**Comment by ervin09** [comment]
@sthen this is above my capabilities to grep that value. you're right im sitting on Instant On version.

**Comment by laf** [comment]
Closing old issues down, please create a new one with updated debug if this is still relevant.
