### ISSUE TITLE
Bird2 #14466 issues due to no timezone detected

### ISSUE THREAD

**Issue by netravnen** [librenms/librenms#15287]
### The problem

The recent introduction of Bird2 support (app) in #14466 has a parsing problem when no timezone is detected.

The installation is using Bird 2.13.1 on Debian 12 (bookworm).

The poller logs this information concerning the bird2 app.

The error indicates `2023-08-21    Active` this string cannot be parsed. Logs missing timezone as root cause.

### Output of ./validate.php

```txt
(venv) librenms@nms2:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.8.2-28-gc98cac8e6 (2023-09-06T07:50:51+00:00)
DB Schema | 2023_09_01_084057_application_new_defaults (258)
PHP       | 8.2.8
Python    | 3.11.2
Database  | MariaDB 10.11.3-MariaDB-1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.6.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Device info

Debian Bookworm running bird 2.13.1

### Discovery output

```txt
.
```

### Poller output

```txt
Application: bird2, app_id=52SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-Oqv' '-m' 'NET-SNMP-EXTEND-MIB' '-M' '/opt/librenms/mibs' 'udp:HOSTNAME:161' 'nsExtendOutputFull.5.98.105.114.100.50']
BIRD 2.13.1 ready.
Access restricted
Name       Proto      Table      State  Since         Info
device1    Device     ---        up     2023-08-19    

kernel1    Kernel     master4    up     2023-08-19    
  Channel ipv4
    State:          UP
    Table:          master4
    Preference:     10
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         0 imported, 18 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:              0          0          0          0          0
      Import withdraws:            0          0        ---          0          0
      Export updates:            688          0        109        ---        579
      Export withdraws:          249        ---        ---        ---        238

kernel2    Kernel     master6    up     2023-08-19    
  Channel ipv6
    State:          UP
    Table:          master6
    Preference:     10
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         0 imported, 2 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:              2          0          2          0          0
      Import withdraws:            0          0        ---          2          0
      Export updates:            111          0         21        ---         90
      Export withdraws:           60        ---        ---        ---         56

static1    Static     master4    up     2023-08-19    
  Channel ipv4
    State:          UP
    Table:          master4
    Preference:     200
    Input filter:   ACCEPT
    Output filter:  REJECT
    Routes:         0 imported, 0 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:              0          0          0          0          0
      Import withdraws:            0          0        ---          0          0
      Export updates:              0          0          0        ---          0
      Export withdraws:            0        ---        ---        ---          0

static2    Static     master6    up     2023-08-19    
  Channel ipv6
    State:          UP
    Table:          master6
    Preference:     200
    Input filter:   ACCEPT
    Output filter:  REJECT
    Routes:         1 imported, 0 exported, 1 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:              1          0          0          0          1
      Import withdraws:            0          0        ---          0          0
      Export updates:              0          0          0        ---          0
      Export withdraws:            0        ---        ---        ---          0

ospf3_main OSPF       master6    up     2023-08-21    Running
  Channel ipv6
    State:          UP
    Table:          master6
    Preference:     150
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         2 imported, 1 exported, 2 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:            196          0        162          7         27
      Import withdraws:          127          0        ---        106         25
      Export updates:             56         35         18        ---          3
      Export withdraws:           24        ---        ---        ---          0

ospf2_main OSPF       master4    up     2023-08-21    Running
  Channel ipv4
    State:          UP
    Table:          master4
    Preference:     150
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         22 imported, 0 exported, 22 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:            888          0        491         63        334
      Import withdraws:          369          0        ---        215        160
      Export updates:            409        401          8        ---          0
      Export withdraws:          160        ---        ---        ---          0

gateway2_4 BGP        ---        start  2023-08-21    Active        Socket: Connection reset by peer
  BGP state:          Active
    Neighbor address: *
    Neighbor AS:      65300
    Local AS:         65300
    Connect delay:    2.639/5
    Last error:       Socket: Connection reset by peer
  Channel ipv4
    State:          DOWN
    Table:          master4
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    IGP IPv4 table: master4
  Channel ipv6
    State:          DOWN
    Table:          master6
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    IGP IPv6 table: master6

accessswitch3_4 BGP        ---        start  2023-08-21    Active        Socket: Connection reset by peer
  BGP state:          Active
    Neighbor address: *
    Neighbor AS:      65300
    Local AS:         65300
    Connect delay:    1.324/5
    Last error:       Socket: Connection reset by peer
  Channel ipv4
    State:          DOWN
    Table:          master4
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    IGP IPv4 table: master4
  Channel ipv6
    State:          DOWN
    Table:          master6
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    IGP IPv6 table: master6

pve2_4     BGP        ---        up     2023-08-30    Established   
  BGP state:          Established
    Neighbor address: *
    Neighbor port:    180
    Neighbor AS:      65300
    Local AS:         65300
    Neighbor ID:      *
    Local capabilities
      Multiprotocol
        AF announced: ipv4 ipv6
      Route refresh
      Graceful restart
      4-octet AS numbers
      Enhanced refresh
      Long-lived graceful restart
    Neighbor capabilities
      Multiprotocol
        AF announced: ipv4 ipv6
      Route refresh
      Graceful restart
      4-octet AS numbers
      Enhanced refresh
      Long-lived graceful restart
    Session:          internal multihop AS4
    Source address:   *
    Hold timer:       180.788/240
    Keepalive timer:  10.805/80
  Channel ipv4
    State:          UP
    Table:          master4
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         0 imported, 0 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:              0          0          0          0          0
      Import withdraws:            0          0        ---          0          0
      Export updates:            146          0        146        ---          0
      Export withdraws:           11        ---        ---        ---          0
    BGP Next hop:   *
    IGP IPv4 table: master4
  Channel ipv6
    State:          UP
    Table:          master6
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         1 imported, 1 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:              1          0          0          0          1
      Import withdraws:            0          0        ---          0          0
      Export updates:             14          5          8        ---          1
      Export withdraws:            3        ---        ---        ---          0
    BGP Next hop:   ::1
    IGP IPv6 table: master6

rr1_4      BGP        ---        up     2023-08-30    Established   
  BGP state:          Established
    Neighbor address: *
    Neighbor AS:      65300
    Local AS:         65300
    Neighbor ID:      *
    Local capabilities
      Multiprotocol
        AF announced: ipv4 ipv6
      Route refresh
      Graceful restart
      4-octet AS numbers
      Enhanced refresh
      Long-lived graceful restart
    Neighbor capabilities
      Multiprotocol
        AF announced: ipv4 ipv6
      Route refresh
      Extended next hop
        IPv6 nexthop: ipv4
      Extended message
      Graceful restart
        Restart time: 120
        AF supported: ipv4 ipv6
        AF preserved:
      4-octet AS numbers
      ADD-PATH
        RX: ipv4 ipv6
        TX: ipv4 ipv6
      Enhanced refresh
      Long-lived graceful restart
        LL stale time: 3600
        AF supported: ipv4 ipv6
        AF preserved:
    Session:          internal multihop AS4
    Source address:   *
    Hold timer:       21.651/30
    Keepalive timer:  0.921/10
  Channel ipv4
    State:          UP
    Table:          master4
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         0 imported, 0 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:            157          0        157          0          0
      Import withdraws:           64          0        ---        110          0
      Export updates:            255          0        255        ---          0
      Export withdraws:           68        ---        ---        ---          0
    BGP Next hop:   *
    IGP IPv4 table: master4
  Channel ipv6
    State:          UP
    Table:          master6
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         0 imported, 1 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:              2          0          0          0          3
      Import withdraws:          141          0        ---        140          2
      Export updates:             32          7         21        ---          4
      Export withdraws:           13        ---        ---        ---          0
    BGP Next hop:   ::1
    IGP IPv6 table: master6

rr2_4      BGP        ---        up     2023-08-24    Established   
  BGP state:          Established
    Neighbor address: *
    Neighbor AS:      65300
    Local AS:         65300
    Neighbor ID:      *
    Local capabilities
      Multiprotocol
        AF announced: ipv4 ipv6
      Route refresh
      Graceful restart
      4-octet AS numbers
      Enhanced refresh
      Long-lived graceful restart
    Neighbor capabilities
      Multiprotocol
        AF announced: ipv4 ipv6
      Route refresh
      Extended message
      Graceful restart
        Restart time: 120
        AF supported: ipv4 ipv6
        AF preserved:
      4-octet AS numbers
      ADD-PATH
        RX: ipv4 ipv6
        TX: ipv4 ipv6
      Enhanced refresh
      Long-lived graceful restart
        LL stale time: 900
        AF supported: ipv4 ipv6
        AF preserved: ipv4 ipv6
      Hostname: rr2
    Session:          internal multihop AS4
    Source address:   *
    Hold timer:       87.952/180
    Keepalive timer:  0.228/60
  Channel ipv4
    State:          UP
    Table:          master4
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         0 imported, 0 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:            166          0        166          0          0
      Import withdraws:          147          0        ---        194          0
      Export updates:            256          0        256        ---          0
      Export withdraws:           90        ---        ---        ---          0
    BGP Next hop:   *
    IGP IPv4 table: master4
  Channel ipv6
    State:          UP
    Table:          master6
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         0 imported, 1 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:              0          0          0          0          0
      Import withdraws:           73          0        ---         73          0
      Export updates:             32         12         19        ---          1
      Export withdraws:           15        ---        ---        ---          0
    BGP Next hop:   ::1
    IGP IPv6 table: master6

pve2_6     BGP        ---        up     2023-08-30    Established   
  BGP state:          Established
    Neighbor address: fd0a:372c:2572:0:7254:d2ff:feab:1fad
    Neighbor AS:      65300
    Local AS:         65300
    Neighbor ID:      *
    Local capabilities
      Multiprotocol
        AF announced: ipv4 ipv6
      Route refresh
      Graceful restart
      4-octet AS numbers
      Enhanced refresh
      Long-lived graceful restart
    Neighbor capabilities
      Multiprotocol
        AF announced: ipv4 ipv6
      Route refresh
      Graceful restart
      4-octet AS numbers
      Enhanced refresh
      Long-lived graceful restart
    Session:          internal multihop AS4
    Source address:   fd0a:372c:2572:0:7254:d2ff:feab:2059
    Hold timer:       210.402/240
    Keepalive timer:  39.953/80
  Channel ipv4
    State:          UP
    Table:          master4
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         0 imported, 0 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:              0          0          0          0          0
      Import withdraws:            0          0        ---          0          0
      Export updates:            149          0        149        ---          0
      Export withdraws:           11        ---        ---        ---          0
    BGP Next hop:   *
    IGP IPv4 table: master4
  Channel ipv6
    State:          UP
    Table:          master6
    Preference:     100
    Input filter:   (unnamed)
    Output filter:  (unnamed)
    Routes:         1 imported, 1 exported, 0 preferred
    Route change stats:     received   rejected   filtered    ignored   accepted
      Import updates:              1          0          0          0          1
      Import withdraws:            0          0        ---          0          0
      Export updates:             14          5          8        ---          1
      Export withdraws:            3        ---        ---        ---          0
    BGP Next hop:   fd0a:372c:2572:0:7254:d2ff:feab:2059
    IGP IPv6 table: master6  
  
SQL[select * from `cache` where `key` = ? limit 1 ["laravel_cache_runtimeCacheLibreNMS\\Util\\GitremoteUrl"] 0.44ms] 
  
Reporting disabled because LibreNMS is not from the official repository  
SQL[select * from `bgpPeers` where (`device_id` = ? and `bgpPeerRemoteAs` = ? and `bgpLocalAddr` = ? and `bgpPeerRemoteAddr` = ?) limit 1 [10,"65300","0.0.0.0","192.0.2.128"] 0.46ms] 
  
SQL[select * from `cache` where `key` = ? limit 1 ["laravel_cache_astext.65300"] 0.34ms] 
  
Error polling applications module for pve3.local. Exception: Failed to parse time string (2023-08-21 Active) at position 11 (A): The timezone could not be found in the database in /opt/librenms/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:88
Stack trace:
#0 /opt/librenms/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(88): DateTime->__construct()
#1 /opt/librenms/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(186): Carbon\Carbon->__construct()
#2 /opt/librenms/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(223): Carbon\Carbon::rawParse()
#3 /opt/librenms/includes/polling/applications/bird2.inc.php(182): Carbon\Carbon::parse()
#4 /opt/librenms/includes/polling/applications.inc.php(9): include('...')
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): {closure}()
#6 /opt/librenms/includes/polling/applications.inc.php(4): Illuminate\Support\Collection->each()
#7 /opt/librenms/includes/polling/functions.inc.php(352): include('...')
#8 /opt/librenms/poller.php(126): poll_device()
#9 {main}

Next Carbon\Exceptions\InvalidFormatException: Failed to parse time string (2023-08-21 Active) at position 11 (A): The timezone could not be found in the database in /opt/librenms/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:90
Stack trace:
#0 /opt/librenms/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(186): Carbon\Carbon->__construct()
#1 /opt/librenms/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(223): Carbon\Carbon::rawParse()
#2 /opt/librenms/includes/polling/applications/bird2.inc.php(182): Carbon\Carbon::parse()
#3 /opt/librenms/includes/polling/applications.inc.php(9): include('...')
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): {closure}()
#5 /opt/librenms/includes/polling/applications.inc.php(4): Illuminate\Support\Collection->each()
#6 /opt/librenms/includes/polling/functions.inc.php(352): include('...')
#7 /opt/librenms/poller.php(126): poll_device()
#8 {main}

Next Carbon\Exceptions\InvalidFormatException: Could not parse '2023-08-21 Active': Failed to parse time string (2023-08-21 Active) at position 11 (A): The timezone could not be found in the database in /opt/librenms/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:197
Stack trace:
#0 /opt/librenms/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(223): Carbon\Carbon::rawParse()
#1 /opt/librenms/includes/polling/applications/bird2.inc.php(182): Carbon\Carbon::parse()
#2 /opt/librenms/includes/polling/applications.inc.php(9): include('...')
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): {closure}()
#4 /opt/librenms/includes/polling/applications.inc.php(4): Illuminate\Support\Collection->each()
#5 /opt/librenms/includes/polling/functions.inc.php(352): include('...')
#6 /opt/librenms/poller.php(126): poll_device()
#7 {main}  
```
```

**Comment by netravnen** [comment]
@zappiehost Seems I need to specify `timeformat protocol xxxxxx` ([doc](https://bird.network.cz/?get_doc&v=20&f=bird-3.html)) in the `/etc/bird/bird.conf`. The **default** protocol timestamp `iso short ms` is only `YYYY-MM-DD`.

**Comment by netravnen** [comment]
Used `timeformat protocol "%F %T %Z";` in the bird configuration file. Now the bird2 app succeeds in parsing the output.

**Comment by zappiehost** [comment]
@netravnen 

Can you please try to add the following to the top of your BIRD config:

```
timeformat base iso long;
timeformat log iso long;
timeformat protocol iso long;
timeformat route iso long;
```

And see how it goes

**Comment by zappiehost** [comment]
Also would you be able to create a PR to update the doc markdown to add the above snipper instructions, something I think I overlooked making sure all BIRD output dates are set in `long` format with hours/mins/sec as well as the dates (example https://github.com/librenms/librenms/pull/14466/files#diff-130a75806df530067f1023b43fbec546c6f3b13bc70ba8adfa4ae06bf57a2299)

**Comment by netravnen** [comment]
> @netravnen
> 
> Can you please try to add the following to the top of your BIRD config:
> 
> ```
> timeformat base iso long;
> timeformat log iso long;
> timeformat protocol iso long;
> timeformat route iso long;
> ```

I went with this, including `%z` for timezone information. As I prefer to have host running UTC time. But often overlook this at setup, and ending up with some hosts running local timezone. Others running UTC. (Still need to configure alert rules for this). The `iso long` format does not contain timezone information.

```
timeformat base "%F %T %z";
timeformat log "%F %T %z";
timeformat protocol "%F %T %z";
timeformat route "%F %T %z";
```

Poller runs just fine. :)

**Comment by netravnen** [comment]
@zappiehost See https://github.com/librenms/librenms/pull/15292
