### ISSUE TITLE
Application rrdcached seems broken

### ISSUE THREAD

**Issue by frank42hh** [librenms/librenms#15299]
### The problem

I tried to activate the rrdcached application on a host. The client side works fine:

```
root@hostname:/etc/snmp# sudo -u Debian-snmp ./rrdcached
<<<rrdcached>>>
9 Statistics follow
QueueLength: 0
UpdatesReceived: 3795101
FlushesReceived: 0
UpdatesWritten: 399873
DataSetsWritten: 3611204
TreeNodesNumber: 11521
TreeDepth: 16
JournalBytes: 399786989
JournalRotate: 24
```

But LibreNMS throws the following error:
```
Error polling applications module for hostname.domain.tld. TypeError: Unsupported operand types: string + int in /opt/librenms/includes/polling/applications/rrdcached.inc.php:65
Stack trace:
#0 /opt/librenms/includes/polling/applications.inc.php(9): include()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): {closure}()
#2 /opt/librenms/includes/polling/applications.inc.php(14): Illuminate\Support\Collection->each()
#3 /opt/librenms/includes/polling/functions.inc.php(352): include('...')
#4 /opt/librenms/poller.php(126): poll_device()
#5 {main}
Unsupported operand types: string + int {"exception":"[object] (TypeError(code: 0): Unsupported operand types: string + int at /opt/librenms/includes/polling/applications/rrdcached.inc.php:65)"}
```

Line 65 of `rrdcached.inc.php` says `$max = $tmp_max[0] + 1;` and according to the error message it sounds like it tries to make a string out of it. Perhaps the top line that says `9 Statistics follow`, but I don't speak python, though.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.8.2-31-gb51ae39e7 (2023-09-07T18:28:35+02:00)
DB Schema | 2023_08_30_105156_add_applications_soft_deleted (259)
PHP       | 8.1.23
Python    | 3.9.2
Database  | MariaDB 10.5.19-MariaDB-0+deb11u2
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.6.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No active python wrapper pollers found
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### Anything in the logs that might be useful for us?

```txt
logs included in problem description above
```

**Comment by murrant** [comment]
Looks like LibreNMS couldn't read input from your rrdcached server. 
I've sent a bugfix for the error you posted, but I suspect it won't fix your issue.
