### ISSUE TITLE
Stopped drawing graphs.

### ISSUE THREAD

**Issue by kometchtech** [librenms/librenms#15403]
### The problem

When the update was made on October 6, 2023, we confirmed that the graphs stopped drawing for some items.
We have confirmed that the system was working up to the previous day's version, as we are currently running daily updates.

![image](https://github.com/librenms/librenms/assets/5137077/c8c62756-2292-42a3-8f88-143a3d210887)

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1-56-g908aef659 (2023-10-06T13:04:04+09:00)
DB Schema | 2023_04_26_185850_change_vminfo_vmw_vm_guest_o_s_nullable (260)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.6.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Anything in the logs that might be useful for us?

```txt
Error polling unix-agent module for example.jp. PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'arch' cannot be null in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:580
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(580): PDOStatement->execute()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(788): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\Database\Connection->runQueryCallback()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->run()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\Database\Connection->statement()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3383): Illuminate\Database\Query\Processors\Processor->processInsertGetId()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1925): Illuminate\Database\Query\Builder->insertGetId()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1333): Illuminate\Database\Eloquent\Builder->__call()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1298): Illuminate\Database\Eloquent\Model->insertAndSetId()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1137): Illuminate\Database\Eloquent\Model->performInsert()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(270): Illuminate\Database\Eloquent\Model->save()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(295): Illuminate\Database\Eloquent\Relations\HasOneOrMany->save()
#13 /opt/librenms/includes/polling/unix-agent/packages.inc.php(71): Illuminate\Database\Eloquent\Relations\HasOneOrMany->saveMany()
#14 /opt/librenms/includes/polling/unix-agent.inc.php(95): include('...')
#15 /opt/librenms/LibreNMS/Modules/LegacyModule.php(121): include('...')
#16 /opt/librenms/LibreNMS/Poller.php(191): LibreNMS\Modules\LegacyModule->poll()
#17 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#18 /opt/librenms/app/Console/Commands/DevicePoll.php(44): LibreNMS\Poller->poll()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#25 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run()
#27 /opt/librenms/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#28 /opt/librenms/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#29 /opt/librenms/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#30 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#31 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#32 /opt/librenms/lnms(40): App\Console\Kernel->handle()
#33 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'arch' cannot be null (Connection: mysql, SQL: insert into `packages` (`manager`, `name`, `arch`, `version`, `build`, `size`, `status`, `device_id`) values (deb, 0, ?, ?, , 0, 1, 32)) in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\Database\Connection->runQueryCallback()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->run()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\Database\Connection->statement()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3383): Illuminate\Database\Query\Processors\Processor->processInsertGetId()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1925): Illuminate\Database\Query\Builder->insertGetId()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1333): Illuminate\Database\Eloquent\Builder->__call()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1298): Illuminate\Database\Eloquent\Model->insertAndSetId()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1137): Illuminate\Database\Eloquent\Model->performInsert()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(270): Illuminate\Database\Eloquent\Model->save()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(295): Illuminate\Database\Eloquent\Relations\HasOneOrMany->save()
#11 /opt/librenms/includes/polling/unix-agent/packages.inc.php(71): Illuminate\Database\Eloquent\Relations\HasOneOrMany->saveMany()
#12 /opt/librenms/includes/polling/unix-agent.inc.php(95): include('...')
#13 /opt/librenms/LibreNMS/Modules/LegacyModule.php(121): include('...')
#14 /opt/librenms/LibreNMS/Poller.php(191): LibreNMS\Modules\LegacyModule->poll()
#15 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#16 /opt/librenms/app/Console/Commands/DevicePoll.php(44): LibreNMS\Poller->poll()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#23 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run()
#25 /opt/librenms/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#26 /opt/librenms/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#27 /opt/librenms/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#28 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#29 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#30 /opt/librenms/lnms(40): App\Console\Kernel->handle()
#31 {main}  
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'arch' cannot be null (Connection: mysql, SQL: insert into `packages` (`manager`, `name`, `arch`, `version`, `build`, `size`, `status`, `device_id`) values (deb, 0, ?, ?, , 0, 1, 32)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'arch' cannot be null (Connection: mysql, SQL: insert into `packages` (`manager`, `name`, `arch`, `version`, `build`, `size`, `status`, `device_id`) values (deb, 0, ?, ?, , 0, 1, 32)) at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795)
[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'arch' cannot be null at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:580)"} 
Error polling unix-agent module for ogawamachi-pve.cskk.jp. Error: Call to undefined function rewrite_generic_hardware() in /opt/librenms/includes/polling/unix-agent.inc.php:194
Stack trace:
#0 /opt/librenms/LibreNMS/Modules/LegacyModule.php(121): include()
#1 /opt/librenms/LibreNMS/Poller.php(191): LibreNMS\Modules\LegacyModule->poll()
#2 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#3 /opt/librenms/app/Console/Commands/DevicePoll.php(44): LibreNMS\Poller->poll()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#10 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run()
#12 /opt/librenms/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#13 /opt/librenms/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#14 /opt/librenms/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#16 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#17 /opt/librenms/lnms(40): App\Console\Kernel->handle()
#18 {main}  
Call to undefined function rewrite_generic_hardware() {"exception":"[object] (Error(code: 0): Call to undefined function rewrite_generic_hardware() at /opt/librenms/includes/polling/unix-agent.inc.php:194)"} 
Error polling unix-agent module for example.jp. Error: Call to undefined function rewrite_generic_hardware() in /opt/librenms/includes/polling/unix-agent.inc.php:194
Stack trace:
#0 /opt/librenms/LibreNMS/Modules/LegacyModule.php(121): include()
#1 /opt/librenms/LibreNMS/Poller.php(191): LibreNMS\Modules\LegacyModule->poll()
#2 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#3 /opt/librenms/app/Console/Commands/DevicePoll.php(44): LibreNMS\Poller->poll()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#10 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run()
#12 /opt/librenms/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#13 /opt/librenms/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#14 /opt/librenms/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#16 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#17 /opt/librenms/lnms(40): App\Console\Kernel->handle()
#18 {main}  
Call to undefined function rewrite_generic_hardware() {"exception":"[object] (Error(code: 0): Call to undefined function rewrite_generic_hardware() at /opt/librenms/includes/polling/unix-agent.inc.php:194)"} 
```
```

**Comment by murrant** [comment]
You should be able to run ./daily.sh to resolve this issue.

**Comment by kometchtech** [comment]
@murrant 

I tried updating the software, but the rendering did not recover.
![image](https://github.com/librenms/librenms/assets/5137077/730c59cc-99ef-4ec3-9dce-afd9b8cc7570)

```
$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1-61-ge53436b6a (2023-10-07T10:37:23+09:00)
DB Schema | 2023_04_26_185850_change_vminfo_vmw_vm_guest_o_s_nullable (260)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.6.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

[librenms.log](https://github.com/librenms/librenms/files/12837775/librenms.log)
