### ISSUE TITLE
VRP polling: 'numasoclients' cannot be null

### ISSUE THREAD

**Issue by an-mc** [librenms/librenms#15441]
### The problem

Fix in https://github.com/librenms/librenms/commit/b7ab5be3470d857c69ebf8e6e9a1cdafe9cc0dfe seems to be missing values when trying to save to the database.

Included stacktrace in details.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1-78-g2f33421ae (2023-10-11T23:49:16+00:00)
DB Schema | 2023_10_07_170735_increase_processes_cputime_length (261)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.6.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### Anything in the logs that might be useful for us?

```txt
Error polling os module for a.b.c.d. PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'numasoclients' cannot be null in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:605
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(605): PDOStatement->execute()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(788): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\Database\Connection->runQueryCallback()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(612): Illuminate\Database\Connection->run()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): Illuminate\Database\Connection->affectingStatement()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3418): Illuminate\Database\Connection->update()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1042): Illuminate\Database\Query\Builder->update()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1213): Illuminate\Database\Eloquent\Builder->update()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1130): Illuminate\Database\Eloquent\Model->performUpdate()
#9 /opt/librenms/LibreNMS/DB/SyncsModels.php(52): Illuminate\Database\Eloquent\Model->save()
#10 /opt/librenms/LibreNMS/OS/Vrp.php(253): LibreNMS\OS\Vrp->syncModels()
#11 /opt/librenms/LibreNMS/Modules/Os.php(80): LibreNMS\OS\Vrp->pollOS()
#12 /opt/librenms/LibreNMS/Poller.php(191): LibreNMS\Modules\Os->poll()
#13 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#14 /opt/librenms/app/Console/Commands/DevicePoll.php(44): LibreNMS\Poller->poll()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#21 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run()
#23 /opt/librenms/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#24 /opt/librenms/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#25 /opt/librenms/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#27 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#28 /opt/librenms/lnms(40): App\Console\Kernel->handle()
#29 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'numasoclients' cannot be null (Connection: mysql, SQL: update `access_points` set `channel` = 6, `radioutil` = 9, `numasoclients` = ?
, `interference` = 5 where `accesspoint_id` = 1) in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\Database\Connection->runQueryCallback()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(612): Illuminate\Database\Connection->run()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): Illuminate\Database\Connection->affectingStatement()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3418): Illuminate\Database\Connection->update()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1042): Illuminate\Database\Query\Builder->update()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1213): Illuminate\Database\Eloquent\Builder->update()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1130): Illuminate\Database\Eloquent\Model->performUpdate()
#7 /opt/librenms/LibreNMS/DB/SyncsModels.php(52): Illuminate\Database\Eloquent\Model->save()
#8 /opt/librenms/LibreNMS/OS/Vrp.php(253): LibreNMS\OS\Vrp->syncModels()
#9 /opt/librenms/LibreNMS/Modules/Os.php(80): LibreNMS\OS\Vrp->pollOS()
#10 /opt/librenms/LibreNMS/Poller.php(191): LibreNMS\Modules\Os->poll()
#11 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#12 /opt/librenms/app/Console/Commands/DevicePoll.php(44): LibreNMS\Poller->poll()
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#19 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run()
#21 /opt/librenms/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#22 /opt/librenms/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#23 /opt/librenms/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#25 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#26 /opt/librenms/lnms(40): App\Console\Kernel->handle()
#27 {main}  
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'numasoclients' cannot be null (Connection: mysql, SQL: update `access_points` set `channel` = 6, `radioutil` = 9, `numasoclients` = ?, `interference` = 5 where `accesspoint_id` = 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'numasoclients' cannot be null (Connection: mysql, SQL: update `access_points` set `channel` = 6, `radioutil` = 9, `numasoclients` = ?, `interference` = 5 where `accesspoint_id` = 1) at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795)
[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'numasoclients' cannot be null at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:605)"}
```

**Comment by murrant** [comment]
Thanks @an-mc as mentioned I have no way to test.  Can you test #15450 to see if it is working?

**Comment by murrant** [comment]
Otherwise, running `./scripts/collect-snmp-data.php` on your device and uploading the snmprec could help me out.  Make sure to replace any data you don't want on the public internet.
