### ISSUE TITLE
SQLSTATE Numeric value out of range

### ISSUE THREAD

**Issue by Bierchermuesli** [librenms/librenms#15443]
### The problem

hi

I have some issues with large or infinite numbers. I guess the issue could be older but was not noticed yet or could be related to some third party libraries or frameworks. 
I noticed the error on `bgpPeers_cbgp` (cbgpPeerPrefixAdminLimit) or `ports_statistics` (big counters) Table

```
librenms@poller3:~$ lnms device:poll -m bgp-peers 1924 -vv
<snip>
 
SQL[select `device_id` from `devices` where `device_id` = ? ["1924"] 0.76ms] 
  
SQL[select * from `devices` where `device_id` = ? limit 1 [1924] 0.75ms] 
  
Hostname:  01.p.ull.ch.lab  (cisco)
ID:        1924
OS:        iosxr
IP:        203.0.113.139

.... <snip>

SNMP['/usr/bin/snmpget' '-v1' '-c' 'COMMUNITY' '-OQUs' '-m' 'CISCO-BGP4-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:HOSTNAME:161' 'cbgpPeer2AcceptedPrefixes.1.4.203.0.113.207.1.1' 'cbgpPeer2DeniedPrefixes.1.4.203.0.113.207.1.1' 'cbgpPeer2PrefixAdminLimit.1.4.203.0.113.207.1.1' 'cbgpPeer2PrefixThreshold.1.4.203.0.113.207.1.1' 'cbgpPeer2PrefixClearThreshold.1.4.203.0.113.207.1.1' 'cbgpPeer2AdvertisedPrefixes.1.4.203.0.113.207.1.1' 'cbgpPeer2SuppressedPrefixes.1.4.203.0.113.207.1.1' 'cbgpPeer2WithdrawnPrefixes.1.4.203.0.113.207.1.1']
cbgpPeer2AcceptedPrefixes.ipv4."*".ipv4.unicast = 0
cbgpPeer2DeniedPrefixes.ipv4."*".ipv4.unicast = 0
cbgpPeer2PrefixAdminLimit.ipv4."*".ipv4.unicast = 4294967295
cbgpPeer2PrefixThreshold.ipv4."*".ipv4.unicast = 75
cbgpPeer2PrefixClearThreshold.ipv4."*".ipv4.unicast = 75
cbgpPeer2AdvertisedPrefixes.ipv4."*".ipv4.unicast = 0
cbgpPeer2SuppressedPrefixes.ipv4."*".ipv4.unicast = 0
cbgpPeer2WithdrawnPrefixes.ipv4."*".ipv4.unicast = 0  
  
array (
  'cbgpPeerAcceptedPrefixes' => '0',
  'cbgpPeerDeniedPrefixes' => '0',
  'cbgpPeerPrefixAdminLimit' => '4294967295',
  'cbgpPeerPrefixThreshold' => '75',
  'cbgpPeerPrefixClearThreshold' => '75',
  'cbgpPeerAdvertisedPrefixes' => '0',
  'cbgpPeerSuppressedPrefixes' => '0',
  'cbgpPeerWithdrawnPrefixes' => '0',
)  
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'PrefixAdminLimit' at row 1 (Connection: mysql, SQL: UPDATE `bgpPeers_cbgp` set `PrefixAdminLimit`=4294967295 WHERE `device_id` = 1924 AND bgpPeerIdentifier = 203.0.113.207 AND afi = ipv4 AND safi = unicast) (Connection: dbFacile, SQL: UPDATE `bgpPeers_cbgp` set `PrefixAdminLimit`=4294967295 WHERE `device_id` = 1924 AND bgpPeerIdentifier = 203.0.113.207 AND afi = ipv4 AND safi = unicast)#0 /opt/librenms/includes/polling/bgp-peers.inc.php(766): dbUpdate()

```

I run it by accident with the deprecated poller.php command: 

```
librenms@poller3:~$ php poller.php -h 1924 -m bgp-peers -d
Warning: poller.php is deprecated! Use lnms device:poll instead.
<snip>
SNMP['/usr/bin/snmpget' '-v1' '-c' 'COMMUNITY' '-OQUs' '-m' 'CISCO-BGP4-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:HOSTNAME:161' 'cbgpPeer2AcceptedPrefixes.1.4.203.0.113.207.1.1' 'cbgpPeer2DeniedPrefixes.1.4.203.0.113.207.1.1' 'cbgpPeer2PrefixAdminLimit.1.4.203.0.113.207.1.1' 'cbgpPeer2PrefixThreshold.1.4.203.0.113.207.1.1' 'cbgpPeer2PrefixClearThreshold.1.4.203.0.113.207.1.1' 'cbgpPeer2AdvertisedPrefixes.1.4.203.0.113.207.1.1' 'cbgpPeer2SuppressedPrefixes.1.4.203.0.113.207.1.1' 'cbgpPeer2WithdrawnPrefixes.1.4.203.0.113.207.1.1']
cbgpPeer2AcceptedPrefixes.ipv4."*".ipv4.unicast = 0
cbgpPeer2DeniedPrefixes.ipv4."*".ipv4.unicast = 0
cbgpPeer2PrefixAdminLimit.ipv4."*".ipv4.unicast = 4294967295
cbgpPeer2PrefixThreshold.ipv4."*".ipv4.unicast = 75
cbgpPeer2PrefixClearThreshold.ipv4."*".ipv4.unicast = 75
cbgpPeer2AdvertisedPrefixes.ipv4."*".ipv4.unicast = 0
cbgpPeer2SuppressedPrefixes.ipv4."*".ipv4.unicast = 0
cbgpPeer2WithdrawnPrefixes.ipv4."*".ipv4.unicast = 0  
  
array (
  'cbgpPeerAcceptedPrefixes' => '0',
  'cbgpPeerDeniedPrefixes' => '0',
  'cbgpPeerPrefixAdminLimit' => '4294967295',
  'cbgpPeerPrefixThreshold' => '75',
  'cbgpPeerPrefixClearThreshold' => '75',
  'cbgpPeerAdvertisedPrefixes' => '0',
  'cbgpPeerSuppressedPrefixes' => '0',
  'cbgpPeerWithdrawnPrefixes' => '0',
)  
SQL[UPDATE `bgpPeers_cbgp` set `PrefixAdminLimit`=? WHERE `device_id` = ? AND bgpPeerIdentifier = ? AND afi = ? AND safi = ? ["4294967295",1924,"203.0.113.207","ipv4","unicast"] 0.54ms] 

```
It runs with poller.php without errors - but the numbers will be cut to 32 bit int. 2147483647 is written to the database.

Where should the numbers be normalized?
If somebody can give me a hint where to dig further, I would very appreciate it.  Thanks

Side note: With poller-wraper.py. no error were reported. although librenms.log is full of it. I acually use the dispatcher service. 
```
./poller-wrapper.py -m bgp-peers 4
2023-10-12 13:36:56,872 :: INFO :: starting the poller check at 2023-10-12 13:36:56 with 1 threads for 1 devices
2023-10-12 13:36:59,323 :: INFO :: worker Thread-2 finished device 1924 in 2 seconds
2023-10-12 13:36:59,323 :: INFO :: poller-wrapper checked 1 devices in 2 seconds with 1 workers with 0 errors
```

### Output of ./validate.php

```txt
librenms@poller3:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1-80-g0540c56d0 (2023-10-12T09:24:27+02:00)
DB Schema | 2023_10_07_231037_application_metrics_add_primary_key (262)
PHP       | 8.1.23
Python    | 3.9.2
Database  | MariaDB 10.5.19-MariaDB-0+deb11u2
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.6.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No active python wrapper pollers found
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached


Same issue with PHP 8.2.11 !
```

**Comment by murrant** [comment]
4294967295 is the max value for an unsigned 32 bit integer.  It seems the column is signed, so only accepts half that.

4294967295 seems too high to be a reasonable limit. There are two ways we could fix it:
1. Change the database to unsigned and store as is.
2. If the value is int max, normalize it to 0 (which usually signifies unlimited.

**Comment by Bierchermuesli** [comment]
indeed.
for some cases would a sanity check make sense (e.g. for cbgpPeerPrefixAdminLimit in bgp-peers.inc.php) but I guess it might be a general  issue which would affect any general update-function. e.g. `ifInBroadcastPkts` which is bigint(20) see below

What differ from the poller.php or why it is 'catched' there? 
were there some framework/logging changes or why did I missed them in the last few months? can't believe we are the only one with this issue. 

thanks for your feedback

```
QLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'ifInBroadcastPkts' at row 1 (Connection: mysql, SQL: UPDATE `p
orts_statistics` set `ifInNUcastPkts`=0,`ifInNUcastPkts_prev`=0,`ifInNUcastPkts_rate`=0,`ifInNUcastPkts_delta`=0,`ifOutNUcastPkts`=0,`ifOutNUca
stPkts_prev`=0,`ifOutNUcastPkts_rate`=0,`ifOutNUcastPkts_delta`=0,`ifInDiscards`=0,`ifInDiscards_prev`=0,`ifInDiscards_rate`=0,`ifInDiscards_de
lta`=0,`ifOutDiscards`=0,`ifOutDiscards_prev`=0,`ifOutDiscards_rate`=0,`ifOutDiscards_delta`=0,`ifInUnknownProtos`=0,`ifInUnknownProtos_prev`=0
,`ifInUnknownProtos_rate`=0,`ifInUnknownProtos_delta`=0,`ifInBroadcastPkts`=18446744073685553715,`ifInBroadcastPkts_prev`=9223372036854775807,`
ifInBroadcastPkts_rate`=0,`ifInBroadcastPkts_delta`=0,`ifOutBroadcastPkts`=18446744073707912909,`ifOutBroadcastPkts_prev`=9223372036854775807,`
ifOutBroadcastPkts_rate`=0,`ifOutBroadcastPkts_delta`=0,`ifInMulticastPkts`=37361943,`ifInMulticastPkts_prev`=37355109,`ifInMulticastPkts_rate`
=22.85618729097,`ifInMulticastPkts_delta`=6834,`ifOutMulticastPkts`=2723333,`ifOutMulticastPkts_prev`=2722966,`ifOutMulticastPkts_rate`=1.22742
47491639,`ifOutMulticastPkts_delta`=367 WHERE `port_id` = 90832) (Connection: dbFacile, SQL: UPDATE `ports_statistics` set `ifInNUcastPkts`=0,`
ifInNUcastPkts_prev`=0,`ifInNUcastPkts_rate`=0,`ifInNUcastPkts_delta`=0,`ifOutNUcastPkts`=0,`ifOutNUcastPkts_prev`=0,`ifOutNUcastPkts_rate`=0,`
ifOutNUcastPkts_delta`=0,`ifInDiscards`=0,`ifInDiscards_prev`=0,`ifInDiscards_rate`=0,`ifInDiscards_delta`=0,`ifOutDiscards`=0,`ifOutDiscards_prev`=0,`ifOutDiscards_rate`=0,`ifOutDiscards_delta`=0,`ifInUnknownProtos`=0,`ifInUnknownProtos_prev`=0,`ifInUnknownProtos_rate`=0,`ifInUnknownProtos_delta`=0,`ifInBroadcastPkts`=18446744073685553715,`ifInBroadcastPkts_prev`=9223372036854775807,`ifInBroadcastPkts_rate`=0,`ifInBroadcastPkts_delta`=0,`ifOutBroadcastPkts`=18446744073707912909,`ifOutBroadcastPkts_prev`=9223372036854775807,`ifOutBroadcastPkts_rate`=0,`ifOutBroadcastPkts_delta`=0,`ifInMulticastPkts`=37361943,`ifInMulticastPkts_prev`=37355109,`ifInMulticastPkts_rate`=22.85618729097,`ifInMulticastPkts_delta`=6834,`ifOutMulticastPkts`=2723333,`ifOutMulticastPkts_prev`=2722966,`ifOutMulticastPkts_rate`=1.2274247491639,`ifOutMulticastPkts_delta`=367 WHERE `port_id` = 90832)#0 /opt/librenms/includes/polling/ports.inc.php(938): dbUpdate()
``` a stupid old ios router hits this limit.

**Comment by murrant** [comment]
New code is more strict about errors.  There errors were there, but invisible before.

**Comment by Bierchermuesli** [comment]
Yay, thanks a lot! I didn't mean for it to have to be fixed by you. I really appreciate it. 

Looks good, although i get some negative values on some  _pref calculations: 

```

SNMP['/usr/bin/snmpget' '-v3' '-l' 'authPriv' '-n' "" '-a' 'SHA' '-A' 'PASSWORD' '-u' 'USER' '-x' 'AES' '-X' 'PASSWORD' '-OQUs' '-m' 'CISCO-BGP4-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:HOSTNAME:161' 'cbgpPeer2AcceptedPrefixes.1.4.203.0.113.88.1.128' 'cbgpPeer2DeniedPrefixes.1.4.203.0.113.88.1.128' 'cbgpPeer2PrefixAdminLimit.1.4.203.0.113.88.1.128' 'cbgpPeer2PrefixThreshold.1.4.203.0.113.88.1.128' 'cbgpPeer2PrefixClearThreshold.1.4.203.0.113.88.1.128' 'cbgpPeer2AdvertisedPrefixes.1.4.203.0.113.88.1.128' 'cbgpPeer2SuppressedPrefixes.1.4.203.0.113.88.1.128' 'cbgpPeer2WithdrawnPrefixes.1.4.203.0.113.88.1.128']
cbgpPeer2AcceptedPrefixes.ipv4."*".ipv4.vpn = 2398
cbgpPeer2DeniedPrefixes.ipv4."*".ipv4.vpn = 76173
cbgpPeer2PrefixAdminLimit.ipv4."*".ipv4.vpn = 4294967295
cbgpPeer2PrefixThreshold.ipv4."*".ipv4.vpn = 75
cbgpPeer2PrefixClearThreshold.ipv4."*".ipv4.vpn = 75
cbgpPeer2AdvertisedPrefixes.ipv4."*".ipv4.vpn = 955
cbgpPeer2SuppressedPrefixes.ipv4."*".ipv4.vpn = 0
cbgpPeer2WithdrawnPrefixes.ipv4."*".ipv4.vpn = 816  
  
array (
  'cbgpPeerAcceptedPrefixes' => '2398',
  'cbgpPeerDeniedPrefixes' => '76173',
  'cbgpPeerPrefixAdminLimit' => '4294967295',
  'cbgpPeerPrefixThreshold' => '75',
  'cbgpPeerPrefixClearThreshold' => '75',
  'cbgpPeerAdvertisedPrefixes' => '955',
  'cbgpPeerSuppressedPrefixes' => '0',
  'cbgpPeerWithdrawnPrefixes' => '816',
)  
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'AcceptedPrefixes_delta' at row 1 (Connection: mysql, SQL: UPDATE `bgpPeers_cbgp` set `AcceptedPrefixes`=2398,`AcceptedPrefixes_delta`=-14,`AcceptedPrefixes_prev`=2412 WHERE `device_id` = 813 AND bgpPeerIdentifier = 203.0.113.88 AND afi = ipv6 AND safi = vpn) (Connection: dbFacile, SQL: UPDATE `bgpPeers_cbgp` set `AcceptedPrefixes`=2398,`AcceptedPrefixes_delta`=-14,`AcceptedPrefixes_prev`=2412 WHERE `device_id` = 813 AND bgpPeerIdentifier = 203.0.113.88 AND afi = ipv6 AND safi = vpn)#0 /opt/librenms/includes/polling/bgp-peers.inc.php(766): dbUpdate()
#1 /opt/librenms/LibreNMS/Modules/LegacyModule.php(121): include('...')
#2 /opt/librenms/LibreNMS/Poller.php(191): LibreNMS\Modules\LegacyModule->poll()
#3 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#4 /opt/librenms/app/Console/Commands/DevicePoll.php(44): LibreNMS\Poller->poll()

```
Data base says:
```
select afi,AcceptedPrefixes,AcceptedPrefixes_delta,AcceptedPrefixes_prev,PrefixAdminLimit from bgpPeers_cbgp WHERE `device_id` = 813 AND bgpPeerIdentifier = "203.0.113.88" AND afi = "ipv6" AND safi = "vpn"

+------+------------------+------------------------+-----------------------+------------------+
| afi  | AcceptedPrefixes | AcceptedPrefixes_delta | AcceptedPrefixes_prev | PrefixAdminLimit |
+------+------------------+------------------------+-----------------------+------------------+
| ipv6 |             2412 |                      0 |                  2398 |       4294967295 |
+------+------------------+------------------------+-----------------------+------------------+

```

**Comment by murrant** [comment]
Oops, delta fields should have been excluded...

**Comment by Bierchermuesli** [comment]
Thanks alot! it is now fixed with https://github.com/librenms/librenms/pull/15458
