### ISSUE TITLE
Error polling ospf module. After update from 23.9.0 > 23.10.0 

### ISSUE THREAD

**Issue by Cormoran96** [librenms/librenms#15520]
### The problem

Hello, 

after the update from 23.9 to 23.10 I have the message "Error polling ospf module. Check log file for more details.".

On arista devices.

In the logs I have: 
```
Error polling ospf module for arista.example.net. PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'ospfAsBdrRtrCount' at row 1 in /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:605
Stack trace:
#0 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(605): PDOStatement->execute()
#1 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(788): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\Database\Connection->runQueryCallback()
#3 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(612): Illuminate\Database\Connection->run()
#4 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): Illuminate\Database\Connection->affectingStatement()
#5 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3418): Illuminate\Database\Connection->update()
#6 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1042): Illuminate\Database\Query\Builder->update()
#7 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1213): Illuminate\Database\Eloquent\Builder->update()
#8 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1130): Illuminate\Database\Eloquent\Model->performUpdate()
#9 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(584): Illuminate\Database\Eloquent\Model->save()
#10 /home/librenms/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}()
#11 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(585): tap()
#12 /home/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->updateOrCreate()
#13 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2333): Illuminate\Database\Eloquent\Model->forwardCallTo()
#14 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2345): Illuminate\Database\Eloquent\Model->__call()
#15 /home/librenms/LibreNMS/Modules/Ospf.php(121): Illuminate\Database\Eloquent\Model::__callStatic()
#16 [internal function]: LibreNMS\Modules\Ospf->LibreNMS\Modules\{closure}()
#17 /home/librenms/LibreNMS/Data/Source/SnmpResponse.php(234): call_user_func()
#18 [internal function]: LibreNMS\Data\Source\SnmpResponse->LibreNMS\Data\Source\{closure}()
#19 /home/librenms/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map()
#20 /home/librenms/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\Support\Arr::map()
#21 /home/librenms/LibreNMS/Data/Source/SnmpResponse.php(235): Illuminate\Support\Collection->map()
#22 /home/librenms/LibreNMS/Modules/Ospf.php(125): LibreNMS\Data\Source\SnmpResponse->mapTable()
#23 /home/librenms/LibreNMS/Poller.php(178): LibreNMS\Modules\Ospf->poll()
#24 /home/librenms/LibreNMS/Poller.php(105): LibreNMS\Poller->pollModules()
#25 /home/librenms/app/Console/Commands/DevicePoll.php(44): LibreNMS\Poller->poll()
#26 /home/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#27 /home/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#28 /home/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#29 /home/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#30 /home/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#31 /home/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#32 /home/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#33 /home/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run()
#34 /home/librenms/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#35 /home/librenms/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#36 /home/librenms/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#37 /home/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#38 /home/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#39 /home/librenms/lnms(40): App\Console\Kernel->handle()
#40 {main}

Next Illuminate\Database\QueryException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'ospfAsBdrRtrCount' at row 1 (Connection: mysql, SQL: update `ospf_areas` set `ospfAsBdrRtrCount` = 4294967294, `ospfAreaLsaCksumSum` = 328314 where `id` = 8634) in /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795
Stack trace:
#0 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\Database\Connection->runQueryCallback()
#1 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(612): Illuminate\Database\Connection->run()
#2 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): Illuminate\Database\Connection->affectingStatement()
#3 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3418): Illuminate\Database\Connection->update()
#4 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1042): Illuminate\Database\Query\Builder->update()
#5 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1213): Illuminate\Database\Eloquent\Builder->update()
#6 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1130): Illuminate\Database\Eloquent\Model->performUpdate()
#7 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(584): Illuminate\Database\Eloquent\Model->save()
#8 /home/librenms/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}()
#9 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(585): tap()
#10 /home/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->updateOrCreate()
#11 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2333): Illuminate\Database\Eloquent\Model->forwardCallTo()
#12 /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2345): Illuminate\Database\Eloquent\Model->__call()
#13 /home/librenms/LibreNMS/Modules/Ospf.php(121): Illuminate\Database\Eloquent\Model::__callStatic()
#14 [internal function]: LibreNMS\Modules\Ospf->LibreNMS\Modules\{closure}()
#15 /home/librenms/LibreNMS/Data/Source/SnmpResponse.php(234): call_user_func()
#16 [internal function]: LibreNMS\Data\Source\SnmpResponse->LibreNMS\Data\Source\{closure}()
#17 /home/librenms/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map()
#18 /home/librenms/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\Support\Arr::map()
#19 /home/librenms/LibreNMS/Data/Source/SnmpResponse.php(235): Illuminate\Support\Collection->map()
#20 /home/librenms/LibreNMS/Modules/Ospf.php(125): LibreNMS\Data\Source\SnmpResponse->mapTable()
#21 /home/librenms/LibreNMS/Poller.php(178): LibreNMS\Modules\Ospf->poll()
#22 /home/librenms/LibreNMS/Poller.php(105): LibreNMS\Poller->pollModules()
#23 /home/librenms/app/Console/Commands/DevicePoll.php(44): LibreNMS\Poller->poll()
#24 /home/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#25 /home/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /home/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#27 /home/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#28 /home/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#29 /home/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#30 /home/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#31 /home/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run()
#32 /home/librenms/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#33 /home/librenms/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#34 /home/librenms/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#35 /home/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#36 /home/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#37 /home/librenms/lnms(40): App\Console\Kernel->handle()
#38 {main}  
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'ospfAsBdrRtrCount' at row 1 (Connection: mysql, SQL: update `ospf_areas` set `ospfAsBdrRtrCount` = 4294967294, `ospfAreaLsaCksumSum` = 328314 where `id` = 8634) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'ospfAsBdrRtrCount' at row 1 (Connection: mysql, SQL: update `ospf_areas` set `ospfAsBdrRtrCount` = 4294967294, `ospfAreaLsaCksumSum` = 328314 where `id` = 8634) at /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795)
[previous exception] [object] (PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'ospfAsBdrRtrCount' at row 1 at /home/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:605)"} 
```

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.10.0 (2023-10-27T05:47:36+02:00)
DB Schema | 2023_10_20_075853_cisco_asa_add_default_limits (268)
PHP       | 8.1.22
Python    | 3.9.2
Database  | MariaDB 10.5.19-MariaDB-0+deb11u2
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.6.5
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

23.9.0

**Comment by murrant** [comment]
4294967294 is a lot of border routers :)

**Comment by Cormoran96** [comment]
Yes, but that's a lie. ;)

Before the update to 23.10 I don't have this issue with the same devices
