### ISSUE TITLE
Cisco NTP failing since #15639

### ISSUE THREAD

**Issue by tsrats** [librenms/librenms#15654]
### The problem

Since my local instance updated with #15639, I now get the following errors in my logs:

```
Error polling ntp module for border.althea-shaheen.com. Error: Class "Number" not found in /opt/librenms/includes/polling/ntp/cisco.inc.php:65
Stack trace:
#0 /opt/librenms/includes/polling/ntp.inc.php(24): include()
#1 /opt/librenms/LibreNMS/Modules/LegacyModule.php(114): include('...')
#2 /opt/librenms/LibreNMS/Poller.php(176): LibreNMS\Modules\LegacyModule->poll()
#3 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#4 /opt/librenms/app/Console/Commands/DevicePoll.php(44): LibreNMS\Poller->poll()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#11 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(177): Symfony\Component\Console\Command\Command->run()
#13 /opt/librenms/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#14 /opt/librenms/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#15 /opt/librenms/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#17 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#18 /opt/librenms/lnms(38): App\Console\Kernel->handle()
#19 {main}  
Class "Number" not found {"exception":"[object] (Error(code: 0): Class \"Number\" not found at /opt/librenms/includes/polling/ntp/cisco.inc.php:65)"} 
INFO: device:poll border.althea-shaheen.com (1) polled in 9.978s  
```

### Output of ./validate.php

```txt
librenms@librenms:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.11.0-44-g93baa514c (2023-12-17T17:52:28+00:00)
DB Schema | 2023_12_15_105529_access_points_nummonbssid_integer (275)
PHP       | 8.2.12
Python    | 3.11.2
Database  | MariaDB 10.11.4-MariaDB-1~deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.6.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### What was the last working version of LibreNMS?

Version before 23.11.0-44-g93baa514c

**Comment by PipoCanaja** [comment]
Hi @tsrats 
Thanx ! 
The fix is on its way.
