### ISSUE TITLE
Fortigate discovery error

### ISSUE THREAD

**Issue by trs80** [librenms/librenms#15770]
### The problem

Discovery of some (but not all - the VM ones are OK) Fortigate devices has an error:

[0;31mError discovering sensors module for mizar.ccgs.wa.edu.au.[0m TypeError: long2ip(): Argument #1 ($ip) must be of type int, float given in /opt/librenms/LibreNMS/Util/IP.php:65
Stack trace:
#0 /opt/librenms/LibreNMS/Util/IP.php(65): long2ip()
#1 /opt/librenms/LibreNMS/Device/YamlDiscovery.php(210): LibreNMS\Util\IP::fromHexString()
#2 [internal function]: LibreNMS\Device\YamlDiscovery::LibreNMS\Device\{closure}()
#3 /opt/librenms/app/View/SimpleTemplate.php(111): preg_replace_callback()
#4 /opt/librenms/LibreNMS/Device/YamlDiscovery.php(220): App\View\SimpleTemplate->__toString()
#5 /opt/librenms/includes/discovery/functions.inc.php(933): LibreNMS\Device\YamlDiscovery::replaceValues()
#6 /opt/librenms/includes/discovery/functions.inc.php(1026): discovery_process()
#7 /opt/librenms/includes/discovery/sensors.inc.php(87): sensors()
#8 /opt/librenms/includes/discovery/functions.inc.php(164): include('...')
#9 /opt/librenms/discovery.php(108): discover_device()
#10 {main}  

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.1.0-42-g0b8413ed9 (2024-01-19T23:14:29+08:00)
DB Schema | 2023_12_12_171400_alert_rule_note (277)
PHP       | 8.1.23
Python    | 3.7.3
Database  | MariaDB 10.3.39-MariaDB-0+deb10u1-log
RRDTool   | 1.7.1
SNMP      | 5.7.3
===========================================

[OK]    Composer Version: 2.6.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Global lnms shortcut not installed. lnms command must be run with full path
        [FIX]:
        sudo ln -s /opt/librenms/lnms /usr/local/bin/lnms
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         LibreNMS/OS/Ewc.php
         composer.json
         composer.lock
         includes/discovery/sensors/voltage/netagent2.inc.php
         includes/polling/cisco-voice/cisco-iosdsp.inc.php
         includes/polling/cisco-voice/cisco-iospri.inc.php
         mibs/fortinet/FORTINET-FORTIMANAGER-FORTIANALYZER-MIB
[FAIL]  We have found some files that are owned by a different user than 'librenms', this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
        [FIX]:
        sudo chown -R librenms:librenms /opt/librenms
        sudo setfacl -d -m g::rwx /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        sudo chmod -R ug=rwX /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        Files:
         /opt/librenms/storage/app/purifier/HTML/4.17.0,fe97c36109f79a043b63c51aaa36362f0f2f6553,1.ser
```

### Device info

Fortigate 

### Discovery output

```txt
./discovery.php -h 323 -d -m sensors | ./pbin.sh

https://p.libren.ms/view/445c645c
```

### Poller output

```txt
./lnms device:poll mizar.ccgs.wa.edu.au -vv --no-data | ./pbin.sh
https://p.libren.ms/view/a3a971db
```

**Comment by rudybroersma** [comment]
Oh wait.
What FortiOS version are you running? 7.2 by any chance?

**Comment by rudybroersma** [comment]
From 7.2 and up Fortinet has changed SNMP output for BGP peers (it now includes vDOM information). This doesn't work on currently LibreNMS discovery:

https://github.com/librenms/librenms/issues/14898
https://github.com/librenms/librenms/issues/14833

I have this issue on my ToDo list

**Comment by trs80** [comment]
I'm not sure this is the same, because I see it on a 60E running 7.0 which doesn't have BGP or VDOMs:

```
Error discovering sensors module for megrez.ccgs.wa.edu.au. TypeError: long2ip(): Argument #1 ($ip) must be of type int, float given in /opt/librenms/LibreNMS/Util/IP.php:65
Stack trace:
#0 /opt/librenms/LibreNMS/Util/IP.php(65): long2ip()
#1 /opt/librenms/LibreNMS/Device/YamlDiscovery.php(210): LibreNMS\Util\IP::fromHexString()
#2 [internal function]: LibreNMS\Device\YamlDiscovery::LibreNMS\Device\{closure}()
#3 /opt/librenms/app/View/SimpleTemplate.php(111): preg_replace_callback()
#4 /opt/librenms/LibreNMS/Device/YamlDiscovery.php(220): App\View\SimpleTemplate->__toString()
#5 /opt/librenms/includes/discovery/functions.inc.php(933): LibreNMS\Device\YamlDiscovery::replaceValues()
#6 /opt/librenms/includes/discovery/functions.inc.php(1026): discovery_process()
#7 /opt/librenms/includes/discovery/sensors.inc.php(87): sensors()
#8 /opt/librenms/includes/discovery/functions.inc.php(164): include('...')
#9 /opt/librenms/discovery.php(108): discover_device()
#10 {main}
```

**Comment by andreas1o** [comment]
> From 7.2 and up Fortinet has changed SNMP output for BGP peers (it now includes vDOM information). This doesn't work on currently LibreNMS discovery:
> 
> #14898 #14833
> 
> I have this issue on my ToDo list

Do you have any update on this issue ?

**Comment by rudybroersma** [comment]
> > From 7.2 and up Fortinet has changed SNMP output for BGP peers (it now includes vDOM information). This doesn't work on currently LibreNMS discovery:
> > #14898 #14833
> > I have this issue on my ToDo list
> 
> Do you have any update on this issue ?

Fortinet has a 'work around' you should implement:

https://github.com/librenms/librenms/issues/14833#issuecomment-1978316359

This is a two tier solution. You have to disable the append-index setting and use per-vDOM SNMP settings:

https://community.fortinet.com/t5/FortiGate/Technical-Tip-Configuring-SNMP-when-VDOM-is-enabled/ta-p/194853

**Comment by murrant** [comment]
https://community.fortinet.com/t5/FortiGate/Technical-Tip-Enable-SNMP-index-extension/ta-p/326675

**Comment by murrant** [comment]
https://github.com/librenms/librenms/issues/14898#issuecomment-2557223641
