### ISSUE TITLE
Issue: array_intersect_key(): Argument #1 ($array) must be of type array, string given

### ISSUE THREAD

**Issue by rinsekloek** [librenms/librenms#15839]
### The problem

We do get a lot of errors after some daily.sh with the following messages:

librenms@ftth-mgmt-monapp:~$ ./addhost.php <HOST> ap v3 LIBRENMS <PASS> <KEY> sha aes

In Arr.php line 491:

  array_intersect_key(): Argument #1 ($array) must be of type array, string given

The root cause seems to be that a lot of functions call: only(), with the first parameter not being an array

    public static function only($array, $keys)
    {
        return array_intersect_key($array, array_flip((array) $keys));
    }

Seems that some strict type checking is enabled ?

### Output of ./validate.php

```txt
librenms@ftth-mgmt-monapp:~$ /opt/librenms/validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.1.0-87-gf0934b53c (2024-02-18T18:30:42+01:00)
DB Schema | 2024_02_07_151845_custom_map_additions (290)
PHP       | 8.2.8
Python    | 3.9.2
Database  | MariaDB 10.5.19-MariaDB-0+deb11u2
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.7.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is functional
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### Anything in the logs that might be useful for us?

```txt
We see this error occurring often in the log

librenms.log.1:#0 /data/librenms/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(491): array_intersect_key()
librenms.log.1:#1 /data/librenms/app/Actions/Device/ValidateDeviceAndCreate.php(139): Illuminate\Support\Arr::only()
librenms.log.1:array_intersect_key(): Argument #1 ($array) must be of type array, string given {"exception":"[object] (TypeError(code: 0): array_intersect_key(): Argument #1 ($array) must be of type array, string given at /data/librenms/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:491)"}
librenms.log.1:Error discovering discovery-protocols module for zvh-wp2-dr02. TypeError: array_intersect_key(): Argument #1 ($array) must be of type array, string given in /data/librenms/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:491
librenms.log.1:#0 /data/librenms/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(491): array_intersect_key()
librenms.log.1:#1 /data/librenms/app/Actions/Device/ValidateDeviceAndCreate.php(139): Illuminate\Support\Arr::only()
librenms.log.1:array_intersect_key(): Argument #1 ($array) must be of type array, string given {"exception":"[object] (TypeError(code: 0): array_intersect_key(): Argument #1 ($array) must be of type array, string given at /data/librenms/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:491)"}
librenms.log.1:Error discovering discovery-protocols module for wer-wp1-dr02. TypeError: array_intersect_key(): Argument #1 ($array) must be of type array, string given in /data/librenms/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:491
librenms.log.1:#0 /data/librenms/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(491): array_intersect_key()
librenms.log.1:#1 /data/librenms/app/Actions/Device/ValidateDeviceAndCreate.php(139): Illuminate\Support\Arr::only()
librenms.log.1:array_intersect_key(): Argument #1 ($array) must be of type array, string given {"exception":"[object] (TypeError(code: 0): array_intersect_key(): Argument #1 ($array) must be of type array, string given at /data/librenms/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:491)"}
```

**Comment by PipoCanaja** [comment]
Hi @rinsekloek 
It is not clear if we have one or two issues here. We need to know exactly how the issue(s) is (are) triggered. 
From what I see : 
- 1 issue during discovery-protocols module.
 - To understand if (and solve it) please run `./discovery.php -m discovery-protocols -v -d -h <idOfDevice>`. Beware that private data (SNMP community, name of your neighbor devices) will be in the debug data, so don't post it without first sanitazing a little bit. You can also send it to me privately (discord) if you prefer. 
- 1 issue during "add-host" call
 - Is it the same stacktrace (meaning it would occur in the discovery following the add-host) or does the add-host fail ?

**Comment by rinsekloek** [comment]
I found the issue. We had configured snmp.v3 in the config this way (Without the 2d array setting as now is done in the WEBUI settings. Removed this and configured snmp.v3 in ui and it is fixed.

config['snmp']['v3'] = array("authalgo" => "SHA", "authlevel" => "authPriv", "authname" => "<user>", "authpass" => "<secret>", "cryptoalgo" => "AES", "cryptopass" => "<secret>");
