### ISSUE TITLE
librenms log flood - Error polling os module - ErrorException: Undefined array key "panGPGWUtilizationActiveTunnels" in Panos.php:150 Stack trace: #0 

### ISSUE THREAD

**Issue by jt0005** [librenms/librenms#16006]
### The problem

New installation, all devices monitored are PaloAlto Networks firewalls, I am seeing the logs continuously flooded with the following stack traces below for each system that is polled, the rest of the device info displays correctly and as expected, the notifications for the devices all show errors logged in the os module. 

`Error polling os module for 10.x.x.x. ErrorException: Undefined array key "panGPGWUtilizationActiveTunnels" in /opt/librenms/LibreNMS/OS/Panos.php:150
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /opt/librenms/app/Providers/ErrorReportingProvider.php(199): call_user_func()
#3 /opt/librenms/LibreNMS/OS/Panos.php(150): App\Providers\ErrorReportingProvider->handleError()
#4 /opt/librenms/LibreNMS/Modules/Os.php(80): LibreNMS\OS\Panos->pollOS()
#5 /opt/librenms/LibreNMS/Poller.php(176): LibreNMS\Modules\Os->poll()
#6 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#7 /opt/librenms/app/Console/Commands/DevicePoll.php(45): LibreNMS\Poller->poll()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#14 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\Component\Console\Command\Command->run()
#16 /opt/librenms/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
#17 /opt/librenms/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#18 /opt/librenms/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#20 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#21 /opt/librenms/lnms(40): App\Console\Kernel->handle()
#22 {main}
`

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.4.1-22-g07655c24a (2024-04-30T05:40:08-07:00)
DB Schema | 2024_04_22_161711_custom_maps_add_group (292)
PHP       | 8.1.2-1ubuntu2.15
Python    | 3.10.12
Database  | MariaDB 10.6.16-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.7.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

**Comment by jt0005** [comment]
Murrant, Otterei, I just wanted to say a huge thank you for the fix! I can confirm that after your changes went in, I no longer see those errors!
