### ISSUE TITLE
got error after running librenms a few hours 

### ISSUE THREAD

**Issue by fengjian1993** [librenms/librenms#16047]
### The problem

got error after running librenms a few hours
it shows 'Whoops, looks like something went wrong. Check your librenms.log.' in page.
more details as following

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.4.0 (2024-05-05T00:28:52+02:00)
DB Schema | 2024_04_10_093513_remove_device_perf (291)
PHP       | 8.2.18
Python    | 3.11.9
Database  | MariaDB 10.5.24-MariaDB-1:10.5.24+maria~ubu2004
RRDTool   | 1.8.0
SNMP      | 5.9.4
===========================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Non-git install, updates are manual or from package
```

### Anything in the logs that might be useful for us?

```txt
Next Illuminate\Database\QueryException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Name does not resolve (Connection: mysql, SQL: select * from `config` where (`config_name` = snmp.unescape) limit 1) in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(983): Illuminate\Database\Connection->runQueryCallback()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(962): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(785): Illuminate\Database\Connection->handleQueryException()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): Illuminate\Database\Connection->run()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2797): Illuminate\Database\Connection->select()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2786): Illuminate\Database\Query\Builder->runSelect()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3340): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2785): Illuminate\Database\Query\Builder->onceWithColumns()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(738): Illuminate\Database\Query\Builder->get()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(722): Illuminate\Database\Eloquent\Builder->getModels()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(333): Illuminate\Database\Eloquent\Builder->get()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(567): Illuminate\Database\Eloquent\Builder->first()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(599): Illuminate\Database\Eloquent\Builder->firstOrCreate()
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->updateOrCreate()
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2334): Illuminate\Database\Eloquent\Model->forwardCallTo()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2346): Illuminate\Database\Eloquent\Model->__call()
#16 /opt/librenms/LibreNMS/Config.php(260): Illuminate\Database\Eloquent\Model::__callStatic()
#17 /opt/librenms/LibreNMS/Config.php(474): LibreNMS\Config::persist()
#18 /opt/librenms/LibreNMS/Config.php(61): LibreNMS\Config::processConfig()
#19 /opt/librenms/app/Providers/ConfigServiceProvider.php(27): LibreNMS\Config::load()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\ConfigServiceProvider->boot()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#25 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1030): Illuminate\Container\Container->call()
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1011): Illuminate\Foundation\Application->bootProvider()
#27 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#28 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1010): array_walk()
#29 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#30 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#31 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\Foundation\Application->bootstrapWith()
#32 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Foundation\Http\Kernel->bootstrap()
#33 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#34 /opt/librenms/html/index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#35 {main}  
php_network_getaddresses: getaddrinfo for redis failed: Name does not resolve [tcp://redis:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 0): php_network_getaddresses: getaddrinfo for redis failed: Name does not resolve [tcp://redis:6379] at /opt/librenms/vendor/predis/predis/src/Connection/AbstractConnection.php:144)"}
```

**Comment by murrant** [comment]
Based on your logs you are using docker and you have a name resolution error for your other containers.  Make sure they are running.

**Comment by fengjian1993** [comment]
> Based on your logs you are using docker and you have a name resolution error for your other containers. Make sure they are running.

i checked db container. it's normal because i login in via mysql command.
