### ISSUE TITLE
Poller Errors in log for Riverbed.php

### ISSUE THREAD

**Issue by bitcoredotorg** [librenms/librenms#16062]
### The problem

A fresh install of Librenms from the provided OVA release tag v23.11.0  running librenms-ubuntu-22.04-amd64-vmware.ova.  Ubuntu has been patched (apt upgrade) but distro is still: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-107-generic x86_64)

Riverbed devices appear to be polling OK and collecting data, however librenms logs have a PHP error when the devices are polled, which seems related to a put() call on line 111 of Riverbed.php.

### Output of ./validate.php

```txt
librenms@r-librenms:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.5.0 (2024-05-20T03:53:54+00:00)
DB Schema | 2024_04_29_183605_custom_maps_drop_background_suffix_and_background_version (294)
PHP       | 8.1.2-1ubuntu2.17
Python    | 3.10.12
Database  | MariaDB 10.6.16-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.7.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### Anything in the logs that might be useful for us?

```txt
Error polling os module for [redacted]. Error: Call to a member function put() on array in /opt/librenms/LibreNMS/OS/Riverbed.php:111
Stack trace:
#0 /opt/librenms/LibreNMS/Modules/Os.php(80): LibreNMS\OS\Riverbed->pollOS()
#1 /opt/librenms/LibreNMS/Poller.php(176): LibreNMS\Modules\Os->poll()
#2 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#3 /opt/librenms/app/Console/Commands/DevicePoll.php(45): LibreNMS\Poller->poll()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#10 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\Component\Console\Command\Command->run()
#12 /opt/librenms/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
#13 /opt/librenms/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#14 /opt/librenms/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#16 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#17 /opt/librenms/lnms(40): App\Console\Kernel->handle()
#18 {main}
Call to a member function put() on array {"exception":"[object] (Error(code: 0): Call to a member function put() on array at /opt/librenms/LibreNMS/OS/Riverbed.php:111)"}
INFO: device:poll [redacted] (42) polled in 5.608s
```

**Comment by bitcoredotorg** [comment]
Meant to post to a device issue, so sorry!
