### ISSUE TITLE
Issues in parsing Dell OS10 BGP peers

### ISSUE THREAD

**Issue by ssasso** [librenms/librenms#16157]
### The problem

For some unknown reason, the hex format of the IP Address reported for Dell OS10 bgp-peers is reported with a hex length of 10 instead of 8, which seems to break this check: 
https://github.com/librenms/librenms/blob/6474e1e0b8b9887aa0f926a2ef05c4801efd8eb5/LibreNMS/Util/IP.php#L64

### Output of ./validate.php

```txt
librenms@sol-prod-monitoring:~$ /opt/librenms/validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.6.0-10-ga37efd287 (2024-06-19T04:58:10+00:00)
DB Schema | 2024_04_29_183605_custom_maps_drop_background_suffix_and_background_version (294)
PHP       | 8.3.6
Python    | 3.12.3
Database  | MariaDB 10.11.8-MariaDB-0ubuntu0.24.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.4.pre2
===========================================

[OK]    Composer Version: 2.7.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Your install is over 24 hours out of date, last update: Wed, 19 Jun 2024 04:58:10 +0000
        [FIX]:
        Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
```

### Device info

Dell S5224, Dell S4128, Dell S5232, Dell S5212, Dell S4112

### Discovery output

```txt
librenms@sol-prod-monitoring:~$ ./discovery.php -h 36 -m bgp-peers -v -d
LibreNMS Discovery
SQL[select `migration` from `migrations` order by `id` desc limit 1 [] 3.23ms]

SQL[select count(*) as aggregate from `migrations` [] 0.43ms]

SQL[select version() [] 0.18ms]

===========================================
Component | Version
--------- | -------
LibreNMS  | 24.6.0-10-ga37efd287 (2024-06-19T04:58:10+00:00)
DB Schema | 2024_04_29_183605_custom_maps_drop_background_suffix_and_background_version (294)
PHP       | 8.3.6
Python    | 3.12.3
Database  | MariaDB 10.11.8-MariaDB-0ubuntu0.24.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.4.pre2
===========================================
DEBUG!
Updating os_def.cache
Override discovery modules: bgp-peers
SQL[SELECT * FROM `devices` WHERE disabled = 0 AND `device_id` = '36' ORDER BY device_id DESC [] 1.04ms]

172.24.1.30 36 dell-os10 SQL[select * from `devices` where `device_id` = ? limit 1 [36] 0.27ms]

SQL[select * from `devices_attribs` where `devices_attribs`.`device_id` = ? and `devices_attribs`.`device_id` is not null [36] 0.23ms]

[FPING] '/usr/bin/fping' '-e' '-q' '-c' '3' '-p' '500' '-t' '500' '-O' '0' '172.24.1.30'

response: 172.24.1.30 : xmt/rcv/%loss = 3/3/0%, min/avg/max = 0.405/0.582/0.678
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/dell' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'public' '-OQXUte' 'udp:172.24.1.30:161' 'SNMPv2-MIB::sysObjectID.0']
SNMPv2-MIB::sysObjectID.0 = SNMPv2-SMI::enterprises.674.11000.5000.100.2.1.18


Modules status: Global+
OS
Device

#### Load disco module core ####
Attempting to initialize OS: dell-os10
Attempting to initialize Group OS: dell
OS initialized as Generic (dell-os10)
SNMP['/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/dell' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'public' '-OQXUte' '-On' 'udp:172.24.1.30:161' 'SNMPv2-MIB::sysObjectID.0' 'SNMPv2-MIB::sysDescr.0' 'SNMPv2-MIB::sysName.0']
.1.3.6.1.2.1.1.2.0 = .1.3.6.1.4.1.674.11000.5000.100.2.1.18
.1.3.6.1.2.1.1.1.0 = Dell SmartFabric OS10 Enterprise.
Copyright (c) 1999-2024 by Dell Inc. All Rights Reserved.
System Description: OS10 Enterprise.
OS Version: 10.5.6.2.
System Type: S5212F-ON
.1.3.6.1.2.1.1.5.0 = FABRIC-LEAF-3


| Dell SmartFabric OS10 Enterprise.
Copyright (c) 1999-2024 by Dell Inc. All Rights Reserved.
System Description: OS10 Enterprise.
OS Version: 10.5.6.2.
System Type: S5212F-ON | .1.3.6.1.4.1.674.11000.5000.100.2.1.18 |

OS: Dell EMC Networking OS10 Enterprise (dell-os10)

Attempting to initialize OS: dell-os10
Attempting to initialize Group OS: dell
OS initialized as Generic (dell-os10)

>> Runtime for discovery module 'core': 0.1720 seconds with 303664 bytes
>> SNMP: [1/0.16s] MySQL: [0/0.00s] RRD: [0/0.00s]
#### Unload disco module core ####

Modules status: Global+
OS
Device

#### Load disco module bgp-peers ####
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'public' '-OQUs' '-m' 'DELLEMC-OS10-BGP4V2-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/dell' 'udp:172.24.1.30:161' 'os10bgp4V2PeerTable']
os10bgp4V2PeerLocalAddrType.1.ipv4."10.0.0.1" = ipv4
os10bgp4V2PeerLocalAddrType.1.ipv4."10.0.0.2" = ipv4
os10bgp4V2PeerLocalAddr.1.ipv4."10.0.0.1" = "10.0.0.30"
os10bgp4V2PeerLocalAddr.1.ipv4."10.0.0.2" = "10.0.0.30"
os10bgp4V2PeerLocalPort.1.ipv4."10.0.0.1" = 32911
os10bgp4V2PeerLocalPort.1.ipv4."10.0.0.2" = 40285
os10bgp4V2PeerLocalAs.1.ipv4."10.0.0.1" = 65000
os10bgp4V2PeerLocalAs.1.ipv4."10.0.0.2" = 65000
os10bgp4V2PeerLocalIdentifier.1.ipv4."10.0.0.1" = 49.48.46.48.46.48.46.51.48
os10bgp4V2PeerLocalIdentifier.1.ipv4."10.0.0.2" = 49.48.46.48.46.48.46.51.48
os10bgp4V2PeerRemotePort.1.ipv4."10.0.0.1" = 179
os10bgp4V2PeerRemotePort.1.ipv4."10.0.0.2" = 179
os10bgp4V2PeerRemoteAs.1.ipv4."10.0.0.1" = 65000
os10bgp4V2PeerRemoteAs.1.ipv4."10.0.0.2" = 65000
os10bgp4V2PeerRemoteIdentifier.1.ipv4."10.0.0.1" = 49.48.46.48.46.48.46.49
os10bgp4V2PeerRemoteIdentifier.1.ipv4."10.0.0.2" = 49.48.46.48.46.48.46.50
os10bgp4V2PeerAdminStatus.1.ipv4."10.0.0.1" = running
os10bgp4V2PeerAdminStatus.1.ipv4."10.0.0.2" = running
os10bgp4V2PeerState.1.ipv4."10.0.0.1" = established
os10bgp4V2PeerState.1.ipv4."10.0.0.2" = established
os10bgp4V2PeerDescription.1.ipv4."10.0.0.1" = FABRIC-SPINE-1
os10bgp4V2PeerDescription.1.ipv4."10.0.0.2" = FABRIC-SPINE-2
os10bgp4V2PeerEntry.15.1.ipv4."10.0.0.1" = "default"
os10bgp4V2PeerEntry.15.1.ipv4."10.0.0.2" = "default"

Error discovering bgp-peers module for 172.24.1.30. LibreNMS\Exceptions\InvalidIpException: Could not parse into IP: 000a000001 in /opt/librenms/LibreNMS/Util/IP.php:78
Stack trace:
#0 /opt/librenms/LibreNMS/Util/IP.php(108): LibreNMS\Util\IP::fromHexString()
#1 /opt/librenms/includes/discovery/bgp-peers/dell-os10.inc.php(38): LibreNMS\Util\IP::fromSnmpString()
#2 /opt/librenms/includes/discovery/bgp-peers.inc.php(11): include('...')
#3 /opt/librenms/includes/discovery/functions.inc.php(167): include('...')
#4 /opt/librenms/discovery.php(108): discover_device()
#5 {main}
SQL[insert into `eventlog` (`reference`, `type`, `datetime`, `severity`, `message`, `username`, `device_id`) values (?, ?, ?, ?, ?, ?, ?) [null,"discovery","2024-06-26 15:48:53",5,"Error discovering bgp-peers module. Check log file for more details.","",36] 1.56ms]

Could not parse into IP: 000a000001 {"exception":"[object] (LibreNMS\\Exceptions\\InvalidIpException(code: 0): Could not parse into IP: 000a000001 at /opt/librenms/LibreNMS/Util/IP.php:78)"}

>> Runtime for discovery module 'bgp-peers': 0.2080 seconds with 424448 bytes
>> SNMP: [1/0.20s] MySQL: [1/0.02s] RRD: [0/0.00s]
#### Unload disco module bgp-peers ####

SQL[update `devices` set `last_discovered_timetaken` = ?, `last_discovered` = NOW() where `device_id` = ? [1.555,36] 1.05ms]

Discovered in 1.555 seconds

./discovery.php 36 2024-06-26 15:48:53 - 1 devices discovered in 1.815 secs

SNMP [3/0.53s]: Snmpget[2/0.33s] Snmpwalk[1/0.20s]
SQL [9/0.09s]: Select[7/0.06s] Insert[1/0.02s] Update[1/0.01s]
RRD [0/0.00s]:
```

### Poller output

```txt
> There was an error creating your issue: body is too long (maximum is 65536 characters).
```

**Comment by ssasso** [comment]
(I was unable to copy the poller output for the body limit, but I think the error is well reported on the discovery part)

**Comment by PipoCanaja** [comment]
Hi @ssasso 
Seems clear that 1 Byte (`00` in hex) is added to the IP addr. Could you check if the value is sent wrong by the device or if the discovery code is somehow wrong ?

**Comment by ssasso** [comment]
@PipoCanaja so `000a000001` is `10.0.0.1`, and looking at the message it seems it only appears as a key (unless the error is related to something that happens later?)

So I manually tried: `/usr/bin/snmpbulkwalk -v2c -cpublic -OQU -m DELLEMC-OS10-BGP4V2-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/dell udp:172.24.1.30:161 os10bgp4V2PeerTable` which outputs:

```
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerLocalAddrType.1.ipv4."10.0.0.1" = ipv4
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerLocalAddrType.1.ipv4."10.0.0.2" = ipv4
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerLocalAddr.1.ipv4."10.0.0.1" = "10.0.0.30"
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerLocalAddr.1.ipv4."10.0.0.2" = "10.0.0.30"
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerLocalPort.1.ipv4."10.0.0.1" = 179
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerLocalPort.1.ipv4."10.0.0.2" = 179
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerLocalAs.1.ipv4."10.0.0.1" = 65000
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerLocalAs.1.ipv4."10.0.0.2" = 65000
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerLocalIdentifier.1.ipv4."10.0.0.1" = 49.48.46.48.46.48.46.51.48
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerLocalIdentifier.1.ipv4."10.0.0.2" = 49.48.46.48.46.48.46.51.48
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerRemotePort.1.ipv4."10.0.0.1" = 40885
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerRemotePort.1.ipv4."10.0.0.2" = 33279
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerRemoteAs.1.ipv4."10.0.0.1" = 65000
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerRemoteAs.1.ipv4."10.0.0.2" = 65000
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerRemoteIdentifier.1.ipv4."10.0.0.1" = 49.48.46.48.46.48.46.49
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerRemoteIdentifier.1.ipv4."10.0.0.2" = 49.48.46.48.46.48.46.50
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerAdminStatus.1.ipv4."10.0.0.1" = running
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerAdminStatus.1.ipv4."10.0.0.2" = running
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerState.1.ipv4."10.0.0.1" = established
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerState.1.ipv4."10.0.0.2" = established
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerDescription.1.ipv4."10.0.0.1" = FABRIC-SPINE-1
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerDescription.1.ipv4."10.0.0.2" = FABRIC-SPINE-2
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerEntry.15.1.ipv4."10.0.0.1" = "default"
DELLEMC-OS10-BGP4V2-MIB::os10bgp4V2PeerEntry.15.1.ipv4."10.0.0.2" = "default"
```

While executing the command I took a pcap trace, where I can see `10.0.0.1` as part of the keys, correctly encoded:

![image](https://github.com/user-attachments/assets/950feb2e-2ab4-46cb-8cf8-80a3b6feb53e)

**Comment by cppmonkey** [comment]
I've added this to `LibreNMS/Util/IP.php` between the length 8 and 32 versions.
```
            if (strlen($hex) == 10) {
                return new IPv4(long2ip(hexdec(substr($hex, 2))));
            }
```

It gets me a little further, but it still fails to complete.  This time being unable to parse the ASN numbers
```
LibreNMS\Util\AutonomousSystem::get(): Argument #1 ($asn) must be of type string|int, null given, called in /opt/librenms/includes/discovery/bgp-peers/dell-os10.inc.php on line 50 {"exception":"[object] (TypeError(code: 0): LibreNMS\\Util\\AutonomousSystem::get(): Argument #1 ($asn) must be of type string|int, null given, called in /opt/librenms/includes/discovery/bgp-peers/dell-os10.inc.php on line 50 at /opt/librenms/LibreNMS/Util/AutonomousSystem.php:39)"}
```

My ASN within my GNS3 lab is 65201.  And I'm running [OS10 within GNS3](https://www.dell.com/support/home/en-uk/product-support/product/smartfabric-os10-emp-partner/drivers), emulating the S4128F running 10.5.6.3.

If I can find time, I may dive a little deeper.
