### ISSUE TITLE
Librenms fails to run ipmitool, same command runs separately

### ISSUE THREAD

**Issue by oernii** [librenms/librenms#16196]
### The problem

Librenms host has IPMI enabled, however the pollers fails to process run the command. 

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.4.0 (2024-05-05T00:28:52+02:00)
DB Schema | 2024_04_10_093513_remove_device_perf (291)
PHP       | 8.2.18
Python    | 3.11.9
Database  | MariaDB 11.4.2-MariaDB-ubu2404
RRDTool   | 1.8.0
SNMP      | 5.9.4
===========================================

[OK]    Installed from package; no Composer required
[FAIL]  APP_KEY does not match key used to encrypt data. APP_KEY must be the same on all nodes.
        [FIX]: 
        If you rotated APP_KEY, run lnms key:rotate to resolve.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[FAIL]  Some dispatcher nodes have not checked in recently
        Inactive Nodes:
         librenms
[OK]    Locks are functional
[OK]    No active python wrapper pollers found
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Non-git install, updates are manual or from package
```

### Anything in the logs that might be useful for us?

```txt
This runs from the same container-exec!:

# /usr/sbin/ipmitool -H 192.168.1.103 -U observium -P xxxxxx -L USER -p 623 -I lanplus -c sdr
SEL,72h,ns,7.1,No Reading
Intrusion,73h,ok,7.1,
Fan1,6240,RPM,ok
Fan2,6120,RPM,ok
Fan3,6240,RPM,ok
Fan4,6240,RPM,ok
...


----------------------------------------------
----------------------------------------------
This crashes, SELinux is disabled:
# ./lnms device:poll -vvv -m ipmi 192.168.1.100
...
#### Load poller module ipmi ####
  
Module enabled: Global + | OS   | Device   | Manual +  
SQL[SELECT * FROM sensors WHERE device_id = ? AND poller_type='ipmi' [14] 1.24ms] 
  
array (
)  
Fetching IPMI sensor data...SNMP['/usr/sbin/ipmitool' '-H' '192.168.1.103' '-U' 'observium' '-P' 'xxxx' '-L' 'USER' '-p' '623' '-I' 'lanplus' '-c' 'sdr']
Error polling ipmi module for 192.168.1.100. Symfony\Component\Process\Exception\ProcessSignaledException: The process has been signaled with signal "11". in /opt/librenms/vendor/symfony/process/Process.php:435
Stack trace:
#0 /opt/librenms/vendor/symfony/process/Process.php(252): Symfony\Component\Process\Process->wait()
#1 /opt/librenms/includes/common.php(70): Symfony\Component\Process\Process->run()
#2 /opt/librenms/includes/polling/ipmi.inc.php(35): external_exec()
#3 /opt/librenms/LibreNMS/Modules/LegacyModule.php(114): include('...')
#4 /opt/librenms/LibreNMS/Poller.php(176): LibreNMS\Modules\LegacyModule->poll()
#5 /opt/librenms/LibreNMS/Poller.php(103): LibreNMS\Poller->pollModules()
#6 /opt/librenms/app/Console/Commands/DevicePoll.php(45): LibreNMS\Poller->poll()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\DevicePoll->handle()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#13 /opt/librenms/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#15 /opt/librenms/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
#16 /opt/librenms/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#17 /opt/librenms/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#19 /opt/librenms/app/Console/Kernel.php(66): Illuminate\Foundation\Console\Kernel->handle()
#20 /opt/librenms/lnms(37): App\Console\Kernel->handle()
#21 {main}  
SQL[insert into `eventlog` (`reference`, `type`, `datetime`, `severity`, `message`, `username`, `device_id`) values (?, ?, ?, ?, ?, ?, ?) [null,"poller","2024-07-12 15:17:18",5,"Error polling ipmi module. Check log file for more details.","",14] 13.72ms] 
  
The process has been signaled with signal "11". {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessSignaledException(code: 0): The process has been signaled with signal \"11\". at /opt/librenms/vendor/symfony/process/Process.php:435)"} 
  
>> SNMP: [0/0.00s] MySQL: [2/0.15s] RRD: [1/0.00s]
...



----------------------------------------------
----------------------------------------------
PS: running on kubernetes k3s otherwise succesfully
```

**Comment by VVelox** [comment]
`sudo -u librenms ipmitool -H 192.168.1.103 -U observium -P xxxxxx -L USER -p 623 -I lanplus -c sdr` work?
