### ISSUE TITLE
unable to connect to MySQL

### ISSUE THREAD

**Issue by Npeca75** [librenms/librenms#16380]
### The problem

after last commit #16349 

```
librenms@nms:~$ ./poller-wrapper.py 1
2024-09-10 05:15:40,891 :: INFO :: Registered as Master
2024-09-10 05:15:40,894 :: CRITICAL :: ERROR: Could not connect to MySQL database! (1045, "Access denied for user 'librenms'@'localhost' (using password: NO)")
Traceback (most recent call last):
  File "/opt/librenms/./poller-wrapper.py", line 64, in <module>
    wrapper.wrapper(
  File "/opt/librenms/LibreNMS/wrapper.py", line 468, in wrapper
    db_connection = LibreNMS.DB(sconfig)
                    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/librenms/LibreNMS/__init__.py", line 220, in __init__
    self.connect()
  File "/opt/librenms/LibreNMS/__init__.py", line 269, in connect
    conn = MySQLdb.connect(**args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/lib/python3/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python3/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'librenms'@'localhost' (using password: NO)")
librenms@nms:~$ 
```

reverting to
`64241dbdf3593456b9b32963c588e48f36d73c48` fix problem

### Output of ./validate.php

```txt
librenms@nms:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.8.0-60-g64241dbdf (2024-09-09T13:12:42+02:00)
DB Schema | 2024_08_27_182000_ports_statistics_table_rev_length (299)
PHP       | 8.2.20
Python    | 3.11.2
Database  | MariaDB 10.11.6-MariaDB-0+deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.7.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

64241dbdf3593456b9b32963c588e48f36d73c48

**Comment by draxien** [comment]
Same issue,

adding $config['db_pass'] into config.php  can fix it temporally

**Comment by hb9eue** [comment]
Same issue.

**Comment by hb9eue** [comment]
Ok, I got it back working. I suspect the environment is not being read correctly in:

LibreNMS/service.py

anymore.

config.php:

```
$config['db_pass'] = "Your Password";
$config['db_host'] = "Your DB Host";
```

db_name and db_user are also condidates, if you don't use the default values.

**Comment by RafalNiewinski** [comment]
Same for all of my installation after today midnight update.

/logs/poller_wrapper.log
`CRITICAL :: ERROR: Could not connect to MySQL database! (1045, "Access denied for user 'librenms'@'localhost' (using password: NO)")`

VALIDATE
```
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.8.0-61-gf1e7a218f (2024-09-09T18:48:07+02:00)
DB Schema | 2024_08_27_182000_ports_statistics_table_rev_length (299)
PHP       | 8.1.2-1ubuntu2.18
Python    | 3.10.12
Database  | MariaDB 10.6.18-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.7.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[FAIL]  Poller is not running.  No poller has run within the last 300 seconds.
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[FAIL]  No active python wrapper pollers found
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

**Comment by f0o** [comment]
Yep can confirm that the facade PR broke the json config conversion which the *.py relies on

**Comment by tomck** [comment]
According to comments here, updating again resolves the issue.

https://community.librenms.org/t/fail-poller-is-not-running-no-poller-has-run-within-the-last-300-seconds/26004

**Comment by RafalNiewinski** [comment]
Yup, the problematic change was reverted here #16382 and now polling works again.
Please update your install by `daily.sh`

**Comment by f0o** [comment]
Closing as the issue was resolved with a Revert PR
