### ISSUE TITLE
Error discovering route module

### ISSUE THREAD

**Issue by rAGSebastianRost** [librenms/librenms#16861]
### The problem

In librenms.log the discovery module reports:

Error discovering route module for (IP ADRESS OF DEVICE REMOVED). TypeError: ip2long(): Argument #1 ($ip) must be of type string, array given in /opt/librenms/LibreNMS/Util/IPv4.php:74

This error happens when discovering FortiNet FortiGate devices.

### Output of ./validate.php

```txt
librenms@librenms-prod:~$ ./validate.php
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.11.0-84-gac7c8e747 (2024-12-08T16:21:08+01:00)
DB Schema | 2024_10_24_131715_mpls_sdp_bindings_enum_string (310)
PHP       | 8.2.26
Python    | 3.11.2
Database  | MariaDB 10.11.6-MariaDB-0+deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.8.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[FAIL]  We have detected that your database schema may be wrong
Database: incorrect column (cef_switching/punt)
Database: incorrect column (cef_switching/punt_prev)
        [FIX]:
        Run the following SQL statements to fix it
        SQL Statements:
         ALTER TABLE `cef_switching` CHANGE `punt` `punt` int NOT NULL ;
         ALTER TABLE `cef_switching` CHANGE `punt_prev` `punt_prev` int NOT NULL ;
Attempt to fix this issue (y or n)?:n
[OK]    MySQL and PHP time match
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

21.11.0

### Anything in the logs that might be useful for us?

```txt
see above
```

**Comment by PipoCanaja** [comment]
Hi @rAGSebastianRost 
Could you do check this `./discovery.php -h <deviceID> -v -d -m route` and search for any clue that could explain the issue ? The reply of the device is definitely not the one LibreNMS expects, but we have no way to findout without more details.

**Comment by rAGSebastianRost** [comment]
The 'array input' is indeed some kind array of nested arrays:

```
Routing table:
array (
  '0.0.0.0' =>
  array (
    'ipRouteDest' =>
    array (
      1 => '0.0.0.0',
    ),
    'ipRouteIfIndex' =>
    array (
      1 => '6',
    ),
    'ipRouteMetric1' =>
    array (
      1 => '0',
    ),
    'ipRouteMetric2' =>
    array (
      1 => '0',
    ),
    'ipRouteMetric3' =>
    array (
      1 => '0',
    ),
    'ipRouteMetric4' =>
    array (
      1 => '0',
    ),
    'ipRouteNextHop' =>
    array (
      1 => '100.70.1.1',
    ),
    'ipRouteType' =>
    array (
      1 => '4',
    ),
    'ipRouteProto' =>
    array (
      1 => '2',
    ),
    'ipRouteAge' =>
    array (
      1 => '0',
    ),
    'ipRouteMask' =>
    array (
      1 => '0.0.0.0',
    ),
    'ipRouteMetric5' =>
    array (
      1 => '0',
    ),
    'ipRouteInfo' =>
    array (
      1 => 'ccitt.0.0',
    ),
  ),
  '10.100.100.0' =>
  array (
    'ipRouteDest' =>
    array (
      1 => '10.100.100.0',
    ),
    'ipRouteIfIndex' =>
    array (
      1 => '5',
    ),
    'ipRouteMetric1' =>
    array (
      1 => '0',
    ),
    'ipRouteMetric2' =>
    array (
      1 => '0',
    ),
    'ipRouteMetric3' =>
    array (
      1 => '0',
    ),
    'ipRouteMetric4' =>
    array (
      1 => '0',
    ),
    'ipRouteNextHop' =>
    array (
      1 => '0.0.0.0',
    ),
    'ipRouteType' =>
    array (
      1 => '3',
    ),
    'ipRouteProto' =>
    array (
      1 => '2',
    ),
    'ipRouteAge' =>
    array (
      1 => '0',
    ),
    'ipRouteMask' =>
    array (
      1 => '255.255.255.0',
    ),
    'ipRouteMetric5' =>
    array (
      1 => '0',
    ),
    'ipRouteInfo' =>
    array (
      1 => 'ccitt.0.0',
    ),
  ),
(FURTHER ARRAYS)

```

**Comment by PipoCanaja** [comment]
Hi @rAGSebastianRost 
Thanx. For some reason, this device is returning an extra index, resulting in those nested arrays instead of the value directly. That would be a bug in the device itself in that case. 

To confirm, you can try to change line 88 of the route file :
```
$inetCidrRoutePfxLen = IPv4::netmask2cidr($ipRoute['ipRouteMask']); //CONVERT
```
to
```
$inetCidrRoutePfxLen = IPv4::netmask2cidr($ipRoute['ipRouteMask'][1]); //CONVERT
```

That will probably fix this error, but all the other lines around line 88 will fail silently (or crash further down). Basically, this device should either reply the correct SNMP value as the MIB says, or specific code should be made to handle the vendor coding errors.

**Comment by rAGSebastianRost** [comment]
Hello @PipoCanaja,

well, that changed something, but only to the worse, as it seems. After the output of the route array the following happens:

```
RFC1213 SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.8ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"6"] 0.84ms]

SQL[select * from `cache` where `key` = ? limit 1 ["laravel_cache_runtimeCacheLibreNMS\\Util\\GitremoteUrl"] 0.43ms]

SQL[select * from `cache` where `key` = ? limit 1 ["laravel_cache_runtimeCacheLibreNMS\\Util\\GithasChanges"] 0.52ms]

Reporting disabled because LibreNMS is not from the official repository
SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.69ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"5"] 0.94ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.62ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.62ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.69ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.77ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.98ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.57ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.43ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"2"] 0.81ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.5ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.81ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.54ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.63ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.71ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.83ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 1.59ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.89ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 1.06ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.75ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.99ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.89ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.59ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.83ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.74ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.79ms]

SQL[select * from `devices` where `devices`.`device_id` = ? limit 1 [390] 0.86ms]

SQL[select * from `ports` where `ports`.`device_id` = ? and `ports`.`device_id` is not null and `ifIndex` = ? limit 1 [390,"1"] 0.85ms]

SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'testit' '-OQUsetX' '-m' 'MPLS-L3VPN-STD-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/fortinet' 'udp:100.70.1.31:161' 'mplsL3VpnVrfPerfCurrNumRoutes']
mplsL3VpnVrfPerfCurrNumRoutes = No Such Object available on this agent at this OID

mplsL3VpnVrfRteTable SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'testit' '-OQUsetX' '-m' 'MPLS-L3VPN-STD-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/fortinet' 'udp:100.70.1.31:161' 'mplsL3VpnVrfRteTable']
mplsL3VpnVrfRteTable = No Such Object available on this agent at this OID


Processing: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.0.0,?,ccitt.0.0,?,100.70.1.1,0,?,2,4,6,?,?,?,?,?)' at line 1 (Connection: mysql, SQL: INSERT IGNORE INTO `route` (`inetCidrRouteDestType`,`inetCidrRouteDest`,`inetCidrRoutePfxLen`,`inetCidrRoutePolicy`,`inetCidrRouteNextHopType`,`inetCidrRouteNextHop`,`inetCidrRouteMetric1`,`inetCidrRouteNextHopAS`,`inetCidrRouteProto`,`inetCidrRouteType`,`inetCidrRouteIfIndex`,`context_name`,`device_id`,`port_id`,`updated_at`,`created_at`)  VALUES (ipv4,0.0.0.0,0,ccitt.0.0,ipv4,100.70.1.1,0,0,2,4,6,,390,13577,2024-12-13 15:21:23,2024-12-13 15:21:23)) (Connection: dbFacile, SQL: INSERT IGNORE INTO `route` (`inetCidrRouteDestType`,`inetCidrRouteDest`,`inetCidrRoutePfxLen`,`inetCidrRoutePolicy`,`inetCidrRouteNextHopType`,`inetCidrRouteNextHop`,`inetCidrRouteMetric1`,`inetCidrRouteNextHopAS`,`inetCidrRouteProto`,`inetCidrRouteType`,`inetCidrRouteIfIndex`,`context_name`,`device_id`,`port_id`,`updated_at`,`created_at`)  VALUES (ipv4,0.0.0.0,0,ccitt.0.0,ipv4,100.70.1.1,0,0,2,4,6,,390,13577,2024-12-13 15:21:23,2024-12-13 15:21:23))#0 /opt/librenms/includes/discovery/route.inc.php(339): dbInsert()
#1 /opt/librenms/includes/discovery/functions.inc.php(170): include('...')
#2 /opt/librenms/discovery.php(108): discover_device()
#3 {main}
+SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.100.0,?,ccitt.0.0,?,0.0.0.0,0,?,2,3,5,?,?,?,?,?)' at line 1 (Connection: mysql, SQL: INSERT IGNORE INTO `route` (`inetCidrRouteDestType`,`inetCidrRouteDest`,`inetCidrRoutePfxLen`,`inetCidrRoutePolicy`,`inetCidrRouteNextHopType`,`inetCidrRouteNextHop`,`inetCidrRouteMetric1`,`inetCidrRouteNextHopAS`,`inetCidrRouteProto`,`inetCidrRouteType`,`inetCidrRouteIfIndex`,`context_name`,`device_id`,`port_id`,`updated_at`,`created_at`)  VALUES (ipv4,10.100.100.0,24,ccitt.0.0,ipv4,0.0.0.0,0,0,2,3,5,,390,13576,2024-12-13 15:21:23,2024-12-13 15:21:23)) (Connection: dbFacile, SQL: INSERT IGNORE INTO `route` (`inetCidrRouteDestType`,`inetCidrRouteDest`,`inetCidrRoutePfxLen`,`inetCidrRoutePolicy`,`inetCidrRouteNextHopType`,`inetCidrRouteNextHop`,`inetCidrRouteMetric1`,`inetCidrRouteNextHopAS`,`inetCidrRouteProto`,`inetCidrRouteType`,`inetCidrRouteIfIndex`,`context_name`,`device_id`,`port_id`,`updated_at`,`created_at`)  VALUES (ipv4,10.100.100.0,24,ccitt.0.0,ipv4,0.0.0.0,0,0,2,3,5,,390,13576,2024-12-13 15:21:23,2024-12-13 15:21:23))#0 /opt/librenms/includes/discovery/route.inc.php(339): dbInsert()
#1 /opt/librenms/includes/discovery/functions.inc.php(170): include('...')
#2 /opt/librenms/discovery.php(108): discover_device()
#3 {main}

(MORE 'SQLSTATE' ERRORS FOR EVERY SINGLE ROUTE)

>> Runtime for discovery module 'route': 0.4570 seconds with 251704 bytes
>> SNMP: [2/0.06s] MySQL: [34/1.09s] InfluxDB: [0/0.00s] RRD: [0/0.00s]
#### Unload disco module route ####

SQL[update `devices` set `last_discovered_timetaken` = ?, `last_discovered` = NOW() where `device_id` = ? [2.501,390] 0.83ms]

Discovered in 2.501 seconds

./discovery.php 390 2024-12-13 15:21:24 - 1 devices discovered in 2.730 secs

SNMP [4/0.12s]: Snmpget[4/0.12s]
SQL [44/1.18s]: Select[43/1.18s] Update[1/0.01s]
InfluxDB [0/0.00s]:
RRD [0/0.00s]:

```

**Comment by PipoCanaja** [comment]
Makes sense. But again, it seems that the issue is on the Fortigate device. Do you run the latest version possible on this device ?

**Comment by rAGSebastianRost** [comment]
As far as i can tell, this error does appear when the device runs FortiOS 7.0.x, but appears when running 7.2.x or 7.4.x .

**Comment by murrant** [comment]
Seen this before.  Fortigate has been breaking every standard MIB by inserting a domain id into the Index.  Please tell their support to stop doing that and create a custom MIB withthe domain index...

**Comment by murrant** [comment]
@rAGSebastianRost yes, they think they introduced a "feature" instead of breaking the MIB.  Like I said.  They need to implement their own MIB under their own enterprise ID.  As of version 7.2, Their devices no longer support RFC1213-MIB or IP-FORWARD-MIB (preferred).

**Comment by murrant** [comment]
https://community.fortinet.com/t5/FortiGate/Technical-Tip-Enable-SNMP-index-extension/ta-p/326675

If you still want to be able fetch data for different vDOM, open a ticket for Fortigate to support specifying vDOM by SNMP context like most vendors do. (instead of breaking standard MIBs as the given setting does)

Directions to configure your Fortigate: https://github.com/librenms/librenms/issues/14898#issuecomment-2557223641
