### ISSUE TITLE
aruba mobilty conductors error while polling

### ISSUE THREAD

**Issue by kkrumm1** [librenms/librenms#16874]
### The problem

Error polling aruba-controller module for 172.16.232.106. PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'interference' at row 1 in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:612
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(612): PDOStatement->execute()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(816): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\Database\Connection->runQueryCallback()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(600): Illuminate\Database\Connection->run()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(552): Illuminate\Database\Connection-

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.11.0-98-g446e05c97 (2024-12-11T17:38:58-06:00)
DB Schema | 2024_10_20_154356_create_qos_table (310)
PHP       | 8.3.11
Python    | 3.10.12
Database  | MariaDB 10.6.18-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.8.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

24.11.0-98

### Device info

Aruba7205-US

### Discovery output

```txt
LibreNMS Discovery
```

### Poller output

```txt
poller
```

**Comment by alagoutte** [comment]
What firmware on Aruba controller ?
