### ISSUE TITLE
Error discovering qos module

### ISSUE THREAD

**Issue by rAGSebastianRost** [librenms/librenms#16909]
### The problem

In librenms.log, the following error shows up;

```
Error discovering qos module for 10.11.3.10. PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php:45
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php(45): PDOStatement->execute()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(816): Illuminate\Database\MySqlConnection->Illuminate\Database\{closure}()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\Database\Connection->runQueryCallback()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php(34): Illuminate\Database\Connection->run()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/MySqlProcessor.php(35): Illuminate\Database\MySqlConnection->insert()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3549): Illuminate\Database\Query\Processors\MySqlProcessor->processInsertGetId()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1982): Illuminate\Database\Query\Builder->insertGetId()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1334): Illuminate\Database\Eloquent\Builder->__call()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1299): Illuminate\Database\Eloquent\Model->insertAndSetId()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1138): Illuminate\Database\Eloquent\Model->performInsert()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(287): Illuminate\Database\Eloquent\Model->save()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(312): Illuminate\Database\Eloquent\Relations\HasOneOrMany->save()
#12 /opt/librenms/LibreNMS/DB/SyncsModels.php(74): Illuminate\Database\Eloquent\Relations\HasOneOrMany->saveMany()
#13 /opt/librenms/LibreNMS/Modules/Qos.php(65): LibreNMS\Modules\Qos->syncModels()
#14 /opt/librenms/includes/discovery/qos.inc.php(26): LibreNMS\Modules\Qos->discover()
#15 /opt/librenms/includes/discovery/functions.inc.php(170): include('...')
#16 /opt/librenms/discovery.php(108): discover_device()
#17 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null (Connection: mysql, SQL: insert into `qos` (`device_id`, `port_id`, `type`, `title`, `tooltip`, `rrd_id`, `snmp_idx`, `ingress`, `egress`, `updated_at`, `created_at`) values (361, 10881, cisco_cbqos_policymap, ?, ?, cbqos-policymap-301989889-301989889, 301989889.301989889, 0, 1, 2024-12-22 00:45:34, 2024-12-22 00:45:34)) in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\Database\Connection->runQueryCallback()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php(34): Illuminate\Database\Connection->run()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/MySqlProcessor.php(35): Illuminate\Database\MySqlConnection->insert()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3549): Illuminate\Database\Query\Processors\MySqlProcessor->processInsertGetId()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1982): Illuminate\Database\Query\Builder->insertGetId()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1334): Illuminate\Database\Eloquent\Builder->__call()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1299): Illuminate\Database\Eloquent\Model->insertAndSetId()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1138): Illuminate\Database\Eloquent\Model->performInsert()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(287): Illuminate\Database\Eloquent\Model->save()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(312): Illuminate\Database\Eloquent\Relations\HasOneOrMany->save()
#10 /opt/librenms/LibreNMS/DB/SyncsModels.php(74): Illuminate\Database\Eloquent\Relations\HasOneOrMany->saveMany()
#11 /opt/librenms/LibreNMS/Modules/Qos.php(65): LibreNMS\Modules\Qos->syncModels()
#12 /opt/librenms/includes/discovery/qos.inc.php(26): LibreNMS\Modules\Qos->discover()
#13 /opt/librenms/includes/discovery/functions.inc.php(170): include('...')
#14 /opt/librenms/discovery.php(108): discover_device()
#15 {main}
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null (Connection: mysql, SQL: insert into `qos` (`device_id`, `port_id`, `type`, `title`, `tooltip`, `rrd_id`, `snmp_idx`, `ingress`, `egress`, `updated_at`, `created_at`) values (361, 10881, cisco_cbqos_policymap, ?, ?, cbqos-policymap-301989889-301989889, 301989889.301989889, 0, 1, 2024-12-22 00:45:34, 2024-12-22 00:45:34)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null (Connection: mysql, SQL: insert into `qos` (`device_id`, `port_id`, `type`, `title`, `tooltip`, `rrd_id`, `snmp_idx`, `ingress`, `egress`, `updated_at`, `created_at`) values (361, 10881, cisco_cbqos_policymap, ?, ?, cbqos-policymap-301989889-301989889, 301989889.301989889, 0, 1, 2024-12-22 00:45:34, 2024-12-22 00:45:34)) at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php:45)"}
```

### Output of ./validate.php

```txt
$ ./validate.php
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.12.0-10-g2389ef89a (2024-12-20T18:25:16+01:00)
DB Schema | 2024_10_24_131715_mpls_sdp_bindings_enum_string (310)
PHP       | 8.2.26
Python    | 3.11.2
Database  | MariaDB 10.11.6-MariaDB-0+deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.8.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[FAIL]  We have detected that your database schema may be wrong
Database: incorrect column (cef_switching/punt)
Database: incorrect column (cef_switching/punt_prev)
        [FIX]:
        Run the following SQL statements to fix it
        SQL Statements:
         ALTER TABLE `cef_switching` CHANGE `punt` `punt` int NOT NULL ;
         ALTER TABLE `cef_switching` CHANGE `punt_prev` `punt_prev` int NOT NULL ;
Attempt to fix this issue (y or n)?:n
[OK]    MySQL and PHP time match
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Zend OPcache - it was already loaded
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

21.12.0

### Anything in the logs that might be useful for us?

```txt
see above
```

**Comment by PipoCanaja** [comment]
Hi @rAGSebastianRost 
Could you run discovery in verbose mode ? That will allow us to see which OS, which device, and where to catch this. 
Thanx

**Comment by raycunningham** [comment]
I am seeing the same issue. Here is the qos section of my verbose discovery. 

#### Load disco module qos ####
Error discovering qos module for 10.3.5.7. PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php:45
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php(45): PDOStatement->execute()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(816): Illuminate\Database\MySqlConnection->Illuminate\Database\{closure}('insert into `qo...', Array)
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\Database\Connection->runQueryCallback('insert into `qo...', Array, Object(Closure))
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php(34): Illuminate\Database\Connection->run('insert into `qo...', Array, Object(Closure))
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/MySqlProcessor.php(35): Illuminate\Database\MySqlConnection->insert('insert into `qo...', Array, 'qos_id')
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3549): Illuminate\Database\Query\Processors\MySqlProcessor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `qo...', Array, 'qos_id')
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1982): Illuminate\Database\Query\Builder->insertGetId(Array, 'qos_id')
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1334): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1299): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1138): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(287): Illuminate\Database\Eloquent\Model->save()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(312): Illuminate\Database\Eloquent\Relations\HasOneOrMany->save(Object(App\Models\Qos))
#12 /opt/librenms/LibreNMS/DB/SyncsModels.php(77): Illuminate\Database\Eloquent\Relations\HasOneOrMany->saveMany(Object(Illuminate\Support\Collection))
#13 /opt/librenms/LibreNMS/Modules/Qos.php(65): LibreNMS\Modules\Qos->syncModels(Object(App\Models\Device), 'qos', Object(Illuminate\Support\Collection))
#14 /opt/librenms/includes/discovery/qos.inc.php(26): LibreNMS\Modules\Qos->discover(Object(LibreNMS\OS\Shared\Cisco))
#15 /opt/librenms/includes/discovery/functions.inc.php(172): include('/opt/librenms/i...')
#16 /opt/librenms/discovery.php(108): discover_device(Array, false)
#17 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null (Connection: mysql, SQL: insert into `qos` (`device_id`, `port_id`, `type`, `title`, `tooltip`, `rrd_id`, `snmp_idx`, `ingress`, `egress`, `updated_at`, `created_at`) values (96, 5465, cisco_cbqos_policymap, ?, ?, cbqos-policymap-301989939-301989939, 301989939.301989939, 0, 1, 2025-02-12 15:50:02, 2025-02-12 15:50:02)) in /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\Database\Connection->runQueryCallback('insert into `qo...', Array, Object(Closure))
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php(34): Illuminate\Database\Connection->run('insert into `qo...', Array, Object(Closure))
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/MySqlProcessor.php(35): Illuminate\Database\MySqlConnection->insert('insert into `qo...', Array, 'qos_id')
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3549): Illuminate\Database\Query\Processors\MySqlProcessor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `qo...', Array, 'qos_id')
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1982): Illuminate\Database\Query\Builder->insertGetId(Array, 'qos_id')
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1334): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1299): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1138): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(287): Illuminate\Database\Eloquent\Model->save()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(312): Illuminate\Database\Eloquent\Relations\HasOneOrMany->save(Object(App\Models\Qos))
#10 /opt/librenms/LibreNMS/DB/SyncsModels.php(77): Illuminate\Database\Eloquent\Relations\HasOneOrMany->saveMany(Object(Illuminate\Support\Collection))
#11 /opt/librenms/LibreNMS/Modules/Qos.php(65): LibreNMS\Modules\Qos->syncModels(Object(App\Models\Device), 'qos', Object(Illuminate\Support\Collection))
#12 /opt/librenms/includes/discovery/qos.inc.php(26): LibreNMS\Modules\Qos->discover(Object(LibreNMS\OS\Shared\Cisco))
#13 /opt/librenms/includes/discovery/functions.inc.php(172): include('/opt/librenms/i...')
#14 /opt/librenms/discovery.php(108): discover_device(Array, false)
#15 {main}
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null (Connection: mysql, SQL: insert into `qos` (`device_id`, `port_id`, `type`, `title`, `tooltip`, `rrd_id`, `snmp_idx`, `ingress`, `egress`, `updated_at`, `created_at`) values (96, 5465, cisco_cbqos_policymap, ?, ?, cbqos-policymap-301989939-301989939, 301989939.301989939, 0, 1, 2025-02-12 15:50:02, 2025-02-12 15:50:02)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null (Connection: mysql, SQL: insert into `qos` (`device_id`, `port_id`, `type`, `title`, `tooltip`, `rrd_id`, `snmp_idx`, `ingress`, `egress`, `updated_at`, `created_at`) values (96, 5465, cisco_cbqos_policymap, ?, ?, cbqos-policymap-301989939-301989939, 301989939.301989939, 0, 1, 2025-02-12 15:50:02, 2025-02-12 15:50:02)) at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php:45)"}

>> Runtime for discovery module 'qos': 10.0100 seconds with 2436128 bytes
>> SNMP: [5/9.62s] MySQL: [3/0.02s] RRD: [0/0.00s]
#### Unload disco module qos ####
