### ISSUE TITLE
addhost.php fails when snmpwalk successed v1.23

### ISSUE THREAD

**Issue by dlangille** [librenms/librenms#5403]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

I am on 1.23

- [x ] Please include all of the information between the `====================================` section of `./[validate.php](url)` which you can run from the cli.
==========================================================
Component | Version
--------- | -------
LibreNMS  | 
DB Schema | 152
PHP       | 5.6.29
MySQL     | 5.6.34
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

The above URL is for: What information do you need to add a new OS?

- [x] Please provide as much detail as possible.

snmpwalk works:
$ snmpwalk -v3 -l authPriv -u MinionComm -a SHA -A pass1234 -x AES -X pass5678 tape01.int.unixathome.org HOST-RESOURCES-MIB::hrSystemNumUsers
HOST-RESOURCES-MIB::hrSystemNumUsers.0 = Gauge32: 4

addhost.php does not:

$ ./addhost.php tape01.int.unixathome.org ap v3 MinionComm pass1234 pass5678 sha aes
PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
PHP Warning:  Module 'snmp' already loaded in Unknown on line 0
PHP Warning:  Module 'session' already loaded in Unknown on line 0
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'filter' already loaded in Unknown on line 0
PHP Warning:  Module 'ctype' already loaded in Unknown on line 0
Could not connect, please check the snmp details and snmp reachability
  SNMP v3: No reply with credentials root/noAuthNoPriv

Am I doing this wrong?

**Comment by murrant** [comment]
I don't understand why you are getting all those warnings, there might be something wrong with you php config.

Please run `./validate.php` and post the output here.

**Comment by dlangille** [comment]
```
[dan@besser:/usr/local/www/librenms] $ ./validate.php 
PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
PHP Warning:  Module 'snmp' already loaded in Unknown on line 0
PHP Warning:  Module 'session' already loaded in Unknown on line 0
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'filter' already loaded in Unknown on line 0
PHP Warning:  Module 'ctype' already loaded in Unknown on line 0
sh: git: not found
sh: git: not found
==========================================================
Component | Version
--------- | -------
LibreNMS  | 
DB Schema | 152
PHP       | 5.6.29
MySQL     | 5.6.34
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

[FAIL]  You need to run this script as root
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character' in /usr/local/www/librenms/validate.php:107
Stack trace:
#0 /usr/local/www/librenms/validate.php(107): DateTime->__construct('@', Object(DateTimeZone))
#1 {main}
  thrown in /usr/local/www/librenms/validate.php on line 107
[dan@besser:/usr/local/www/librenms] $

**Comment by dlangille** [comment]
Then once more with sudo:

```
$ sudo ./validate.php 
PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
PHP Warning:  Module 'snmp' already loaded in Unknown on line 0
PHP Warning:  Module 'session' already loaded in Unknown on line 0
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'filter' already loaded in Unknown on line 0
PHP Warning:  Module 'ctype' already loaded in Unknown on line 0
sh: git: not found
sh: git: not found
==========================================================
Component | Version
--------- | -------
LibreNMS  | 
DB Schema | 152
PHP       | 5.6.29
MySQL     | 5.6.34
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character' in /usr/local/www/librenms/validate.php:107
Stack trace:
#0 /usr/local/www/librenms/validate.php(107): DateTime->__construct('@', Object(DateTimeZone))
#1 {main}
  thrown in /usr/local/www/librenms/validate.php on line 107

**Comment by murrant** [comment]
A few issues here obviously.  Let's start with git missing.

Please install git and make sure you can run `git status`.  The run `./validate.php` again and post the output.

**Comment by dlangille** [comment]
Can we start with something else please?

I am the FreeBSD maintainer for the LibreNMS package. I've just packaged 1.23 and this is running on a host without git. Anyone installing the package will not be expected to have git installed. 

Thank you.

**Comment by laf** [comment]
I'm assuming this is against a server, if so can you post your net-snmp snmpd.conf file so we can replicate this pls?

N

**Comment by murrant** [comment]
I'm still concerned that you have no database schema.  Did you run build-base.php?

**Comment by murrant** [comment]
Also, you could either add git temporarily to troubleshoot or modify validate.php to skip the version check.

**Comment by dlangille** [comment]
Note: this install was an upgrade from v 201607

I will attend to the unanswered questions when I'm back at my laptop.

**Comment by dlangille** [comment]
After installing git 2.11.0:

```
$ sudo ./validate.php 
PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
PHP Warning:  Module 'snmp' already loaded in Unknown on line 0
PHP Warning:  Module 'session' already loaded in Unknown on line 0
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'filter' already loaded in Unknown on line 0
PHP Warning:  Module 'ctype' already loaded in Unknown on line 0
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
==========================================================
Component | Version
--------- | -------
LibreNMS  | 
DB Schema | 152
PHP       | 5.6.29
MySQL     | 5.6.34
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character' in /usr/local/www/librenms/validate.php:107
Stack trace:
#0 /usr/local/www/librenms/validate.php(107): DateTime->__construct('@', Object(DateTimeZone))
#1 {main}
  thrown in /usr/local/www/librenms/validate.php on line 107

**Comment by dlangille** [comment]
I commented out lines 106-109 and ran it again.  Now working on resolving these issues:

```
[WARN]  You don't have $config["user"] set, this most likely needs to be set to librenms
[OK]    Database connection successful
[FAIL]  You have MySQL STRICT_TRANS_TABLES enabled, please disable this until full support has been added: https://dev.mysql.com/doc/refman/5.0/en/sql-mode.html
[WARN]  Your RRD directory is not set to 0775, please check our installation instructions
[WARN]  openssl_random_pseudo_bytes is not being used for user password hashing. This is a recommended function (https://secure.php.net/openssl_random_pseudo_bytes)
[WARN]  Your local git branch is not master, this will prevent automatic updates.
su: unknown class: git diff --name-only --exit-code

**Comment by dlangille** [comment]
Notes:

It helps the user to mention the directory here.  I'll look at a patch later.

```
[WARN]  Your RRD directory is not set to 0775, please check our installation instructions
```

We are now at this stage.  I will try addhost.php again, and if that still fails, I will post snmp configuration details.

```

$ sudo ./validate.php 
PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
PHP Warning:  Module 'snmp' already loaded in Unknown on line 0
PHP Warning:  Module 'session' already loaded in Unknown on line 0
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'filter' already loaded in Unknown on line 0
PHP Warning:  Module 'ctype' already loaded in Unknown on line 0
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
==========================================================
Component | Version
--------- | -------
LibreNMS  | 
DB Schema | 152
PHP       | 5.6.29
MySQL     | 5.6.34
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
==========================================================

[FAIL]  We have found some files that are owned by a different user than www, this will stop you updating automatically and / or rrd files being updated causing graphs to fail:
If you don't run a bespoke install then you can fix this by running `chown -R www:www /usr/local/www/librenms`
	 /usr/local/www/librenms
	 /usr/local/www/librenms/config.php~
	 /usr/local/www/librenms/contrib
	 /usr/local/www/librenms/sql-schema
	 /usr/local/www/librenms/mibs
	 /usr/local/www/librenms/mibs/sub10
	 /usr/local/www/librenms/mibs/riverbed
	 /usr/local/www/librenms/mibs/dell
	 /usr/local/www/librenms/mibs/fiberhome
	 /usr/local/www/librenms/mibs/aos
	  and 1164 more...
[OK]    Database connection successful
[WARN]  openssl_random_pseudo_bytes is not being used for user password hashing. This is a recommended function (https://secure.php.net/openssl_random_pseudo_bytes)

**Comment by dlangille** [comment]
The addhost.php did not error out:

```
$ sudo ./addhost.php tape01.int.unixathome.org ap v3 MinionComm pass1234 pass5678 sha aes
PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
PHP Warning:  Module 'snmp' already loaded in Unknown on line 0
PHP Warning:  Module 'session' already loaded in Unknown on line 0
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'filter' already loaded in Unknown on line 0
PHP Warning:  Module 'ctype' already loaded in Unknown on line 0
Added device tape01.int.unixathome.org (37)

**Comment by dlangille** [comment]
The validate.php recommendation to disable STRICT_TRANS_TABLES led me to try sql-mode="ANSI" in the [mysqld] of my.cnf.  This resolved the [FAIL] message but it prevents any data from being displayed in the webpages.  They are completely blank otherwise.

I commented out the mode= directive, and restarted mysql.  Now the webpages have data, and I can confirm that the tape01 device has been added.

What value for mode is preferred by LibreNMS?

**Comment by dlangille** [comment]
Here is the snmpd.conf from tape01, comments removed:

```
agentAddress  udp:10.55.0.103:161
view   systemonly  included   .1.3.6.1.2.1.1
view   systemonly  included   .1.3.6.1.2.1.25.1

 rocommunity MinionComm  default
 rouser   authOnlyUser

sysLocation    Sitting on the Dock of the Bay
sysContact     Me <me@example.org>
sysServices    72
proc  mountd
proc  ntalkd    4
disk       /     10000
disk       /var  5%
includeAllDisks  10%
load   12 10 5
 trapsink     localhost public
iquerySecName   internalUser       
rouser          internalUser
defaultMonitors          yes
linkUpDownNotifications  yes
 extend    test1   /bin/echo  Hello, world!
 extend-sh test2   echo Hello, world! ; echo Hi there ; exit 35
 master          agentx

**Comment by murrant** [comment]
Check the install docs.  It tells you required settings for MySQL.

Installation-Ubuntu-1604-Apache/#install-configure-mysql

**Comment by dlangille** [comment]
Thank you.  Confirmed.  These settings allow both ./addhost.php and the website to work.

```
innodb_file_per_table=1
sql-mode=""
```

Do we agree that it was the config settings re MySQL which were preventing addhost.php from working?

**Comment by laf** [comment]
I would say so, using the stable branch is only a snapshot in time so if it didn't work there then everyone would be having the issue who were on the latest dev releases.
