### ISSUE TITLE
Discovery Broken

### ISSUE THREAD

**Issue by networkpadawan** [librenms/librenms#6890]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Since trying to add a vcenter host to discovery I get this informtion:

/app/librenms/discovery.php -h all -d
LibreNMS Discovery
===================================
Version info:
Commit SHA: 8d5c3f34f2117c27ee76c0a129c9634a8f065982
Commit Date: 1498462021
DB Schema: 195
PHP: 7.0.19
MySQL: 5.5.44-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
==================================DEBUG!
DB Schema update started....
SQL[SELECT version FROM `dbSchema` ORDER BY version DESC LIMIT 1] 
DB Schema already up to date.
Updating os_def.cache... PHP Fatal error:  Uncaught Symfony\Component\Yaml\Exception\ParseException: You cannot define a sequence item when in a mapping in /app/librenms/lib/influxdb-php/vendor/symfony/yaml/Parser.php:84
Stack trace:
#0 /app/librenms/lib/influxdb-php/vendor/symfony/yaml/Parser.php(215): Symfony\Component\Yaml\Parser->parse(Array, false, false, false)
#1 /app/librenms/lib/influxdb-php/vendor/symfony/yaml/Yaml.php(72): Symfony\Component\Yaml\Parser->parse(Array, false, false, false)
#2 /app/librenms/includes/common.php(1611): Symfony\Component\Yaml\Yaml::parse('os: ftos\ntext: ...')
#3 /app/librenms/includes/common.php(1633): load_all_os(false, false)
#4 /app/librenms/discovery.php(121): update_os_cache()
#5 {main}
  thrown in /app/librenms/lib/influxdb-php/vendor/symfony/yaml/Parser.php on line 84

Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: You cannot define a sequence item when in a mapping in /app/librenms/lib/influxdb-php/vendor/symfony/yaml/Parser.php:84
Stack trace:
#0 /app/librenms/lib/influxdb-php/vendor/symfony/yaml/Parser.php(215): Symfony\Component\Yaml\Parser->parse(Array, false, false, false)
#1 /app/librenms/lib/influxdb-php/vendor/symfony/yaml/Yaml.php(72): Symfony\Component\Yaml\Parser->parse(Array, false, false, false)
#2 /app/librenms/includes/common.php(1611): Symfony\Component\Yaml\Yaml::parse('os: ftos\ntext: ...')
#3 /app/librenms/includes/common.php(1633): load_all_os(false, false)
#4 /app/librenms/discovery.php(121): update_os_cache()
#5 {main}
  thrown in /app/librenms/lib/influxdb-php/vendor/symfony/yaml/Parser.php on line 84

Anyone know what it could be?

**Comment by networkpadawan** [comment]
just found the issue.
