### ISSUE TITLE
Distributed poller memcached problem?

### ISSUE THREAD

**Issue by xpatux** [librenms/librenms#7969]
Hi,

I'm having an issue with distributed poller. There is a server running a complete librenms install and another running just the cron jobs without web ui.

The error occurs on the first server when cronic cron job starts while the poller on the second server is still running:

```python
Traceback (most recent call last):
  File "/usr/local/librenms/poller-wrapper.py", line 158, in <module>
    if str(memc.get(master_tag)) == config['distributed_poller_name']:
  File "/usr/lib/python2.7/dist-packages/memcache.py", line 1093, in get
    return self._get('get', key)
  File "/usr/lib/python2.7/dist-packages/memcache.py", line 1077, in _get
    return _unsafe_get()
  File "/usr/lib/python2.7/dist-packages/memcache.py", line 1065, in _unsafe_get
    value = self._recv_value(server, flags, rlen)
  File "/usr/lib/python2.7/dist-packages/memcache.py", line 1257, in _recv_value
    raise ValueError('Unknown flags on get: %x' % flags)
ValueError: Unknown flags on get: 10
```
### validate.php output
```
Component | Version
--------- | -------
LibreNMS  | 1.33-280-g12373d0
DB Schema | 226
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 5.5.58-0ubuntu0.14.04.1-log
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
```

**Comment by laf** [comment]
This issue has been closed as it isn't classed as a bug or a new device request.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3
